export const skusByCategory: {
  category: string
  skus: {
    guid: string
    stringId: string
    name: string
    description: string
    tier: 'Business' | 'Enterprise' | 'Frontline' | 'Add-on' | 'Education' | 'Gov'
  }[]
}[] = [
  {
    category: 'Microsoft 365 Business',
    skus: [
      {
        guid: 'O365_BUSINESS_ESSENTIALS',
        stringId: 'O365_BUSINESS_ESSENTIALS',
        name: 'Microsoft 365 Business Basic',
        description: 'Web and mobile Office apps, Exchange, Teams, SharePoint, and 1TB OneDrive. No desktop Office apps. Max 300 users.',
        tier: 'Business',
      },
      {
        guid: 'O365_BUSINESS_PREMIUM',
        stringId: 'O365_BUSINESS_PREMIUM',
        name: 'Microsoft 365 Business Standard',
        description: 'Everything in Basic plus full desktop Office apps (Word, Excel, PowerPoint, etc.). Max 300 users.',
        tier: 'Business',
      },
      {
        guid: 'SPB',
        stringId: 'SPB',
        name: 'Microsoft 365 Business Premium',
        description: 'Business Standard plus Intune, Entra ID P1, Defender for Business, and advanced security features. Max 300 users.',
        tier: 'Business',
      },
      {
        guid: 'O365_BUSINESS',
        stringId: 'O365_BUSINESS',
        name: 'Microsoft 365 Apps for Business',
        description: 'Desktop Office apps and 1TB OneDrive only. No Exchange or Teams included. Max 300 users.',
        tier: 'Business',
      },
    ],
  },
  {
    category: 'Microsoft 365 Enterprise',
    skus: [
      {
        guid: '18181a46-0d4e-45cd-891e-60aabd171b4e',
        stringId: 'STANDARDPACK',
        name: 'Office 365 E1',
        description: 'Web/mobile Office apps, Exchange Online Plan 1, Teams, SharePoint. No desktop apps. Common in hybrid environments.',
        tier: 'Enterprise',
      },
      {
        guid: '6fd2c87f-b296-42f0-b197-1e91e994b900',
        stringId: 'ENTERPRISEPACK',
        name: 'Office 365 E3',
        description: 'Desktop Office apps, Exchange Online Plan 2, Teams, SharePoint, unlimited archive, and compliance tools. No advanced security.',
        tier: 'Enterprise',
      },
      {
        guid: 'c7df2760-2c81-4ef7-b578-5b5392b571df',
        stringId: 'ENTERPRISEPREMIUM',
        name: 'Office 365 E5',
        description: 'Everything in E3 plus Power BI Pro, Phone System, Audio Conferencing, and advanced compliance and threat intelligence.',
        tier: 'Enterprise',
      },
      {
        guid: 'ea126fc5-a19e-42e2-a731-da9d437bffcf',
        stringId: 'SPE_E3',
        name: 'Microsoft 365 E3',
        description: 'O365 E3 plus Windows 10/11 Enterprise, EMS E3 (Intune + Entra ID P1). Core enterprise bundle.',
        tier: 'Enterprise',
      },
      {
        guid: 'b05e124f-c7cc-45a0-a6aa-8cf78c946968',
        stringId: 'SPE_E5',
        name: 'Microsoft 365 E5',
        description: 'Microsoft 365 E3 plus Defender for Endpoint P2, Defender for Office 365 P2, Entra ID P2, and advanced compliance. Top-tier enterprise suite.',
        tier: 'Enterprise',
      },
      {
        guid: '26d45bd9-adf1-46cd-a9e1-51e9a5524128',
        stringId: 'ENTERPRISEPREMIUM_NOPSTNCONF',
        name: 'Office 365 E5 (No Audio Conferencing)',
        description: 'O365 E5 without the Audio Conferencing add-on. Useful when Teams Phone PSTN calling is not needed.',
        tier: 'Enterprise',
      },
      {
        guid: 'e8a166a6-1659-4c4e-95e9-d9e74f5cc77f',
        stringId: 'OFFICESUBSCRIPTION',
        name: 'Microsoft 365 Apps for Enterprise',
        description: 'Full desktop Office suite (Word, Excel, PowerPoint, Outlook, etc.) for enterprise users. No cloud services included.',
        tier: 'Enterprise',
      },
      {
        guid: 'ENTERPRISEPACK_USGOV_DOD',
        stringId: 'ENTERPRISEPACK_USGOV_DOD',
        name: 'Office 365 E3 (DoD)',
        description: 'O365 E3 for US Department of Defense GCC High/DoD environment.',
        tier: 'Gov',
      },
      {
        guid: 'MCOEV',
        stringId: 'MCOEV',
        name: 'Microsoft Teams Phone Standard',
        description: 'Adds Phone System to an existing M365 plan. Required for any PSTN calling scenario — direct routing, calling plans, or operator connect.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'Frontline Workers',
    skus: [
      {
        guid: 'e8b4befe-9c62-4b93-a387-4de8ae003c68',
        stringId: 'DESKLESSPACK',
        name: 'Office 365 F3',
        description: 'Web/mobile Office, Exchange (2GB mailbox), Teams, SharePoint for frontline workers. No desktop apps.',
        tier: 'Frontline',
      },
      {
        guid: '1e988bf3-8b7c-4731-bec7-b9cb1fbf8c4f',
        stringId: 'SPE_F1',
        name: 'Microsoft 365 F1',
        description: 'Teams, SharePoint, Yammer, basic Entra ID for frontline workers. No email or desktop Office apps.',
        tier: 'Frontline',
      },
      {
        guid: 'f2d3d257-bd8a-47e4-a0ae-ee70faea67a9',
        stringId: 'SPE_F3',
        name: 'Microsoft 365 F3',
        description: 'O365 F3 plus Windows 10/11 Enterprise (F edition), Intune, and Entra ID P1. Full frontline bundle with MDM.',
        tier: 'Frontline',
      },
    ],
  },
  {
    category: 'Exchange',
    skus: [
      {
        guid: 'EXCHANGESTANDARD',
        stringId: 'EXCHANGESTANDARD',
        name: 'Exchange Online Plan 1',
        description: '50GB mailbox, basic Exchange features. No In-Place Archive or advanced compliance. Common add-on for Teams-only users needing email.',
        tier: 'Add-on',
      },
      {
        guid: 'EXCHANGEENTERPRISE',
        stringId: 'EXCHANGEENTERPRISE',
        name: 'Exchange Online Plan 2',
        description: '100GB mailbox, unlimited archive, litigation hold, DLP, and voice mail. Required for In-Place Archive.',
        tier: 'Add-on',
      },
      {
        guid: 'EXCHANGE_S_ESSENTIALS',
        stringId: 'EXCHANGE_S_ESSENTIALS',
        name: 'Exchange Online Essentials',
        description: 'Basic Exchange Online for small business with 50GB mailbox. Includes basic anti-spam.',
        tier: 'Add-on',
      },
      {
        guid: 'EXCHANGEDESKLESS',
        stringId: 'EXCHANGEDESKLESS',
        name: 'Exchange Online Kiosk',
        description: '2GB mailbox for frontline/kiosk workers. Web access only. Minimum-cost Exchange option for shift workers.',
        tier: 'Add-on',
      },
      {
        guid: 'EXCHANGEARCHIVE_ADDON',
        stringId: 'EXCHANGEARCHIVE_ADDON',
        name: 'Exchange Online Archiving',
        description: 'Unlimited cloud-based archiving add-on for on-premises Exchange users (Exchange Online Archiving for Exchange Server).',
        tier: 'Add-on',
      },
      {
        guid: 'EOP_ENTERPRISE',
        stringId: 'EOP_ENTERPRISE',
        name: 'Exchange Online Protection',
        description: 'Anti-spam and anti-malware filtering for on-premises Exchange or standalone use.',
        tier: 'Add-on',
      },
      {
        guid: 'EXCHANGESTANDARD_GOV',
        stringId: 'EXCHANGESTANDARD_GOV',
        name: 'Exchange Online Plan 1 for Government',
        description: 'Exchange Online Plan 1 for GCC tenants with FedRAMP-compliant infrastructure.',
        tier: 'Gov',
      },
      {
        guid: 'EXCHANGEENTERPRISE_GOV',
        stringId: 'EXCHANGEENTERPRISE_GOV',
        name: 'Exchange Online Plan 2 for Government',
        description: 'Exchange Online Plan 2 for GCC tenants with unlimited archive and litigation hold.',
        tier: 'Gov',
      },
    ],
  },
  {
    category: 'Security & Compliance',
    skus: [
      {
        guid: 'EMS',
        stringId: 'EMS',
        name: 'Enterprise Mobility + Security E3',
        description: 'Intune, Entra ID P1, Azure Information Protection P1, and Advanced Threat Analytics.',
        tier: 'Add-on',
      },
      {
        guid: 'EMSPREMIUM',
        stringId: 'EMSPREMIUM',
        name: 'Enterprise Mobility + Security E5',
        description: 'EMS E3 plus Entra ID P2, Microsoft Defender for Identity, Defender for Cloud Apps, and AIP P2.',
        tier: 'Add-on',
      },
      {
        guid: 'INTUNE_A',
        stringId: 'INTUNE_A',
        name: 'Microsoft Intune Plan 1',
        description: 'MDM and MAM for all platforms (Windows, iOS, Android, macOS). Core device management for MSPs.',
        tier: 'Add-on',
      },
      {
        guid: 'INTUNE_A_D',
        stringId: 'INTUNE_A_D',
        name: 'Microsoft Intune Plan 2',
        description: 'Intune Plan 1 plus endpoint privilege management, Intune Tunnel, and specialty device management.',
        tier: 'Add-on',
      },
      {
        guid: 'INTUNE_SMB',
        stringId: 'INTUNE_SMB',
        name: 'Microsoft Intune for SMB',
        description: 'Simplified Intune for SMB environments. Included in Microsoft 365 Business Premium.',
        tier: 'Business',
      },
      {
        guid: '078d2b04-f1bd-4111-bbd4-b4b1b354cef4',
        stringId: 'AAD_PREMIUM',
        name: 'Microsoft Entra ID P1',
        description: 'Conditional Access, MFA, SSPR, hybrid identity, dynamic groups, and group-based licensing. Formerly Azure AD Premium P1.',
        tier: 'Add-on',
      },
      {
        guid: '84a661c4-e949-4bd2-a560-ed7766fcaf2b',
        stringId: 'AAD_PREMIUM_P2',
        name: 'Microsoft Entra ID P2',
        description: 'Entra ID P1 plus Identity Protection (risk-based Conditional Access) and Privileged Identity Management (PIM). Formerly Azure AD Premium P2.',
        tier: 'Add-on',
      },
      {
        guid: 'AAD_BASIC',
        stringId: 'AAD_BASIC',
        name: 'Microsoft Entra ID Basic',
        description: 'Basic Entra ID with group management and SSO. No Conditional Access or MFA. Typically included in O365 licenses.',
        tier: 'Add-on',
      },
      {
        guid: 'MFA_PREMIUM',
        stringId: 'MFA_PREMIUM',
        name: 'Microsoft Entra Multi-Factor Authentication',
        description: 'Standalone MFA license. Typically included within Entra ID P1/P2. Enables per-user MFA without Conditional Access.',
        tier: 'Add-on',
      },
      {
        guid: 'DEFENDER_ENDPOINT_P1',
        stringId: 'DEFENDER_ENDPOINT_P1',
        name: 'Microsoft Defender for Endpoint P1',
        description: 'Next-gen antivirus, attack surface reduction, and device control. Included in Microsoft 365 Business Premium.',
        tier: 'Add-on',
      },
      {
        guid: 'DEFENDER_ENDPOINT_P2',
        stringId: 'DEFENDER_ENDPOINT_P2',
        name: 'Microsoft Defender for Endpoint P2',
        description: 'P1 plus EDR, automated investigation and remediation, threat hunting, and vulnerability management (TVM).',
        tier: 'Add-on',
      },
      {
        guid: 'MDATP_XPLAT',
        stringId: 'MDATP_XPLAT',
        name: 'Microsoft Defender for Endpoint (Cross-Platform)',
        description: 'Defender for Endpoint coverage for Linux, macOS, iOS, and Android devices.',
        tier: 'Add-on',
      },
      {
        guid: 'MDO_SMB',
        stringId: 'MDO_SMB',
        name: 'Microsoft Defender for Business',
        description: 'Simplified EDR and endpoint protection for SMBs (up to 300 users). Included in M365 Business Premium. Also available standalone.',
        tier: 'Business',
      },
      {
        guid: 'THREAT_INTELLIGENCE',
        stringId: 'THREAT_INTELLIGENCE',
        name: 'Microsoft Defender for Office 365 P2',
        description: 'Safe Links, Safe Attachments, anti-phishing, attack simulator, threat hunting, and automated investigation.',
        tier: 'Add-on',
      },
      {
        guid: 'ATP_ENTERPRISE',
        stringId: 'ATP_ENTERPRISE',
        name: 'Microsoft Defender for Office 365 P1',
        description: 'Safe Links, Safe Attachments, and anti-phishing protection for Exchange, SharePoint, Teams, and OneDrive.',
        tier: 'Add-on',
      },
      {
        guid: 'ADALLOM_STANDALONE',
        stringId: 'ADALLOM_STANDALONE',
        name: 'Microsoft Defender for Cloud Apps',
        description: 'Cloud Access Security Broker (CASB). Shadow IT discovery, session control, app governance, and threat protection across SaaS apps.',
        tier: 'Add-on',
      },
      {
        guid: 'ATA',
        stringId: 'ATA',
        name: 'Microsoft Defender for Identity',
        description: 'Detects advanced AD-based threats. Monitors for lateral movement, pass-the-hash, DCSync, and Golden Ticket attacks. Formerly Azure ATP.',
        tier: 'Add-on',
      },
      {
        guid: 'INFORMATION_PROTECTION_COMPLIANCE',
        stringId: 'INFORMATION_PROTECTION_COMPLIANCE',
        name: 'Microsoft 365 E5 Compliance',
        description: 'Purview information protection, insider risk management, eDiscovery, and compliance manager. Add-on for E3 customers.',
        tier: 'Add-on',
      },
      {
        guid: 'IDENTITY_THREAT_PROTECTION',
        stringId: 'IDENTITY_THREAT_PROTECTION',
        name: 'Microsoft 365 E5 Security',
        description: 'Defender for Endpoint P2, Defender for Office 365 P2, Defender for Identity, Entra ID P2, and Defender for Cloud Apps. Add-on to E3.',
        tier: 'Add-on',
      },
      {
        guid: 'c52ea49f-fe5d-4e95-93ba-1de91d380f89',
        stringId: 'RIGHTSMANAGEMENT',
        name: 'Azure Information Protection Plan 1',
        description: 'Classify, label, and protect documents and emails. Included in most M365 plans. Formerly AIP P1.',
        tier: 'Add-on',
      },
      {
        guid: 'RIGHTSMANAGEMENT_PREMIUM',
        stringId: 'RIGHTSMANAGEMENT_PREMIUM',
        name: 'Azure Information Protection Plan 2',
        description: 'AIP P1 plus automatic classification, on-premises scanner, and unified labeling. For organizations with strict data classification requirements.',
        tier: 'Add-on',
      },
      {
        guid: 'c2e41e49-e2a2-4c55-832a-cf13ffba1d6a',
        stringId: '10_ALR_ADDON',
        name: '10-Year Audit Log Retention Add-On',
        description: 'Extends Microsoft Purview audit log retention to 10 years. Required for long-term compliance and forensic investigations.',
        tier: 'Add-on',
      },
      {
        guid: 'CMPA_addon',
        stringId: 'CMPA_addon',
        name: 'Compliance Manager Premium Assessment Add-On',
        description: 'Additional regulatory compliance assessments beyond the templates included in Compliance Manager.',
        tier: 'Add-on',
      },
      {
        guid: 'MICROSOFT_COMMUNICATIONS_COMPLIANCE',
        stringId: 'MICROSOFT_COMMUNICATIONS_COMPLIANCE',
        name: 'Microsoft Purview Communication Compliance',
        description: 'Monitors Teams, Exchange, and third-party communications for policy violations. Used for regulatory and HR compliance.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'Microsoft Entra',
    skus: [
      {
        guid: '078d2b04-f1bd-4111-bbd4-b4b1b354cef4',
        stringId: 'AAD_PREMIUM',
        name: 'Microsoft Entra ID P1',
        description: 'Conditional Access, MFA, SSPR, dynamic groups, hybrid join, group-based licensing. Formerly Azure AD P1.',
        tier: 'Add-on',
      },
      {
        guid: '84a661c4-e949-4bd2-a560-ed7766fcaf2b',
        stringId: 'AAD_PREMIUM_P2',
        name: 'Microsoft Entra ID P2',
        description: 'Entra ID P1 plus Identity Protection (risk-based CA) and Privileged Identity Management (PIM). Formerly Azure AD P2.',
        tier: 'Add-on',
      },
      {
        guid: 'ENTRA_IDENTITY_GOVERNANCE',
        stringId: 'ENTRA_IDENTITY_GOVERNANCE',
        name: 'Microsoft Entra ID Governance',
        description: 'Access reviews, entitlement management, lifecycle workflows, and Privileged Access Management for internal and external identities.',
        tier: 'Add-on',
      },
      {
        guid: 'MCASFAS',
        stringId: 'MCASFAS',
        name: 'Microsoft Entra Permissions Management',
        description: 'Cloud Infrastructure Entitlement Management (CIEM) for Azure, AWS, and GCP. Detects and remediates over-provisioned permissions.',
        tier: 'Add-on',
      },
      {
        guid: 'ENTRA_WORKLOAD_IDENTITIES',
        stringId: 'ENTRA_WORKLOAD_IDENTITIES',
        name: 'Microsoft Entra Workload Identities Premium',
        description: 'Conditional Access and Identity Protection for apps, service principals, and managed identities (non-human accounts).',
        tier: 'Add-on',
      },
      {
        guid: 'ENTRA_SUITE',
        stringId: 'ENTRA_SUITE',
        name: 'Microsoft Entra Suite',
        description: 'Bundles Entra ID P2, Entra ID Governance, Entra Internet Access, Entra Private Access, and Entra Workload Identities at a discount.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'Microsoft Copilot',
    skus: [
      {
        guid: '639dec6b-bb19-468b-871c-c5c441c4b0cb',
        stringId: 'Microsoft_365_Copilot',
        name: 'Microsoft 365 Copilot',
        description: 'AI assistant integrated into Word, Excel, PowerPoint, Outlook, Teams, and more. Requires M365 E3/E5 or Business Standard/Premium.',
        tier: 'Add-on',
      },
      {
        guid: 'COPILOT_STUDIO_VIRAL',
        stringId: 'COPILOT_STUDIO_VIRAL',
        name: 'Microsoft Copilot Studio (Trial)',
        description: 'Trial license for Copilot Studio allowing users to build custom copilots and agents. Often self-service assigned.',
        tier: 'Add-on',
      },
      {
        guid: 'POWER_VIRTUAL_AGENTS_VIRAL',
        stringId: 'POWER_VIRTUAL_AGENTS_VIRAL',
        name: 'Power Virtual Agents Viral',
        description: 'Trial/viral license for Power Virtual Agents (now Copilot Studio). Appears on tenants where users self-enrolled.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'Windows 365 (Cloud PC)',
    skus: [
      {
        guid: 'CPC_B_1C_2RAM_64GB',
        stringId: 'CPC_B_1C_2RAM_64GB',
        name: 'Windows 365 Business 1 vCPU / 2 GB / 64 GB',
        description: 'Entry-level Cloud PC for light tasks. 1 vCPU, 2GB RAM, 64GB storage. Suitable for task workers with web-based workloads.',
        tier: 'Business',
      },
      {
        guid: 'CPC_B_2C_4RAM_64GB',
        stringId: 'CPC_B_2C_4RAM_64GB',
        name: 'Windows 365 Business 2 vCPU / 4 GB / 64 GB',
        description: '2 vCPU, 4GB RAM, 64GB storage Cloud PC. Suitable for light productivity and Office users.',
        tier: 'Business',
      },
      {
        guid: 'CPC_B_2C_4RAM_128GB',
        stringId: 'CPC_B_2C_4RAM_128GB',
        name: 'Windows 365 Business 2 vCPU / 4 GB / 128 GB',
        description: '2 vCPU, 4GB RAM, 128GB storage Cloud PC for users needing more local storage.',
        tier: 'Business',
      },
      {
        guid: 'CPC_B_2C_8RAM_128GB',
        stringId: 'CPC_B_2C_8RAM_128GB',
        name: 'Windows 365 Business 2 vCPU / 8 GB / 128 GB',
        description: '2 vCPU, 8GB RAM, 128GB storage. Balanced Cloud PC for standard productivity workloads.',
        tier: 'Business',
      },
      {
        guid: 'CPC_B_4C_16RAM_128GB',
        stringId: 'CPC_B_4C_16RAM_128GB',
        name: 'Windows 365 Business 4 vCPU / 16 GB / 128 GB',
        description: '4 vCPU, 16GB RAM, 128GB storage. Performance Cloud PC for demanding business applications.',
        tier: 'Business',
      },
      {
        guid: 'CPC_B_8C_32RAM_128GB',
        stringId: 'CPC_B_8C_32RAM_128GB',
        name: 'Windows 365 Business 8 vCPU / 32 GB / 128 GB',
        description: '8 vCPU, 32GB RAM, 128GB storage. High-performance Cloud PC for power users and developers.',
        tier: 'Business',
      },
      {
        guid: 'CPC_E_2C_4RAM_64GB',
        stringId: 'CPC_E_2C_4RAM_64GB',
        name: 'Windows 365 Enterprise 2 vCPU / 4 GB / 64 GB',
        description: 'Enterprise Cloud PC with Intune management, custom images, and advanced networking. 2 vCPU, 4GB RAM, 64GB storage.',
        tier: 'Enterprise',
      },
      {
        guid: 'CPC_E_2C_8RAM_128GB',
        stringId: 'CPC_E_2C_8RAM_128GB',
        name: 'Windows 365 Enterprise 2 vCPU / 8 GB / 128 GB',
        description: 'Enterprise Cloud PC with Intune and Entra join support. 2 vCPU, 8GB RAM, 128GB storage.',
        tier: 'Enterprise',
      },
      {
        guid: 'CPC_E_4C_16RAM_128GB',
        stringId: 'CPC_E_4C_16RAM_128GB',
        name: 'Windows 365 Enterprise 4 vCPU / 16 GB / 128 GB',
        description: 'Enterprise Cloud PC. 4 vCPU, 16GB RAM, 128GB. Common tier for knowledge workers needing a full Windows experience.',
        tier: 'Enterprise',
      },
      {
        guid: 'CPC_E_8C_32RAM_256GB',
        stringId: 'CPC_E_8C_32RAM_256GB',
        name: 'Windows 365 Enterprise 8 vCPU / 32 GB / 256 GB',
        description: 'High-performance Enterprise Cloud PC for power users and developers. 8 vCPU, 32GB RAM, 256GB storage.',
        tier: 'Enterprise',
      },
    ],
  },
  {
    category: 'Teams & Communication',
    skus: [
      {
        guid: 'TEAMS_ESSENTIALS',
        stringId: 'TEAMS_ESSENTIALS',
        name: 'Microsoft Teams Essentials',
        description: 'Teams meetings (30hr limit), 10GB cloud storage, group chat. No Exchange, SharePoint, or full Office. Lowest-cost Teams option.',
        tier: 'Business',
      },
      {
        guid: 'TEAMS_EXPLORATORY',
        stringId: 'TEAMS_EXPLORATORY',
        name: 'Microsoft Teams Exploratory',
        description: 'Free trial license automatically assigned to eligible users without a Teams license. Should be converted to paid before expiration.',
        tier: 'Add-on',
      },
      {
        guid: 'MCOEV',
        stringId: 'MCOEV',
        name: 'Microsoft Teams Phone Standard',
        description: 'Adds Phone System to an existing M365 plan. Required for any calling scenario — direct routing, calling plans, or operator connect.',
        tier: 'Add-on',
      },
      {
        guid: 'MCOEV_GOV',
        stringId: 'MCOEV_GOV',
        name: 'Microsoft Teams Phone Standard for GCC',
        description: 'Teams Phone Standard for GCC government tenants.',
        tier: 'Gov',
      },
      {
        guid: 'Microsoft_Teams_Rooms_Basic',
        stringId: 'Microsoft_Teams_Rooms_Basic',
        name: 'Microsoft Teams Rooms Basic',
        description: 'Free Teams Rooms license for up to 25 rooms. Basic meeting room functionality without advanced management features.',
        tier: 'Add-on',
      },
      {
        guid: 'Microsoft_Teams_Rooms_Pro',
        stringId: 'Microsoft_Teams_Rooms_Pro',
        name: 'Microsoft Teams Rooms Pro',
        description: 'Full Teams Rooms license with advanced management, AI-powered video, and Intune integration for meeting room devices.',
        tier: 'Add-on',
      },
      {
        guid: 'MCOPSTN1',
        stringId: 'MCOPSTN1',
        name: 'Microsoft 365 Domestic Calling Plan',
        description: 'PSTN minutes for domestic calls within a single country. Requires Teams Phone Standard (MCOEV).',
        tier: 'Add-on',
      },
      {
        guid: 'MCOPSTN2',
        stringId: 'MCOPSTN2',
        name: 'Microsoft 365 Domestic and International Calling Plan',
        description: 'PSTN minutes for domestic and international calls. Requires Teams Phone Standard.',
        tier: 'Add-on',
      },
      {
        guid: 'MCOPSTN5',
        stringId: 'MCOPSTN5',
        name: 'Microsoft 365 Domestic Calling Plan (120 min)',
        description: 'Low-volume domestic calling plan with 120 minutes per user per month. For light callers.',
        tier: 'Add-on',
      },
      {
        guid: 'MCOMEETADV',
        stringId: 'MCOMEETADV',
        name: 'Microsoft 365 Audio Conferencing',
        description: 'Dial-in PSTN conferencing for Teams meetings. Included in O365 E5. Add-on for E3 and Business plans.',
        tier: 'Add-on',
      },
      {
        guid: 'MCOPSTNC',
        stringId: 'MCOPSTNC',
        name: 'Communications Credits',
        description: 'Pay-as-you-go PSTN minutes for calling plan overages and audio conferencing. Required if calling plan minutes run out.',
        tier: 'Add-on',
      },
      {
        guid: 'ADV_COMMS',
        stringId: 'ADV_COMMS',
        name: 'Advanced Communications',
        description: 'Large meetings (up to 20,000 attendees), custom meeting branding, compliance recording, and advanced admin tools for Teams.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'Microsoft Viva',
    skus: [
      {
        guid: 'VIVA',
        stringId: 'VIVA',
        name: 'Microsoft Viva Suite',
        description: 'Full employee experience platform: Viva Insights, Learning, Topics, Goals, Connections, and Engage. Bundled at a discount over individual SKUs.',
        tier: 'Add-on',
      },
      {
        guid: 'VIVA_INSIGHTS_P1',
        stringId: 'VIVA_INSIGHTS_P1',
        name: 'Microsoft Viva Insights',
        description: 'Personal, manager, and leader insights into work patterns and wellbeing using M365 data. Privacy-protected analytics.',
        tier: 'Add-on',
      },
      {
        guid: 'VIVA_LEARNING',
        stringId: 'VIVA_LEARNING',
        name: 'Microsoft Viva Learning',
        description: 'Learning management integration in Teams. Surfaces content from LinkedIn Learning, Microsoft Learn, and third-party LMS providers.',
        tier: 'Add-on',
      },
      {
        guid: 'VIVA_TOPICS',
        stringId: 'VIVA_TOPICS',
        name: 'Microsoft Viva Topics',
        description: 'AI-powered knowledge discovery. Automatically identifies topics and surfaces expert connections and knowledge pages in M365.',
        tier: 'Add-on',
      },
      {
        guid: 'VIVA_GOALS',
        stringId: 'VIVA_GOALS',
        name: 'Microsoft Viva Goals',
        description: 'OKR (Objectives and Key Results) management tool integrated with Teams and M365. Aligns team goals with organizational strategy.',
        tier: 'Add-on',
      },
      {
        guid: 'VIVAENGAGE_CORE',
        stringId: 'VIVAENGAGE_CORE',
        name: 'Viva Engage Core',
        description: 'Social networking and communities inside Teams. The modern Yammer experience embedded in Microsoft 365.',
        tier: 'Add-on',
      },
      {
        guid: 'VIVA_ENGAGE_COMMUNITIES_AND_COMMUNICATIONS',
        stringId: 'VIVA_ENGAGE_COMMUNITIES_AND_COMMUNICATIONS',
        name: 'Viva Engage Communities and Communications',
        description: 'Advanced Viva Engage with leadership communications, analytics, and storyline features.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'SharePoint & OneDrive',
    skus: [
      {
        guid: 'SHAREPOINTSTANDARD',
        stringId: 'SHAREPOINTSTANDARD',
        name: 'SharePoint Online Plan 1',
        description: 'SharePoint Online with 1TB storage and core collaboration features. No compliance features or unlimited storage.',
        tier: 'Add-on',
      },
      {
        guid: 'SHAREPOINTENTERPRISE',
        stringId: 'SHAREPOINTENTERPRISE',
        name: 'SharePoint Online Plan 2',
        description: 'Full SharePoint Online with unlimited storage, eDiscovery, Business Connectivity Services, and advanced compliance.',
        tier: 'Add-on',
      },
      {
        guid: 'ONEDRIVE_BASIC',
        stringId: 'ONEDRIVE_BASIC',
        name: 'OneDrive for Business Plan 1',
        description: '1TB OneDrive for Business storage per user. Basic file sync and sharing without advanced compliance.',
        tier: 'Add-on',
      },
      {
        guid: 'WACONEDRIVEENTERPRISE',
        stringId: 'WACONEDRIVEENTERPRISE',
        name: 'OneDrive for Business Plan 2',
        description: 'Unlimited OneDrive for Business storage per user with advanced compliance, DLP, and in-place hold.',
        tier: 'Add-on',
      },
      {
        guid: 'SYNTEX',
        stringId: 'SYNTEX',
        name: 'Microsoft Syntex',
        description: 'AI-powered content understanding. Automatically classifies documents, extracts data, and applies metadata in SharePoint.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'Microsoft 365 Apps',
    skus: [
      {
        guid: 'e8a166a6-1659-4c4e-95e9-d9e74f5cc77f',
        stringId: 'OFFICESUBSCRIPTION',
        name: 'Microsoft 365 Apps for Enterprise',
        description: 'Full desktop Office suite (Word, Excel, PowerPoint, Outlook, etc.) for enterprise. No cloud services included.',
        tier: 'Enterprise',
      },
      {
        guid: 'O365_BUSINESS',
        stringId: 'O365_BUSINESS',
        name: 'Microsoft 365 Apps for Business',
        description: 'Full desktop Office suite for up to 300 users with 1TB OneDrive. No Exchange or Teams.',
        tier: 'Business',
      },
    ],
  },
  {
    category: 'Power Platform',
    skus: [
      {
        guid: 'POWER_BI_STANDARD',
        stringId: 'POWER_BI_STANDARD',
        name: 'Microsoft Fabric (Free) / Power BI Free',
        description: 'Free Power BI and Fabric with limited sharing. No premium features or workspace publishing to others.',
        tier: 'Add-on',
      },
      {
        guid: 'POWER_BI_PRO',
        stringId: 'POWER_BI_PRO',
        name: 'Power BI Pro',
        description: 'Full Power BI with sharing, collaboration, and publishing to workspaces. Required to share dashboards with other Pro users.',
        tier: 'Add-on',
      },
      {
        guid: 'POWER_BI_PREMIUM_PER_USER',
        stringId: 'POWER_BI_PREMIUM_PER_USER',
        name: 'Power BI Premium Per User',
        description: 'Power BI Premium features per user: paginated reports, AI insights, larger data models, and increased dataset refresh rates.',
        tier: 'Add-on',
      },
      {
        guid: 'FLOW_FREE',
        stringId: 'FLOW_FREE',
        name: 'Power Automate Free',
        description: 'Free Power Automate with limited runs and standard connectors. Often auto-assigned. Upgrade for premium connectors or more runs.',
        tier: 'Add-on',
      },
      {
        guid: 'FLOW_PER_USER',
        stringId: 'FLOW_PER_USER',
        name: 'Power Automate per User Plan',
        description: 'Unlimited flows with premium and custom connectors for a single user. Includes attended RPA capabilities.',
        tier: 'Add-on',
      },
      {
        guid: 'POWERAPPS_PER_USER',
        stringId: 'POWERAPPS_PER_USER',
        name: 'Power Apps per User Plan',
        description: 'Unlimited Power Apps for a single user including premium connectors and Dataverse.',
        tier: 'Add-on',
      },
      {
        guid: 'POWERAPPS_PER_APP',
        stringId: 'POWERAPPS_PER_APP',
        name: 'Power Apps per App Plan',
        description: 'Single-app license for one Power App per user. Cost-effective for targeted app deployments without a full per-user plan.',
        tier: 'Add-on',
      },
      {
        guid: 'POWERAPPS_VIRAL',
        stringId: 'POWERAPPS_VIRAL',
        name: 'Power Apps Trial / Viral',
        description: 'Self-service trial license for Power Apps. Appears when users sign up independently. Should be managed and converted centrally.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'Visio',
    skus: [
      {
        guid: 'VISIO_PLAN1_NAT',
        stringId: 'VISIO_PLAN1_NAT',
        name: 'Visio Plan 1',
        description: 'Web-based Visio only. Create and edit diagrams in a browser using standard templates.',
        tier: 'Add-on',
      },
      {
        guid: 'VISIOCLIENT',
        stringId: 'VISIOCLIENT',
        name: 'Visio Plan 2',
        description: 'Full desktop Visio application plus web version. Advanced diagramming, data linking, and process automation.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'Project',
    skus: [
      {
        guid: 'PROJECTESSENTIALS',
        stringId: 'PROJECTESSENTIALS',
        name: 'Project Plan 1',
        description: 'Web-based Project only. Basic task management, board views, and team collaboration.',
        tier: 'Add-on',
      },
      {
        guid: 'PROJECTPREMIUM',
        stringId: 'PROJECTPREMIUM',
        name: 'Project Plan 3',
        description: 'Web and desktop Project. Full project management with resource management, timesheets, and reporting.',
        tier: 'Add-on',
      },
      {
        guid: 'PROJECTPROFESSIONAL',
        stringId: 'PROJECTPROFESSIONAL',
        name: 'Project Plan 5',
        description: 'Everything in Plan 3 plus Portfolio management, advanced resource analytics, and enterprise project management.',
        tier: 'Add-on',
      },
    ],
  },
  {
    category: 'Dynamics 365',
    skus: [
      {
        guid: 'DYN365_ENTERPRISE_SALES',
        stringId: 'DYN365_ENTERPRISE_SALES',
        name: 'Dynamics 365 Sales Enterprise',
        description: 'Full CRM with sales automation, AI-powered forecasting, and LinkedIn Sales Navigator integration.',
        tier: 'Enterprise',
      },
      {
        guid: 'DYN365_ENTERPRISE_CUSTOMER_SERVICE',
        stringId: 'DYN365_ENTERPRISE_CUSTOMER_SERVICE',
        name: 'Dynamics 365 Customer Service Enterprise',
        description: 'Case management, routing, knowledge base, SLAs, and omnichannel support capabilities.',
        tier: 'Enterprise',
      },
      {
        guid: 'DYN365_FINANCIALS_BUSINESS_SKU',
        stringId: 'DYN365_FINANCIALS_BUSINESS_SKU',
        name: 'Dynamics 365 Business Central Essentials',
        description: 'ERP for SMBs: financial management, supply chain, projects, and HR. No manufacturing.',
        tier: 'Business',
      },
      {
        guid: 'DYN365_BUSINESS_PREMIUM',
        stringId: 'DYN365_BUSINESS_PREMIUM',
        name: 'Dynamics 365 Business Central Premium',
        description: 'Business Central Essentials plus manufacturing and service order management.',
        tier: 'Business',
      },
      {
        guid: 'DYN365_TEAM_MEMBERS',
        stringId: 'DYN365_TEAM_MEMBERS',
        name: 'Dynamics 365 Team Members',
        description: 'Light Dynamics 365 license for users who only need read access and basic updates. Lowest-cost D365 user license.',
        tier: 'Add-on',
      },
      {
        guid: 'CRMSTANDARD',
        stringId: 'CRMSTANDARD',
        name: 'Dynamics CRM Online Professional',
        description: 'Legacy Dynamics CRM Online license. May still appear on older tenants. Replaced by Dynamics 365 Sales.',
        tier: 'Enterprise',
      },
    ],
  },
  {
    category: 'Education',
    skus: [
      {
        guid: 'STANDARDWOFFPACK_FACULTY',
        stringId: 'STANDARDWOFFPACK_FACULTY',
        name: 'Office 365 Education for Faculty',
        description: 'Full Office 365 suite for faculty including desktop apps, Exchange, Teams, and SharePoint.',
        tier: 'Education',
      },
      {
        guid: 'STANDARDWOFFPACK_STUDENT',
        stringId: 'STANDARDWOFFPACK_STUDENT',
        name: 'Office 365 Education for Students',
        description: 'Office 365 for students — typically free with institutional email verification.',
        tier: 'Education',
      },
      {
        guid: 'M365EDU_A1',
        stringId: 'M365EDU_A1',
        name: 'Microsoft 365 A1',
        description: 'Free tier for education. Web-based Office, Teams, SharePoint. No desktop apps. Available to students and faculty.',
        tier: 'Education',
      },
      {
        guid: 'M365EDU_A3_FACULTY',
        stringId: 'M365EDU_A3_FACULTY',
        name: 'Microsoft 365 A3 for Faculty',
        description: 'Microsoft 365 E3 equivalent for faculty with education-specific compliance tools and School Data Sync.',
        tier: 'Education',
      },
      {
        guid: 'M365EDU_A3_STUDENT',
        stringId: 'M365EDU_A3_STUDENT',
        name: 'Microsoft 365 A3 for Students',
        description: 'Microsoft 365 E3 equivalent for students at discounted education pricing.',
        tier: 'Education',
      },
      {
        guid: 'M365EDU_A5_FACULTY',
        stringId: 'M365EDU_A5_FACULTY',
        name: 'Microsoft 365 A5 for Faculty',
        description: 'Microsoft 365 E5 equivalent for faculty including advanced security, compliance, and Power BI.',
        tier: 'Education',
      },
      {
        guid: 'M365EDU_A5_STUDENT',
        stringId: 'M365EDU_A5_STUDENT',
        name: 'Microsoft 365 A5 for Students',
        description: 'Microsoft 365 E5 equivalent for students. Full security and compliance features at education pricing.',
        tier: 'Education',
      },
      {
        guid: 'AAD_PREMIUM_FACULTY',
        stringId: 'AAD_PREMIUM_FACULTY',
        name: 'Microsoft Entra ID P1 for Faculty',
        description: 'Entra ID P1 for educational institutions — Conditional Access and MFA for faculty accounts.',
        tier: 'Education',
      },
      {
        guid: 'INTUNE_EDU',
        stringId: 'INTUNE_EDU',
        name: 'Intune for Education',
        description: 'Simplified device management for schools. Streamlined Intune console for managing student and teacher devices.',
        tier: 'Education',
      },
    ],
  },
  {
    category: 'Government (GCC / GCCH / DoD)',
    skus: [
      {
        guid: 'ENTERPRISEPACK_GOV',
        stringId: 'ENTERPRISEPACK_GOV',
        name: 'Office 365 E3 for Government',
        description: 'O365 E3 for GCC tenants with FedRAMP Moderate compliance.',
        tier: 'Gov',
      },
      {
        guid: 'ENTERPRISEPREMIUM_GOV',
        stringId: 'ENTERPRISEPREMIUM_GOV',
        name: 'Office 365 E5 for Government',
        description: 'O365 E5 for GCC tenants. Includes advanced compliance and threat intelligence on FedRAMP-compliant infrastructure.',
        tier: 'Gov',
      },
      {
        guid: 'SPE_E3_GOV',
        stringId: 'SPE_E3_GOV',
        name: 'Microsoft 365 E3 for Government',
        description: 'Microsoft 365 E3 for GCC environments — O365 E3 Gov + Intune Gov + EMS E3 Gov.',
        tier: 'Gov',
      },
      {
        guid: 'SPE_E5_GOV',
        stringId: 'SPE_E5_GOV',
        name: 'Microsoft 365 E5 for Government',
        description: 'Microsoft 365 E5 for GCC environments. Full enterprise security and compliance suite on FedRAMP High infrastructure.',
        tier: 'Gov',
      },
      {
        guid: 'SPE_F1_GOV',
        stringId: 'SPE_F1_GOV',
        name: 'Microsoft 365 F1 for Government',
        description: 'Frontline worker license for GCC government environments.',
        tier: 'Gov',
      },
      {
        guid: 'DESKLESSPACK_GOV',
        stringId: 'DESKLESSPACK_GOV',
        name: 'Office 365 F3 for Government',
        description: 'Office 365 F3 for GCC tenants. Frontline worker license with FedRAMP compliance.',
        tier: 'Gov',
      },
      {
        guid: 'INTUNE_A_GOV',
        stringId: 'INTUNE_A_GOV',
        name: 'Microsoft Intune for Government',
        description: 'Intune MDM/MAM for GCC tenants. FedRAMP-compliant device management.',
        tier: 'Gov',
      },
      {
        guid: 'MCOEV_GOV',
        stringId: 'MCOEV_GOV',
        name: 'Microsoft Teams Phone Standard for GCC',
        description: 'Teams Phone System for GCC government tenants.',
        tier: 'Gov',
      },
      {
        guid: 'EXCHANGESTANDARD_GOV',
        stringId: 'EXCHANGESTANDARD_GOV',
        name: 'Exchange Online Plan 1 for Government',
        description: 'Exchange Online Plan 1 on FedRAMP-compliant GCC infrastructure.',
        tier: 'Gov',
      },
      {
        guid: 'RIGHTSMANAGEMENT_CE_GOV',
        stringId: 'RIGHTSMANAGEMENT_CE_GOV',
        name: 'Azure Information Protection P1 for Government',
        description: 'AIP Plan 1 (sensitivity labels and protection) for GCC environments.',
        tier: 'Gov',
      },
    ],
  },
  {
    category: 'Legacy & Retired SKUs',
    skus: [
      {
        guid: 'MCOSTANDARD',
        stringId: 'MCOSTANDARD',
        name: 'Skype for Business Online Plan 2',
        description: 'Legacy Skype for Business Online license. No longer sold but may still appear on older tenants. Fully replaced by Microsoft Teams.',
        tier: 'Add-on',
      },
      {
        guid: 'YAMMER_ENTERPRISE',
        stringId: 'YAMMER_ENTERPRISE',
        name: 'Yammer Enterprise',
        description: 'Legacy Yammer enterprise networking license. Now surfaced as Viva Engage. Still appears as a service plan within M365 licenses.',
        tier: 'Add-on',
      },
      {
        guid: 'STREAM',
        stringId: 'STREAM',
        name: 'Microsoft Stream (Classic)',
        description: 'Legacy Stream video platform license. Replaced by Stream (on SharePoint). Still appears as a service plan on older tenants.',
        tier: 'Add-on',
      },
      {
        guid: 'SPZA_IW',
        stringId: 'SPZA_IW',
        name: 'App Connect',
        description: 'Legacy app integration license. Appears on older tenants. Provides basic app connectivity services.',
        tier: 'Add-on',
      },
      {
        guid: 'WIN10_VDA_E3',
        stringId: 'WIN10_VDA_E3',
        name: 'Windows 10/11 Enterprise E3 (VDA)',
        description: 'Virtual Desktop Access license for Windows Enterprise features on non-qualifying hardware or VMs. Separate from M365 E3.',
        tier: 'Enterprise',
      },
      {
        guid: 'WIN10_VDA_E5',
        stringId: 'WIN10_VDA_E5',
        name: 'Windows 10/11 Enterprise E5 (VDA)',
        description: 'VDA license adding Credential Guard and Defender for Endpoint. For AVD and non-qualifying hardware scenarios.',
        tier: 'Enterprise',
      },
      {
        guid: 'RIGHTSMANAGEMENT_ADHOC',
        stringId: 'RIGHTSMANAGEMENT_ADHOC',
        name: 'Rights Management Adhoc',
        description: 'Free RMS license auto-assigned when a user receives an RMS-protected document. Not purchasable — appears automatically on the tenant.',
        tier: 'Add-on',
      },
      {
        guid: 'SMB_APPS',
        stringId: 'SMB_APPS',
        name: 'Business Apps (Free)',
        description: 'Legacy free license including Microsoft Bookings and Invoicing. May appear on older SMB tenants.',
        tier: 'Business',
      },
      {
        guid: 'OFFICEBASIC',
        stringId: 'OFFICEBASIC',
        name: 'Basic Collaboration',
        description: 'Legacy minimal license including Exchange Online, OneDrive, and Skype Meetings. Rarely seen on modern tenants.',
        tier: 'Add-on',
      },
    ],
  },
];
