export const errorsByCategory: {
  category: string
  errors: {
    hex: string
    decimal: number
    name: string
    description: string
    severity: 'Info' | 'Warning' | 'Error' | 'Critical'
  }[]
}[] = [
  {
    category: 'Common System Errors',
    errors: [
      { hex: '0x00000000', decimal: 0, name: 'ERROR_SUCCESS', description: 'Operation completed successfully.', severity: 'Info' },
      { hex: '0x00000001', decimal: 1, name: 'ERROR_INVALID_FUNCTION', description: 'Incorrect function called or unknown function number.', severity: 'Error' },
      { hex: '0x00000002', decimal: 2, name: 'ERROR_FILE_NOT_FOUND', description: 'The system cannot find the file specified.', severity: 'Error' },
      { hex: '0x00000003', decimal: 3, name: 'ERROR_PATH_NOT_FOUND', description: 'The system cannot find the path specified.', severity: 'Error' },
      { hex: '0x00000004', decimal: 4, name: 'ERROR_TOO_MANY_OPEN_FILES', description: 'The system cannot open the file. Too many open file handles.', severity: 'Error' },
      { hex: '0x00000005', decimal: 5, name: 'ERROR_ACCESS_DENIED', description: 'Access is denied. Check permissions or run as administrator.', severity: 'Error' },
      { hex: '0x00000006', decimal: 6, name: 'ERROR_INVALID_HANDLE', description: 'The handle is invalid. Often caused by a closed or corrupted handle.', severity: 'Error' },
      { hex: '0x00000008', decimal: 8, name: 'ERROR_NOT_ENOUGH_MEMORY', description: 'Not enough storage is available to process this command.', severity: 'Error' },
      { hex: '0x0000000D', decimal: 13, name: 'ERROR_INVALID_DATA', description: 'The data is invalid.', severity: 'Error' },
      { hex: '0x0000000E', decimal: 14, name: 'ERROR_OUTOFMEMORY', description: 'Not enough storage is available to complete this operation.', severity: 'Error' },
      { hex: '0x0000000F', decimal: 15, name: 'ERROR_INVALID_DRIVE', description: 'The system cannot find the drive specified.', severity: 'Error' },
      { hex: '0x00000012', decimal: 18, name: 'ERROR_NO_MORE_FILES', description: 'There are no more files to enumerate.', severity: 'Info' },
      { hex: '0x0000001F', decimal: 31, name: 'ERROR_GEN_FAILURE', description: 'A device attached to the system is not functioning.', severity: 'Error' },
      { hex: '0x00000020', decimal: 32, name: 'ERROR_SHARING_VIOLATION', description: 'The process cannot access the file because it is being used by another process.', severity: 'Warning' },
      { hex: '0x00000026', decimal: 38, name: 'ERROR_HANDLE_EOF', description: 'Reached end of file.', severity: 'Info' },
      { hex: '0x00000027', decimal: 39, name: 'ERROR_HANDLE_DISK_FULL', description: 'The disk is full.', severity: 'Error' },
      { hex: '0x00000032', decimal: 50, name: 'ERROR_NOT_SUPPORTED', description: 'The request is not supported.', severity: 'Error' },
      { hex: '0x00000035', decimal: 53, name: 'ERROR_BAD_NETPATH', description: 'The network path was not found. Check UNC path and network connectivity.', severity: 'Error' },
      { hex: '0x00000041', decimal: 65, name: 'ERROR_NETWORK_ACCESS_DENIED', description: 'Network access is denied.', severity: 'Error' },
      { hex: '0x00000050', decimal: 80, name: 'ERROR_FILE_EXISTS', description: 'The file already exists.', severity: 'Warning' },
      { hex: '0x00000052', decimal: 82, name: 'ERROR_CANNOT_MAKE', description: 'The directory or file cannot be created.', severity: 'Error' },
      { hex: '0x00000057', decimal: 87, name: 'ERROR_INVALID_PARAMETER', description: 'The parameter is incorrect.', severity: 'Error' },
      { hex: '0x00000070', decimal: 112, name: 'ERROR_DISK_FULL', description: 'There is not enough space on the disk.', severity: 'Error' },
      { hex: '0x0000007B', decimal: 123, name: 'ERROR_INVALID_NAME', description: 'The filename, directory name, or volume label syntax is incorrect.', severity: 'Error' },
      { hex: '0x0000007E', decimal: 126, name: 'ERROR_MOD_NOT_FOUND', description: 'The specified module could not be found. Missing DLL or dependency.', severity: 'Error' },
      { hex: '0x0000007F', decimal: 127, name: 'ERROR_PROC_NOT_FOUND', description: 'The specified procedure could not be found.', severity: 'Error' },
      { hex: '0x000000B7', decimal: 183, name: 'ERROR_ALREADY_EXISTS', description: 'Cannot create a file when that file already exists.', severity: 'Warning' },
      { hex: '0x000000D8', decimal: 216, name: 'ERROR_NOACCESS', description: 'Invalid access to memory location.', severity: 'Error' },
      { hex: '0x000000E7', decimal: 231, name: 'ERROR_PIPE_BUSY', description: 'All pipe instances are busy.', severity: 'Warning' },
      { hex: '0x000000EA', decimal: 234, name: 'ERROR_MORE_DATA', description: 'More data is available than the buffer provided.', severity: 'Info' },
      { hex: '0x000000F0', decimal: 240, name: 'ERROR_SESSION_CREDENTIAL_CONFLICT', description: 'Multiple connections to a server using more than one username are not allowed.', severity: 'Warning' },
      { hex: '0x00000103', decimal: 259, name: 'ERROR_NO_MORE_ITEMS', description: 'No more items are available for enumeration.', severity: 'Info' },
      { hex: '0x000003E3', decimal: 995, name: 'ERROR_OPERATION_ABORTED', description: 'The I/O operation has been aborted because of either a thread exit or an application request.', severity: 'Warning' },
      { hex: '0x000003E5', decimal: 997, name: 'ERROR_IO_PENDING', description: 'Overlapped I/O operation is in progress.', severity: 'Info' },
      { hex: '0x000004C7', decimal: 1223, name: 'ERROR_CANCELLED', description: 'The operation was canceled by the user.', severity: 'Info' },
      { hex: '0x000004D5', decimal: 1237, name: 'ERROR_RETRY', description: 'The operation could not be completed. A retry should be performed.', severity: 'Warning' },
    ],
  },
  {
    category: 'Windows Update & Feature Updates',
    errors: [
      { hex: '0x80070002', decimal: -2147024894, name: 'ERROR_FILE_NOT_FOUND (WU)', description: 'Windows Update cannot find required files. Try running the Windows Update troubleshooter or DISM.', severity: 'Error' },
      { hex: '0x80070005', decimal: -2147024891, name: 'ERROR_ACCESS_DENIED (WU)', description: 'Windows Update access denied. Often caused by corrupted system files or antivirus interference.', severity: 'Error' },
      { hex: '0x8007000E', decimal: -2147024882, name: 'ERROR_OUTOFMEMORY (WU)', description: 'Windows Update ran out of memory. Free up RAM and disk space.', severity: 'Error' },
      { hex: '0x8007001F', decimal: -2147024865, name: 'ERROR_GEN_FAILURE (WU)', description: 'General failure during Windows Update. Run SFC /scannow and DISM /RestoreHealth.', severity: 'Error' },
      { hex: '0x80070020', decimal: -2147024864, name: 'ERROR_SHARING_VIOLATION (WU)', description: 'A file needed by Windows Update is locked by another process.', severity: 'Error' },
      { hex: '0x80070070', decimal: -2147024784, name: 'ERROR_DISK_FULL (WU)', description: 'Not enough disk space to install updates. Free up space on the system drive.', severity: 'Error' },
      { hex: '0x800700B7', decimal: -2147024713, name: 'ERROR_ALREADY_EXISTS (WU)', description: 'Update file already exists. May indicate a partial previous download.', severity: 'Warning' },
      { hex: '0x80070422', decimal: -2147023838, name: 'ERROR_SERVICE_DISABLED', description: 'Windows Update service is disabled. Enable and start the wuauserv service.', severity: 'Error' },
      { hex: '0x80070490', decimal: -2147023728, name: 'ERROR_NOT_FOUND (WU)', description: 'Element not found. Often a corrupt CBS store — run DISM /RestoreHealth.', severity: 'Error' },
      { hex: '0x800705B4', decimal: -2147023436, name: 'ERROR_TIMEOUT (WU)', description: 'Windows Update operation timed out. Check network connectivity and WSUS configuration.', severity: 'Error' },
      { hex: '0x8007054F', decimal: -2147023025, name: 'ERROR_INTERNAL_ERROR (WU)', description: 'An internal error occurred in Windows Update.', severity: 'Error' },
      { hex: '0x80073701', decimal: -2147010559, name: 'ERROR_SXS_ASSEMBLY_MISSING', description: 'A required assembly is missing from the WinSxS store. Run DISM /RestoreHealth.', severity: 'Error' },
      { hex: '0x8024000B', decimal: -2145107957, name: 'WU_E_CALL_CANCELLED', description: 'Operation was cancelled by Windows Update.', severity: 'Warning' },
      { hex: '0x8024000E', decimal: -2145107954, name: 'WU_E_XML_INVALID', description: 'Windows Update found invalid information in the update XML.', severity: 'Error' },
      { hex: '0x80240016', decimal: -2145107946, name: 'WU_E_INSTALL_NOT_ALLOWED', description: 'Operation tried to install while another installation was in progress.', severity: 'Warning' },
      { hex: '0x80240020', decimal: -2145107936, name: 'WU_E_NO_INTERACTIVE_USER', description: 'No interactive user is logged on — update requires a user session.', severity: 'Warning' },
      { hex: '0x80242006', decimal: -2145095674, name: 'WU_E_UH_INVALIDMETADATA', description: 'Update handler could not complete because the update contains invalid metadata.', severity: 'Error' },
      { hex: '0x80244007', decimal: -2145107961, name: 'WU_E_PT_SOAPCLIENT_SOAPFAULT', description: 'SOAP client failed due to a SOAP fault. Check WSUS or Windows Update connectivity.', severity: 'Error' },
      { hex: '0x80244022', decimal: -2145107934, name: 'WU_E_PT_HTTP_STATUS_SERVICE_UNAVAIL', description: 'HTTP 503 from WSUS or Windows Update — server temporarily unavailable.', severity: 'Error' },
      { hex: '0xC1900101', decimal: -1056505599, name: 'MOSETUP_E_DRIVER_FAILURE', description: 'Feature update failed due to a driver issue. Common during Windows 10/11 upgrades. Update or remove problematic drivers.', severity: 'Critical' },
      { hex: '0xC1900200', decimal: -1056505344, name: 'MOSETUP_E_COMPAT_SYSREQ_BLOCK', description: 'System does not meet minimum requirements for the Windows upgrade.', severity: 'Critical' },
      { hex: '0xC1900107', decimal: -1056505593, name: 'MOSETUP_E_CLEANUP_PENDING', description: 'A cleanup operation is still pending from a previous upgrade. Reboot and retry.', severity: 'Warning' },
      { hex: '0xC1900208', decimal: -1056505336, name: 'MOSETUP_E_COMPAT_INSTALLREQ_BLOCK', description: 'An incompatible app is blocking the Windows upgrade. Uninstall flagged apps and retry.', severity: 'Critical' },
    ],
  },
  {
    category: 'BSOD Stop Codes',
    errors: [
      { hex: '0x0000000A', decimal: 10, name: 'IRQL_NOT_LESS_OR_EQUAL', description: 'Kernel accessed memory at improper IRQL. Almost always a faulty driver.', severity: 'Critical' },
      { hex: '0x0000001A', decimal: 26, name: 'MEMORY_MANAGEMENT', description: 'Serious memory management error. Run MemTest86 to check RAM.', severity: 'Critical' },
      { hex: '0x0000001E', decimal: 30, name: 'KMODE_EXCEPTION_NOT_HANDLED', description: 'Kernel mode exception was not handled. Check minidump for offending driver.', severity: 'Critical' },
      { hex: '0x00000023', decimal: 35, name: 'FAT_FILE_SYSTEM', description: 'Problem in the FAT file system. Run CHKDSK.', severity: 'Critical' },
      { hex: '0x00000024', decimal: 36, name: 'NTFS_FILE_SYSTEM', description: 'Problem with the NTFS file system driver. Run CHKDSK on the affected volume.', severity: 'Critical' },
      { hex: '0x0000002E', decimal: 46, name: 'DATA_BUS_ERROR', description: 'Parity error in system memory. Usually indicates faulty RAM or motherboard.', severity: 'Critical' },
      { hex: '0x0000003B', decimal: 59, name: 'SYSTEM_SERVICE_EXCEPTION', description: 'A system service threw an exception. Often caused by a faulty driver. Check minidump for offending module.', severity: 'Critical' },
      { hex: '0x00000044', decimal: 68, name: 'MULTIPLE_IRP_COMPLETE_REQUESTS', description: 'A driver attempted to complete an IRP more than once.', severity: 'Critical' },
      { hex: '0x00000050', decimal: 80, name: 'PAGE_FAULT_IN_NONPAGED_AREA', description: 'Invalid memory referenced. Caused by faulty RAM, drivers, or system files.', severity: 'Critical' },
      { hex: '0x00000051', decimal: 81, name: 'REGISTRY_ERROR', description: 'Error related to the registry. May indicate disk failure or corrupted hive.', severity: 'Critical' },
      { hex: '0x0000005A', decimal: 90, name: 'CRITICAL_SERVICE_FAILED', description: 'A critical service failed to start during boot.', severity: 'Critical' },
      { hex: '0x00000069', decimal: 105, name: 'IO1_INITIALIZATION_FAILED', description: 'I/O initialization failed during boot.', severity: 'Critical' },
      { hex: '0x00000074', decimal: 116, name: 'BAD_SYSTEM_CONFIG_INFO', description: 'Registry or BCD store is corrupt. Run Startup Repair or restore from backup.', severity: 'Critical' },
      { hex: '0x0000007A', decimal: 122, name: 'KERNEL_DATA_INPAGE_ERROR', description: 'Required page of kernel data could not be read into memory. Often a failing disk or bad RAM.', severity: 'Critical' },
      { hex: '0x0000007E', decimal: 126, name: 'SYSTEM_THREAD_EXCEPTION_NOT_HANDLED', description: 'A system thread generated an exception the error handler did not catch. Usually a driver issue.', severity: 'Critical' },
      { hex: '0x0000007F', decimal: 127, name: 'UNEXPECTED_KERNEL_MODE_TRAP', description: 'The CPU generated a trap the kernel did not catch. Often hardware failure or overclocking issue.', severity: 'Critical' },
      { hex: '0x00000080', decimal: 128, name: 'NMI_HARDWARE_FAILURE', description: 'Non-maskable interrupt from hardware. Indicates serious hardware failure.', severity: 'Critical' },
      { hex: '0x0000009F', decimal: 159, name: 'DRIVER_POWER_STATE_FAILURE', description: 'A driver is inconsistent with power state transitions. Common on laptops during sleep/wake.', severity: 'Critical' },
      { hex: '0x000000BE', decimal: 190, name: 'ATTEMPTED_WRITE_TO_READONLY_MEMORY', description: 'A driver attempted to write to read-only memory. Driver bug.', severity: 'Critical' },
      { hex: '0x000000C2', decimal: 194, name: 'BAD_POOL_CALLER', description: 'A process made an illegal memory pool request. Usually a faulty driver.', severity: 'Critical' },
      { hex: '0x000000C4', decimal: 196, name: 'DRIVER_VERIFIER_DETECTED_VIOLATION', description: 'Driver Verifier caught a driver violation. Check Driver Verifier settings.', severity: 'Critical' },
      { hex: '0x000000C5', decimal: 197, name: 'DRIVER_CORRUPTED_EXPOOL', description: 'A driver corrupted pool memory. Run Driver Verifier to identify the culprit.', severity: 'Critical' },
      { hex: '0x000000D1', decimal: 209, name: 'DRIVER_IRQL_NOT_LESS_OR_EQUAL', description: 'A driver attempted to access pageable memory at an improper IRQL. Common driver bug.', severity: 'Critical' },
      { hex: '0x000000EA', decimal: 234, name: 'THREAD_STUCK_IN_DEVICE_DRIVER', description: 'A thread in a device driver was stuck in an infinite loop. Often GPU driver related.', severity: 'Critical' },
      { hex: '0x000000EF', decimal: 239, name: 'CRITICAL_PROCESS_DIED', description: 'A critical system process died. Usually wininit.exe, csrss.exe, or winlogon.exe.', severity: 'Critical' },
      { hex: '0x000000F4', decimal: 244, name: 'CRITICAL_OBJECT_TERMINATION', description: 'A critical process or thread terminated unexpectedly. Often a failing disk or corrupt system files.', severity: 'Critical' },
      { hex: '0x000000FE', decimal: 254, name: 'BUGCODE_USB_DRIVER', description: 'USB driver error. Try unplugging USB devices or updating USB drivers.', severity: 'Critical' },
      { hex: '0x00000116', decimal: 278, name: 'VIDEO_TDR_FAILURE', description: 'Video TDR failure — GPU driver stopped responding and failed to recover. Update GPU drivers.', severity: 'Critical' },
      { hex: '0x0000013A', decimal: 314, name: 'KERNEL_MODE_HEAP_CORRUPTION', description: 'Kernel mode heap corruption detected. Usually a driver bug.', severity: 'Critical' },
      { hex: '0x00000154', decimal: 340, name: 'UNEXPECTED_STORE_EXCEPTION', description: 'An unexpected exception occurred in the store stack. Can be caused by failing storage.', severity: 'Critical' },
      { hex: '0x00000164', decimal: 356, name: 'WIN32K_CRITICAL_FAILURE', description: 'win32k.sys critical failure. Can be caused by display driver or kernel patch issues.', severity: 'Critical' },
      { hex: '0xDEADDEAD', decimal: -559038771, name: 'MANUALLY_INITIATED_CRASH', description: 'Crash was manually triggered via keyboard shortcut or NotMyFault tool.', severity: 'Info' },
    ],
  },
  {
    category: 'NT Status Codes (0xC0000xxx)',
    errors: [
      { hex: '0xC0000001', decimal: -1073741823, name: 'STATUS_UNSUCCESSFUL', description: 'General unsuccessful status. Operation failed for an unspecified reason.', severity: 'Error' },
      { hex: '0xC0000005', decimal: -1073741819, name: 'STATUS_ACCESS_VIOLATION', description: 'Memory access violation. A process attempted to access memory it has no rights to. Often causes application crashes.', severity: 'Critical' },
      { hex: '0xC0000008', decimal: -1073741816, name: 'STATUS_INVALID_HANDLE', description: 'An invalid handle was specified.', severity: 'Error' },
      { hex: '0xC000000D', decimal: -1073741811, name: 'STATUS_INVALID_PARAMETER', description: 'An invalid parameter was passed to a service or function.', severity: 'Error' },
      { hex: '0xC000000F', decimal: -1073741809, name: 'STATUS_NO_SUCH_FILE', description: 'The file does not exist.', severity: 'Error' },
      { hex: '0xC0000016', decimal: -1073741802, name: 'STATUS_MORE_PROCESSING_REQUIRED', description: 'More processing is required. Common in Kerberos/NTLM multi-step authentication.', severity: 'Info' },
      { hex: '0xC0000017', decimal: -1073741801, name: 'STATUS_NO_MEMORY', description: 'Not enough virtual memory or paging file quota to complete the operation.', severity: 'Error' },
      { hex: '0xC0000022', decimal: -1073741790, name: 'STATUS_ACCESS_DENIED', description: 'A process has requested access to an object but has not been granted those access rights.', severity: 'Error' },
      { hex: '0xC0000034', decimal: -1073741772, name: 'STATUS_OBJECT_NAME_NOT_FOUND', description: 'Object name not found. Registry key, file, or device does not exist.', severity: 'Error' },
      { hex: '0xC0000043', decimal: -1073741757, name: 'STATUS_SHARING_VIOLATION', description: 'A file cannot be opened because it has been opened in an incompatible sharing mode.', severity: 'Warning' },
      { hex: '0xC000006A', decimal: -1073741718, name: 'STATUS_WRONG_PASSWORD', description: 'The specified password is incorrect.', severity: 'Warning' },
      { hex: '0xC000006C', decimal: -1073741716, name: 'STATUS_PASSWORD_RESTRICTION', description: 'Password does not meet domain password policy requirements.', severity: 'Warning' },
      { hex: '0xC000006D', decimal: -1073741715, name: 'STATUS_LOGON_FAILURE', description: 'Logon failure: unknown username or bad password.', severity: 'Error' },
      { hex: '0xC000006E', decimal: -1073741714, name: 'STATUS_ACCOUNT_RESTRICTION', description: 'Logon failure: account restriction prevents this user from logging on.', severity: 'Error' },
      { hex: '0xC000006F', decimal: -1073741713, name: 'STATUS_INVALID_LOGON_HOURS', description: 'Logon failure: account is not authorized to log on at this time.', severity: 'Warning' },
      { hex: '0xC0000070', decimal: -1073741712, name: 'STATUS_INVALID_WORKSTATION', description: 'Logon failure: user is not allowed to log on from this workstation.', severity: 'Warning' },
      { hex: '0xC0000071', decimal: -1073741711, name: 'STATUS_PASSWORD_EXPIRED', description: 'Logon failure: the password for this account has expired.', severity: 'Warning' },
      { hex: '0xC0000072', decimal: -1073741710, name: 'STATUS_ACCOUNT_DISABLED', description: 'Logon failure: account is currently disabled.', severity: 'Warning' },
      { hex: '0xC000007C', decimal: -1073741700, name: 'STATUS_NO_LOGON_SERVERS', description: 'There are no logon servers available to service the logon request. Domain controller unreachable.', severity: 'Error' },
      { hex: '0xC0000089', decimal: -1073741687, name: 'STATUS_INVALID_IMAGE_FORMAT', description: 'The specified image file did not have the correct format.', severity: 'Error' },
      { hex: '0xC000009A', decimal: -1073741670, name: 'STATUS_INSUFFICIENT_RESOURCES', description: 'Insufficient system resources to complete the API.', severity: 'Error' },
      { hex: '0xC00000BB', decimal: -1073741637, name: 'STATUS_NOT_SUPPORTED', description: 'The requested operation is not supported.', severity: 'Error' },
      { hex: '0xC0000101', decimal: -1073741567, name: 'STATUS_DIRECTORY_NOT_EMPTY', description: 'The directory is not empty.', severity: 'Warning' },
      { hex: '0xC0000120', decimal: -1073741536, name: 'STATUS_CANCELLED', description: 'The operation was cancelled.', severity: 'Info' },
      { hex: '0xC0000135', decimal: -1073741515, name: 'STATUS_DLL_NOT_FOUND', description: 'A required DLL was not found.', severity: 'Error' },
      { hex: '0xC0000139', decimal: -1073741511, name: 'STATUS_ENTRYPOINT_NOT_FOUND', description: 'The procedure entry point could not be located in the DLL.', severity: 'Error' },
      { hex: '0xC0000142', decimal: -1073741502, name: 'STATUS_DLL_INIT_FAILED', description: 'DLL initialization routine failed. Indicates a dependency or system file issue.', severity: 'Error' },
      { hex: '0xC0000185', decimal: -1073741435, name: 'STATUS_IO_DEVICE_ERROR', description: 'The request could not be performed because of an I/O device error. Often a failing disk.', severity: 'Critical' },
      { hex: '0xC000018A', decimal: -1073741430, name: 'STATUS_NO_TRUST_LSA_SECRET', description: 'The SAM database on the server does not have a computer account for this workstation trust relationship.', severity: 'Error' },
      { hex: '0xC000018D', decimal: -1073741427, name: 'STATUS_TRUSTED_RELATIONSHIP_FAILURE', description: 'The trust relationship between this workstation and the primary domain failed. Rejoin the domain.', severity: 'Error' },
      { hex: '0xC0000192', decimal: -1073741422, name: 'STATUS_NETLOGON_NOT_STARTED', description: 'An attempt was made to logon but the Netlogon service was not started.', severity: 'Error' },
      { hex: '0xC0000193', decimal: -1073741421, name: 'STATUS_ACCOUNT_EXPIRED', description: 'The user account has expired.', severity: 'Warning' },
      { hex: '0xC0000224', decimal: -1073741276, name: 'STATUS_PASSWORD_MUST_CHANGE', description: 'User must change password before logging on the first time.', severity: 'Warning' },
      { hex: '0xC0000234', decimal: -1073741260, name: 'STATUS_ACCOUNT_LOCKED_OUT', description: 'Account locked out due to too many invalid logon attempts.', severity: 'Warning' },
      { hex: '0xC0000257', decimal: -1073741225, name: 'STATUS_DOWNGRADE_DETECTED', description: 'A downgrade attack has been detected. Kerberos security failure.', severity: 'Critical' },
    ],
  },
  {
    category: 'Active Directory & Kerberos',
    errors: [
      { hex: '0x80090304', decimal: -2146893052, name: 'SEC_E_INTERNAL_ERROR', description: 'The Local Security Authority cannot be contacted.', severity: 'Error' },
      { hex: '0x8009030C', decimal: -2146893044, name: 'SEC_E_LOGON_DENIED', description: 'The logon attempt failed. Kerberos logon denied.', severity: 'Error' },
      { hex: '0x8009030E', decimal: -2146893042, name: 'SEC_E_NO_CREDENTIALS', description: 'No credentials are available in the security package.', severity: 'Error' },
      { hex: '0x8009030F', decimal: -2146893041, name: 'SEC_E_MESSAGE_ALTERED', description: 'The message or signature supplied for verification has been altered.', severity: 'Critical' },
      { hex: '0x80090311', decimal: -2146893039, name: 'SEC_E_NO_AUTHENTICATING_AUTHORITY', description: 'No authority could be contacted for authentication. DC unreachable or Kerberos misconfigured.', severity: 'Error' },
      { hex: '0x80090316', decimal: -2146893034, name: 'SEC_E_INVALID_TOKEN', description: 'The token supplied to the function is invalid. Kerberos ticket may have expired or been tampered with.', severity: 'Error' },
      { hex: '0x80090317', decimal: -2146893033, name: 'SEC_E_TOKEN_TOO_LARGE', description: 'The security token exceeds the maximum allowed size. Too many group memberships — Kerberos token bloat.', severity: 'Warning' },
      { hex: '0x8009031A', decimal: -2146893030, name: 'SEC_E_MUTUAL_AUTH_FAILED', description: 'Mutual authentication failed. The server password is out of date at the domain controller.', severity: 'Error' },
      { hex: '0x80090321', decimal: -2146893023, name: 'SEC_E_WRONG_PRINCIPAL', description: 'The target principal name is incorrect. SPN mismatch — check AD SPN registration.', severity: 'Error' },
      { hex: '0x80090322', decimal: -2146893022, name: 'SEC_E_TIME_SKEW', description: 'Clock skew too great between client and server. Kerberos requires time within 5 minutes — sync clocks.', severity: 'Error' },
      { hex: '0x80090323', decimal: -2146893021, name: 'SEC_E_CERT_EXPIRED', description: 'The received certificate has expired.', severity: 'Error' },
      { hex: '0x80090325', decimal: -2146893019, name: 'SEC_E_UNTRUSTED_ROOT', description: 'The certificate chain was issued by an authority that is not trusted.', severity: 'Error' },
      { hex: '0x80090327', decimal: -2146893017, name: 'SEC_E_DOWNGRADE_DETECTED', description: 'The system detected a possible attempt to compromise security. Kerberos downgrade attack detected.', severity: 'Critical' },
      { hex: '0x8007052E', decimal: -2147023314, name: 'ERROR_LOGON_FAILURE', description: 'Logon failure: unknown user name or bad password. Most common AD authentication error.', severity: 'Error' },
      { hex: '0x80070534', decimal: -2147023308, name: 'ERROR_NONE_MAPPED', description: 'No mapping between account names and security IDs was done. User/group not found in AD.', severity: 'Error' },
      { hex: '0x8007054B', decimal: -2147023285, name: 'ERROR_DOMAIN_CONTROLLER_NOT_FOUND', description: 'Could not find the domain controller for this domain. DNS or network issue.', severity: 'Error' },
      { hex: '0x8007054F', decimal: -2147023281, name: 'ERROR_DS_UNAVAILABLE', description: 'The directory service is unavailable. Domain controller is offline or unreachable.', severity: 'Error' },
      { hex: '0x80070569', decimal: -2147023255, name: 'ERROR_LOGON_TYPE_NOT_GRANTED', description: 'A user has been denied the requested logon type at this machine. Check local/GPO logon rights.', severity: 'Warning' },
      { hex: '0x80070774', decimal: -2147023244, name: 'ERROR_ACCOUNT_LOCKED_OUT', description: 'The referenced account is currently locked out and cannot be logged on to.', severity: 'Warning' },
    ],
  },
  {
    category: 'RPC & Network',
    errors: [
      { hex: '0x800706BA', decimal: -2147023174, name: 'RPC_S_SERVER_UNAVAILABLE', description: 'The RPC server is unavailable. Check that the target machine is online and firewall allows RPC.', severity: 'Error' },
      { hex: '0x800706BB', decimal: -2147023173, name: 'RPC_S_SERVER_TOO_BUSY', description: 'The RPC server is too busy to complete this operation.', severity: 'Warning' },
      { hex: '0x800706BE', decimal: -2147023170, name: 'RPC_S_CALL_FAILED', description: 'The remote procedure call failed. Network issue or service crash on remote end.', severity: 'Error' },
      { hex: '0x800706BF', decimal: -2147023169, name: 'RPC_S_CALL_FAILED_DNE', description: 'The remote procedure call failed and did not execute.', severity: 'Error' },
      { hex: '0x800706D9', decimal: -2147023143, name: 'EPT_S_NOT_REGISTERED', description: 'No endpoint registered. The service on the remote machine is not running.', severity: 'Error' },
      { hex: '0x80070043', decimal: -2147024829, name: 'ERROR_BAD_NET_NAME', description: 'The network name cannot be found. Check the UNC path or DNS resolution.', severity: 'Error' },
      { hex: '0x80070035', decimal: -2147024843, name: 'ERROR_BAD_NETPATH', description: 'The network path was not found. Check firewall, SMB settings, and network connectivity.', severity: 'Error' },
      { hex: '0x80072EE2', decimal: -2147012894, name: 'WININET_E_TIMEOUT', description: 'The operation timed out. Check network connectivity and proxy settings.', severity: 'Error' },
      { hex: '0x80072EE7', decimal: -2147012889, name: 'WININET_E_NAME_NOT_RESOLVED', description: 'The server name or address could not be resolved. DNS issue.', severity: 'Error' },
      { hex: '0x80072EFD', decimal: -2147012867, name: 'WININET_E_CANNOT_CONNECT', description: 'A connection with the server could not be established.', severity: 'Error' },
      { hex: '0x80072EFE', decimal: -2147012866, name: 'WININET_E_CONNECTION_ABORTED', description: 'The connection with the server was terminated abnormally.', severity: 'Error' },
      { hex: '0x80072EFF', decimal: -2147012865, name: 'WININET_E_CONNECTION_RESET', description: 'The connection with the server was reset.', severity: 'Error' },
      { hex: '0x80072F0C', decimal: -2147012852, name: 'WININET_E_INVALID_CA', description: 'The certificate authority is invalid or incorrect. SSL/TLS certificate issue.', severity: 'Error' },
    ],
  },
  {
    category: 'WMI Errors',
    errors: [
      { hex: '0x80041001', decimal: -2147217407, name: 'WBEM_E_FAILED', description: 'General WMI failure. Check WMI service and run winmgmt /verifyrepository.', severity: 'Error' },
      { hex: '0x80041002', decimal: -2147217406, name: 'WBEM_E_NOT_FOUND', description: 'WMI object or property not found.', severity: 'Error' },
      { hex: '0x80041003', decimal: -2147217405, name: 'WBEM_E_ACCESS_DENIED', description: 'WMI access denied. Check DCOM and WMI namespace permissions.', severity: 'Error' },
      { hex: '0x80041006', decimal: -2147217402, name: 'WBEM_E_OUT_OF_MEMORY', description: 'WMI ran out of memory to complete the operation.', severity: 'Error' },
      { hex: '0x80041010', decimal: -2147217392, name: 'WBEM_E_INVALID_CLASS', description: 'Specified WMI class does not exist in the namespace.', severity: 'Error' },
      { hex: '0x8004100E', decimal: -2147217394, name: 'WBEM_E_INVALID_NAMESPACE', description: 'Specified WMI namespace does not exist.', severity: 'Error' },
      { hex: '0x80041032', decimal: -2147217358, name: 'WBEM_E_CALL_CANCELLED', description: 'WMI call was cancelled.', severity: 'Warning' },
      { hex: '0x8004106C', decimal: -2147217300, name: 'WBEM_E_QUOTA_VIOLATION', description: 'WMI quota was violated. Too many concurrent WMI operations.', severity: 'Error' },
      { hex: '0x80041064', decimal: -2147217308, name: 'WBEM_E_DATABASE_VER_MISMATCH', description: 'WMI repository version mismatch. Rebuild with winmgmt /resetrepository.', severity: 'Error' },
      { hex: '0x8004107A', decimal: -2147217286, name: 'WBEM_E_TIMED_OUT', description: 'WMI operation timed out. The query or operation took too long to execute.', severity: 'Error' },
    ],
  },
  {
    category: 'MSI Installer Errors',
    errors: [
      { hex: '0x00000641', decimal: 1601, name: 'ERROR_INSTALL_SERVICE_FAILURE', description: 'Windows Installer service could not be accessed. Start the msiserver service.', severity: 'Error' },
      { hex: '0x00000642', decimal: 1602, name: 'ERROR_INSTALL_USEREXIT', description: 'User cancelled the installation.', severity: 'Info' },
      { hex: '0x00000643', decimal: 1603, name: 'ERROR_INSTALL_FAILURE', description: 'Fatal error during installation. Check MSI log for root cause. Often a permissions or dependency issue.', severity: 'Error' },
      { hex: '0x00000644', decimal: 1604, name: 'ERROR_INSTALL_SUSPEND', description: 'Installation suspended — incomplete.', severity: 'Warning' },
      { hex: '0x00000645', decimal: 1605, name: 'ERROR_UNKNOWN_PRODUCT', description: 'This action is only valid for products that are currently installed.', severity: 'Error' },
      { hex: '0x00000652', decimal: 1618, name: 'ERROR_INSTALL_ALREADY_RUNNING', description: 'Another installation is already in progress. Complete that first, or kill msiexec.exe.', severity: 'Warning' },
      { hex: '0x00000653', decimal: 1619, name: 'ERROR_INSTALL_PACKAGE_OPEN_FAILED', description: 'This installation package could not be opened. Check path and permissions.', severity: 'Error' },
      { hex: '0x00000654', decimal: 1620, name: 'ERROR_INSTALL_PACKAGE_INVALID', description: 'This installation package could not be opened. It may be corrupt.', severity: 'Error' },
      { hex: '0x00000659', decimal: 1625, name: 'ERROR_INSTALL_PACKAGE_REJECTED', description: 'Installation rejected by system policy. Check Software Restriction Policies or AppLocker.', severity: 'Error' },
      { hex: '0x00000667', decimal: 1639, name: 'ERROR_INVALID_COMMAND_LINE', description: 'Invalid command line argument for msiexec.', severity: 'Error' },
      { hex: '0x00000BC2', decimal: 3010, name: 'ERROR_SUCCESS_REBOOT_REQUIRED', description: 'Installation succeeded but a reboot is required to complete.', severity: 'Warning' },
    ],
  },
  {
    category: 'Office & M365 Activation',
    errors: [
      { hex: '0xC004C003', decimal: -1073418237, name: 'SL_E_ACTIVATION_FAILED', description: 'Office activation failed. The activation server determined the specified product key is blocked.', severity: 'Error' },
      { hex: '0xC004C060', decimal: -1073418144, name: 'SL_E_GRACE_TIME_EXPIRED', description: 'Office grace period has expired. Activation required immediately.', severity: 'Error' },
      { hex: '0xC004F017', decimal: -1073415145, name: 'SL_E_PRODUCT_SKU_NOT_INSTALLED', description: 'The software license product SKU is not installed.', severity: 'Error' },
      { hex: '0xC004F025', decimal: -1073415131, name: 'SL_E_NOT_GENUINE', description: 'The software is not genuine. License validation failed.', severity: 'Critical' },
      { hex: '0xC004F074', decimal: -1073415052, name: 'SL_E_ACTIVATION_FAILED_KMS', description: 'KMS activation failed. No KMS host could be found. Check DNS SRV records or KMS host availability.', severity: 'Error' },
      { hex: '0xC004F079', decimal: -1073415047, name: 'SL_E_ACTIVATION_THRESHOLD_NOT_MET', description: 'KMS activation count threshold not met. KMS requires minimum 5 clients (25 for Office).', severity: 'Warning' },
      { hex: '0xC004B100', decimal: -1073422592, name: 'SL_E_CHPA_PRODUCT_KEY_BLOCKED', description: 'The product key is blocked. It may have been reported as stolen or misused.', severity: 'Error' },
      { hex: '0x8004FE21', decimal: -2147163615, name: 'OFFICE_SUBSCRIPTION_ERROR', description: 'Microsoft 365 subscription issue. Sign out and back in to Office, or check license assignment.', severity: 'Error' },
      { hex: '0x8004FE33', decimal: -2147163597, name: 'OFFICE_SUBSCRIPTION_NOT_FOUND', description: 'No valid Microsoft 365 subscription found for this account. Check license in M365 admin center.', severity: 'Error' },
    ],
  },
  {
    category: 'BitLocker Errors',
    errors: [
      { hex: '0x80310000', decimal: -2144272384, name: 'FVE_E_LOCKED_VOLUME', description: 'This drive is locked by BitLocker Drive Encryption. Unlock the drive before proceeding.', severity: 'Error' },
      { hex: '0x80310001', decimal: -2144272383, name: 'FVE_E_NOT_ENCRYPTED', description: 'This drive is not encrypted.', severity: 'Info' },
      { hex: '0x80310002', decimal: -2144272382, name: 'FVE_E_NO_TPM_BIOS', description: 'The BIOS did not correctly communicate with the Trusted Platform Module (TPM).', severity: 'Error' },
      { hex: '0x80310009', decimal: -2144272375, name: 'FVE_E_INVALID_PASSWORD_FORMAT', description: 'The BitLocker password does not meet complexity requirements.', severity: 'Warning' },
      { hex: '0x8031000A', decimal: -2144272374, name: 'FVE_E_IN_REBOOT_PENDING', description: 'The drive encryption operation cannot be completed because a restart is required.', severity: 'Warning' },
      { hex: '0x80310018', decimal: -2144272360, name: 'FVE_E_FAILED_AUTHENTICATION', description: 'BitLocker Drive Encryption authentication failed. The recovery key may be required.', severity: 'Error' },
      { hex: '0x80310026', decimal: -2144272346, name: 'FVE_E_CONV_READ_ERROR', description: 'BitLocker encountered an error reading the drive during conversion. The drive may be failing.', severity: 'Critical' },
      { hex: '0x80310033', decimal: -2144272333, name: 'FVE_E_TPM_INVALID_PCR', description: 'BitLocker detected an invalid PCR value from the TPM. Secure Boot or BIOS settings may have changed.', severity: 'Error' },
      { hex: '0x80310038', decimal: -2144272328, name: 'FVE_E_NO_RECOVERY_KEY_FOUND', description: 'No BitLocker recovery key found. Check Active Directory or Azure AD for escrowed key.', severity: 'Critical' },
    ],
  },
  {
    category: 'DNS Errors',
    errors: [
      { hex: '0x0000251D', decimal: 9501, name: 'DNS_ERROR_RCODE_FORMAT_ERROR', description: 'DNS server unable to interpret format.', severity: 'Error' },
      { hex: '0x0000251E', decimal: 9502, name: 'DNS_ERROR_RCODE_SERVER_FAILURE', description: 'DNS server failure.', severity: 'Error' },
      { hex: '0x0000251F', decimal: 9503, name: 'DNS_ERROR_RCODE_NAME_ERROR', description: 'DNS name does not exist.', severity: 'Warning' },
      { hex: '0x00002521', decimal: 9505, name: 'DNS_ERROR_RCODE_REFUSED', description: 'DNS operation refused.', severity: 'Error' },
      { hex: '0x000025B3', decimal: 9651, name: 'DNS_ERROR_ZONE_DOES_NOT_EXIST', description: 'DNS zone does not exist.', severity: 'Error' },
      { hex: '0x80072AF9', decimal: -2147014407, name: 'WSAHOST_NOT_FOUND', description: 'No such host is known. The hostname cannot be resolved via DNS.', severity: 'Error' },
      { hex: '0x80072AFC', decimal: -2147014404, name: 'WSANO_DATA', description: 'The requested name is valid, but no data of the requested type was found.', severity: 'Warning' },
    ],
  },
  {
    category: 'VPN & Remote Access',
    errors: [
      { hex: '0x800B0109', decimal: -2146762487, name: 'CERT_E_UNTRUSTEDROOT', description: 'Certificate chain processed but terminated in a root certificate which is not trusted. VPN certificate issue.', severity: 'Error' },
      { hex: '0x800B010F', decimal: -2146762481, name: 'CERT_E_CN_NO_MATCH', description: 'The certificate CN does not match. VPN server name does not match the certificate subject.', severity: 'Error' },
      { hex: '0x80092013', decimal: -2146885613, name: 'CRYPT_E_REVOKED', description: 'The certificate is revoked. Check CRL or OCSP connectivity.', severity: 'Critical' },
      { hex: '0x80072746', decimal: -2147014842, name: 'WSAECONNRESET', description: 'An existing connection was forcibly closed by the remote host. VPN server dropped the connection.', severity: 'Error' },
      { hex: '0x80072745', decimal: -2147014843, name: 'WSAECONNABORTED', description: 'An established connection was aborted by the software in your host machine.', severity: 'Error' },
    ],
  },
  {
    category: 'Hyper-V Errors',
    errors: [
      { hex: '0x80370000', decimal: -2144927744, name: 'VM_E_CANNOT_FIND_VM', description: 'The virtual machine cannot be found. It may have been deleted or renamed.', severity: 'Error' },
      { hex: '0x80370002', decimal: -2144927742, name: 'VM_E_DRIVER_NOT_PRESENT', description: 'The Hyper-V driver is not present. Ensure the Hyper-V role is installed.', severity: 'Error' },
      { hex: '0x80370003', decimal: -2144927741, name: 'VM_E_HYPERVISOR_NOT_PRESENT', description: 'The hypervisor is not running. Check that virtualization is enabled in BIOS/UEFI.', severity: 'Error' },
      { hex: '0x80370005', decimal: -2144927739, name: 'VM_E_INVALID_PROCESSOR_COUNT', description: 'The specified processor count is not valid for this virtual machine configuration.', severity: 'Error' },
      { hex: '0x8037000A', decimal: -2144927734, name: 'VM_E_INVALID_FILE_FORMAT', description: 'The virtual hard disk file format is invalid or not supported.', severity: 'Error' },
      { hex: '0x80370010', decimal: -2144927728, name: 'VM_E_CANNOT_ACCESS_FILE', description: 'Cannot access the virtual machine file. Check permissions and that the path exists.', severity: 'Error' },
      { hex: '0x8037001E', decimal: -2144927714, name: 'VM_E_INSUFFICIENT_MEMORY', description: 'There is not enough memory in the system to start the virtual machine.', severity: 'Error' },
      { hex: '0x80370028', decimal: -2144927704, name: 'VM_E_WRONG_VM_STATE', description: 'The operation is not valid for the current virtual machine state.', severity: 'Warning' },
      { hex: '0x80370031', decimal: -2144927695, name: 'VM_E_INVALID_CHECKPOINT', description: 'The specified checkpoint does not exist or is invalid.', severity: 'Error' },
    ],
  },
  {
    category: 'COM & DCOM Errors',
    errors: [
      { hex: '0x80004001', decimal: -2147467263, name: 'E_NOTIMPL', description: 'Not implemented. The requested COM interface or method is not available.', severity: 'Error' },
      { hex: '0x80004002', decimal: -2147467262, name: 'E_NOINTERFACE', description: 'No such interface supported by the COM object.', severity: 'Error' },
      { hex: '0x80004004', decimal: -2147467260, name: 'E_ABORT', description: 'Operation aborted.', severity: 'Warning' },
      { hex: '0x80004005', decimal: -2147467259, name: 'E_FAIL', description: 'Unspecified COM failure. Check DCOM settings and event logs for details.', severity: 'Error' },
      { hex: '0x80070005', decimal: -2147024891, name: 'E_ACCESSDENIED (DCOM)', description: 'COM access denied. Check DCOM Launch and Activation permissions in Component Services.', severity: 'Error' },
      { hex: '0x8000FFFF', decimal: -2147418113, name: 'E_UNEXPECTED', description: 'Unexpected COM failure — catastrophic error.', severity: 'Critical' },
      { hex: '0x80010001', decimal: -2147418111, name: 'RPC_E_CALL_REJECTED', description: 'Call was rejected by callee. COM server is busy or not responding.', severity: 'Error' },
      { hex: '0x80010108', decimal: -2147417848, name: 'RPC_E_DISCONNECTED', description: 'The object invoked has disconnected from its clients. COM server crash.', severity: 'Error' },
      { hex: '0x800401F3', decimal: -2147221005, name: 'CO_E_CLASSSTRING', description: 'Invalid class string. The CLSID or ProgID is not registered.', severity: 'Error' },
      { hex: '0x80040154', decimal: -2147221164, name: 'REGDB_E_CLASSNOTREG', description: 'Class not registered. The COM class is not registered on this machine.', severity: 'Error' },
    ],
  },
];
