export const eventsByCategory: {
  category: string
  log: string
  events: {
    id: number
    name: string
    description: string
    severity: 'Info' | 'Warning' | 'Error' | 'Critical'
  }[]
}[] = [
  {
    category: 'Logon & Authentication',
    log: 'Security',
    events: [
      { id: 4624, name: 'Successful Logon', description: 'An account was successfully logged on. Check logon type for interactive vs network vs service.', severity: 'Info' },
      { id: 4625, name: 'Failed Logon', description: 'An account failed to log on. Check failure reason for lockout or bad password.', severity: 'Warning' },
      { id: 4634, name: 'Logoff', description: 'An account was logged off.', severity: 'Info' },
      { id: 4647, name: 'User Initiated Logoff', description: 'User initiated logoff for the listed account.', severity: 'Info' },
      { id: 4648, name: 'Explicit Credential Logon', description: 'A logon was attempted using explicit credentials (e.g. runas). Common in pass-the-hash attacks.', severity: 'Warning' },
      { id: 4672, name: 'Special Privileges Assigned', description: 'Special privileges (admin-equivalent) assigned to new logon session.', severity: 'Info' },
      { id: 4740, name: 'Account Locked Out', description: 'A user account was locked out. Check caller computer name to find the source.', severity: 'Warning' },
      { id: 4767, name: 'Account Unlocked', description: 'A user account was unlocked.', severity: 'Info' },
      { id: 4771, name: 'Kerberos Pre-Auth Failed', description: 'Kerberos pre-authentication failed. Often indicates bad password or clock skew over 5 minutes.', severity: 'Warning' },
      { id: 4776, name: 'NTLM Auth Attempt', description: 'The domain controller attempted to validate credentials via NTLM.', severity: 'Info' },
      { id: 4778, name: 'RDP Session Reconnected', description: 'A session was reconnected to a Window Station. Common with RDP reconnects.', severity: 'Info' },
      { id: 4779, name: 'RDP Session Disconnected', description: 'A session was disconnected from a Window Station.', severity: 'Info' },
      { id: 4800, name: 'Workstation Locked', description: 'The workstation was locked.', severity: 'Info' },
      { id: 4801, name: 'Workstation Unlocked', description: 'The workstation was unlocked.', severity: 'Info' },
      { id: 4802, name: 'Screensaver Invoked', description: 'The screen saver was invoked.', severity: 'Info' },
      { id: 4803, name: 'Screensaver Dismissed', description: 'The screen saver was dismissed.', severity: 'Info' },
    ],
  },
  {
    category: 'Account Management',
    log: 'Security',
    events: [
      { id: 4720, name: 'User Account Created', description: 'A user account was created.', severity: 'Info' },
      { id: 4722, name: 'User Account Enabled', description: 'A user account was enabled.', severity: 'Info' },
      { id: 4723, name: 'Password Change Attempt', description: 'An attempt was made to change an account\'s password.', severity: 'Info' },
      { id: 4724, name: 'Password Reset Attempt', description: 'An attempt was made to reset an account\'s password by an admin.', severity: 'Warning' },
      { id: 4725, name: 'User Account Disabled', description: 'A user account was disabled.', severity: 'Warning' },
      { id: 4726, name: 'User Account Deleted', description: 'A user account was deleted.', severity: 'Warning' },
      { id: 4727, name: 'Global Group Created', description: 'A security-enabled global group was created.', severity: 'Info' },
      { id: 4728, name: 'Member Added to Global Group', description: 'A member was added to a security-enabled global group.', severity: 'Info' },
      { id: 4729, name: 'Member Removed from Global Group', description: 'A member was removed from a security-enabled global group.', severity: 'Warning' },
      { id: 4730, name: 'Global Group Deleted', description: 'A security-enabled global group was deleted.', severity: 'Warning' },
      { id: 4731, name: 'Local Group Created', description: 'A security-enabled local group was created.', severity: 'Info' },
      { id: 4732, name: 'Member Added to Local Group', description: 'A member was added to a security-enabled local group.', severity: 'Info' },
      { id: 4733, name: 'Member Removed from Local Group', description: 'A member was removed from a security-enabled local group.', severity: 'Warning' },
      { id: 4734, name: 'Local Group Deleted', description: 'A security-enabled local group was deleted.', severity: 'Warning' },
      { id: 4738, name: 'User Account Changed', description: 'A user account was changed. Includes password, flag, and attribute changes.', severity: 'Info' },
      { id: 4741, name: 'Computer Account Created', description: 'A computer account was created in AD.', severity: 'Info' },
      { id: 4742, name: 'Computer Account Changed', description: 'A computer account was changed.', severity: 'Info' },
      { id: 4743, name: 'Computer Account Deleted', description: 'A computer account was deleted from AD.', severity: 'Warning' },
      { id: 4756, name: 'Member Added to Universal Group', description: 'A member was added to a security-enabled universal group.', severity: 'Info' },
      { id: 4757, name: 'Member Removed from Universal Group', description: 'A member was removed from a security-enabled universal group.', severity: 'Warning' },
      { id: 4781, name: 'Account Name Changed', description: 'The name of an account was changed.', severity: 'Warning' },
    ],
  },
  {
    category: 'Process & Task Activity',
    log: 'Security',
    events: [
      { id: 4688, name: 'New Process Created', description: 'A new process has been created. Enable command line auditing to capture full arguments — critical for threat hunting.', severity: 'Info' },
      { id: 4689, name: 'Process Exited', description: 'A process has exited. Correlate with 4688 for process lifetime.', severity: 'Info' },
      { id: 4698, name: 'Scheduled Task Created', description: 'A scheduled task was created. Common persistence mechanism for malware.', severity: 'Warning' },
      { id: 4699, name: 'Scheduled Task Deleted', description: 'A scheduled task was deleted.', severity: 'Warning' },
      { id: 4700, name: 'Scheduled Task Enabled', description: 'A scheduled task was enabled.', severity: 'Warning' },
      { id: 4701, name: 'Scheduled Task Disabled', description: 'A scheduled task was disabled.', severity: 'Info' },
      { id: 4702, name: 'Scheduled Task Updated', description: 'A scheduled task was updated. Check for changes to actions or triggers.', severity: 'Warning' },
    ],
  },
  {
    category: 'PowerShell & Script Activity',
    log: 'PowerShell / Operational',
    events: [
      { id: 4103, name: 'Pipeline Execution', description: 'PowerShell pipeline execution details. Requires Module Logging to be enabled.', severity: 'Info' },
      { id: 4104, name: 'Script Block Logging', description: 'PowerShell script block was executed. Captures full script content — enable for security visibility.', severity: 'Warning' },
      { id: 4105, name: 'Script Block Start', description: 'PowerShell started executing a script block.', severity: 'Info' },
      { id: 4106, name: 'Script Block End', description: 'PowerShell finished executing a script block.', severity: 'Info' },
      { id: 400, name: 'PowerShell Session Started', description: 'A new PowerShell session (engine state change to Available). Check HostApplication for source.', severity: 'Info' },
      { id: 403, name: 'PowerShell Session Ended', description: 'PowerShell engine state changed to Stopped. Session ended.', severity: 'Info' },
      { id: 600, name: 'PowerShell Provider Loaded', description: 'A PowerShell provider was loaded. WSMan provider load may indicate remoting activity.', severity: 'Info' },
    ],
  },
  {
    category: 'Object & File Access',
    log: 'Security',
    events: [
      { id: 4656, name: 'Object Handle Requested', description: 'A handle to an object was requested. Auditing must be enabled on the object.', severity: 'Info' },
      { id: 4660, name: 'Object Deleted', description: 'An object was deleted.', severity: 'Warning' },
      { id: 4663, name: 'Object Access Attempt', description: 'An attempt was made to access an object such as a file, folder, or registry key.', severity: 'Info' },
      { id: 4670, name: 'Object Permissions Changed', description: 'Permissions on an object were changed.', severity: 'Warning' },
    ],
  },
  {
    category: 'Policy & Audit Changes',
    log: 'Security',
    events: [
      { id: 4719, name: 'Audit Policy Changed', description: 'System audit policy was changed. Could indicate an attacker disabling logging.', severity: 'Warning' },
      { id: 4739, name: 'Domain Policy Changed', description: 'Domain policy was changed including password policy or lockout settings.', severity: 'Warning' },
      { id: 4902, name: 'Audit Policy Table Created', description: 'The per-user audit policy table was created during system startup.', severity: 'Info' },
      { id: 4906, name: 'CrashOnAuditFail Value Changed', description: 'The CrashOnAuditFail value was changed. If set to 1, system will crash if security log is full.', severity: 'Warning' },
      { id: 4907, name: 'Auditing Settings Changed', description: 'Auditing settings on an object were changed.', severity: 'Warning' },
    ],
  },
  {
    category: 'Network & Firewall',
    log: 'Security',
    events: [
      { id: 5140, name: 'Network Share Accessed', description: 'A network share object was accessed.', severity: 'Info' },
      { id: 5142, name: 'Network Share Added', description: 'A network share object was added.', severity: 'Warning' },
      { id: 5144, name: 'Network Share Deleted', description: 'A network share object was deleted.', severity: 'Warning' },
      { id: 5156, name: 'Firewall Allowed Connection', description: 'Windows Filtering Platform permitted a network connection.', severity: 'Info' },
      { id: 5157, name: 'Firewall Blocked Connection', description: 'Windows Filtering Platform blocked a network connection.', severity: 'Warning' },
      { id: 5447, name: 'Firewall Filter Changed', description: 'A Windows Filtering Platform filter was changed.', severity: 'Warning' },
    ],
  },
  {
    category: 'System Startup & Shutdown',
    log: 'System',
    events: [
      { id: 41, name: 'Kernel-Power: Unexpected Shutdown', description: 'The system rebooted without cleanly shutting down. Often indicates a crash, power loss, or BSOD.', severity: 'Critical' },
      { id: 1074, name: 'System Shutdown / Restart', description: 'A process or user initiated a system shutdown or restart. Includes who and why.', severity: 'Info' },
      { id: 1076, name: 'Shutdown Reason Set', description: 'The user set the reason for an unexpected shutdown.', severity: 'Info' },
      { id: 6005, name: 'Event Log Service Started', description: 'The event log service was started. Indicates system boot.', severity: 'Info' },
      { id: 6006, name: 'Event Log Service Stopped', description: 'The event log service was stopped. Indicates clean shutdown.', severity: 'Info' },
      { id: 6008, name: 'Unexpected Shutdown', description: 'The previous system shutdown was unexpected. Typically precedes event 41.', severity: 'Error' },
      { id: 6013, name: 'System Uptime', description: 'Logged daily — shows system uptime in seconds. Useful for detecting hidden reboots.', severity: 'Info' },
    ],
  },
  {
    category: 'Services',
    log: 'System',
    events: [
      { id: 7000, name: 'Service Failed to Start', description: 'A service failed to start. Check the error code for root cause.', severity: 'Error' },
      { id: 7001, name: 'Service Dependency Failed', description: 'A service failed to start due to a dependency failure.', severity: 'Error' },
      { id: 7009, name: 'Service Timeout', description: 'A timeout was reached while waiting for a service to connect.', severity: 'Error' },
      { id: 7011, name: 'Service Transaction Timeout', description: 'A timeout was reached waiting for a transaction response from a service.', severity: 'Warning' },
      { id: 7022, name: 'Service Hung on Start', description: 'A service hung on starting.', severity: 'Warning' },
      { id: 7023, name: 'Service Terminated with Error', description: 'A service terminated with the listed error code.', severity: 'Error' },
      { id: 7024, name: 'Service Terminated with Specific Error', description: 'A service terminated with a service-specific error.', severity: 'Error' },
      { id: 7031, name: 'Service Crashed', description: 'A service terminated unexpectedly. Check recovery actions.', severity: 'Error' },
      { id: 7034, name: 'Service Crashed Unexpectedly', description: 'A service terminated unexpectedly. No recovery action configured.', severity: 'Error' },
      { id: 7036, name: 'Service State Change', description: 'A service entered a running or stopped state.', severity: 'Info' },
      { id: 7040, name: 'Service Start Type Changed', description: 'The start type of a service was changed. Watch for security services being set to Disabled.', severity: 'Warning' },
      { id: 7045, name: 'New Service Installed', description: 'A new service was installed on the system. Common malware persistence vector.', severity: 'Warning' },
    ],
  },
  {
    category: 'Application Errors',
    log: 'Application',
    events: [
      { id: 1000, name: 'Application Error', description: 'An application faulted and was terminated. Check faulting module and exception code for root cause.', severity: 'Error' },
      { id: 1001, name: 'Application Fault (WER)', description: 'Windows Error Reporting logged a fault. Correlates with event 1000.', severity: 'Error' },
      { id: 1002, name: 'Application Hang', description: 'An application stopped responding and was terminated by the user or system.', severity: 'Warning' },
      { id: 1026, name: '.NET Runtime Error', description: 'A .NET application encountered an unhandled exception. Check description for stack trace.', severity: 'Error' },
    ],
  },
  {
    category: 'Windows Update',
    log: 'System',
    events: [
      { id: 19, name: 'Update Installed Successfully', description: 'A Windows update was installed successfully.', severity: 'Info' },
      { id: 20, name: 'Update Installation Failed', description: 'A Windows update failed to install. Check error code for details.', severity: 'Error' },
      { id: 43, name: 'Update Installation Started', description: 'Windows Update began installing an update.', severity: 'Info' },
      { id: 44, name: 'Update Download Started', description: 'Windows Update began downloading an update.', severity: 'Info' },
    ],
  },
  {
    category: 'BitLocker',
    log: 'System',
    events: [
      { id: 24577, name: 'Volume Encryption Started', description: 'Encryption of a volume has begun.', severity: 'Info' },
      { id: 24578, name: 'Volume Encryption Stopped', description: 'Encryption of a volume was stopped before completion.', severity: 'Warning' },
      { id: 24579, name: 'Volume Encryption Complete', description: 'Encryption of a volume has completed successfully.', severity: 'Info' },
      { id: 24580, name: 'Volume Decryption Started', description: 'Decryption of a BitLocker-protected volume has begun.', severity: 'Warning' },
      { id: 24581, name: 'Volume Decryption Complete', description: 'Decryption of a BitLocker-protected volume has completed.', severity: 'Warning' },
      { id: 24582, name: 'Volume Decryption Stopped', description: 'Decryption of a volume was stopped before completion.', severity: 'Warning' },
      { id: 24588, name: 'Volume Check Failed', description: 'The validation of a volume has failed. Volume may be corrupt.', severity: 'Error' },
      { id: 24621, name: 'Initial Volume State Check', description: 'BitLocker performed initial state check on the volume.', severity: 'Info' },
    ],
  },
  {
    category: 'Group Policy',
    log: 'System',
    events: [
      { id: 1500, name: 'Group Policy Applied (Computer)', description: 'Computer Group Policy was applied successfully.', severity: 'Info' },
      { id: 1501, name: 'Group Policy Applied (User)', description: 'User Group Policy was applied successfully.', severity: 'Info' },
      { id: 1502, name: 'Group Policy Applied (Local)', description: 'Local Group Policy was applied successfully.', severity: 'Info' },
      { id: 1503, name: 'Group Policy Applied (Local User)', description: 'Local user Group Policy was applied successfully.', severity: 'Info' },
      { id: 1006, name: 'Group Policy Processing Failed (Computer)', description: 'Windows failed to apply Group Policy for the computer. Check for network or DC connectivity issues.', severity: 'Error' },
      { id: 1007, name: 'Group Policy Processing Failed (User)', description: 'Windows failed to apply Group Policy for the user.', severity: 'Error' },
      { id: 1125, name: 'Group Policy Processing Slow Link', description: 'Windows is applying Group Policy over a slow link.', severity: 'Warning' },
    ],
  },
  {
    category: 'RDP & Remote Access',
    log: 'Security / TerminalServices',
    events: [
      { id: 1149, name: 'RDP Auth Succeeded (No Credentials)', description: 'User authenticated to Remote Desktop without credentials prompt. Check for pass-the-hash or saved credentials.', severity: 'Warning' },
      { id: 4778, name: 'RDP Session Reconnected', description: 'A Remote Desktop session was reconnected.', severity: 'Info' },
      { id: 4779, name: 'RDP Session Disconnected', description: 'A Remote Desktop session was disconnected.', severity: 'Info' },
      { id: 21, name: 'RDP Logon Successful', description: 'Remote Desktop Services: Session logon succeeded.', severity: 'Info' },
      { id: 22, name: 'RDP Shell Started', description: 'Remote Desktop Services: Shell start notification received.', severity: 'Info' },
      { id: 23, name: 'RDP Session Logoff', description: 'Remote Desktop Services: Session logoff succeeded.', severity: 'Info' },
      { id: 24, name: 'RDP Session Disconnected', description: 'Remote Desktop Services: Session has been disconnected.', severity: 'Info' },
      { id: 25, name: 'RDP Session Reconnection Succeeded', description: 'Remote Desktop Services: Session reconnection succeeded.', severity: 'Info' },
    ],
  },
  {
    category: 'Disk & Hardware',
    log: 'System',
    events: [
      { id: 7, name: 'Disk Error', description: 'The device has a bad block. Indicates failing disk — back up immediately and replace.', severity: 'Critical' },
      { id: 11, name: 'Driver Error', description: 'The driver detected a controller error. May indicate failing disk or cable.', severity: 'Error' },
      { id: 51, name: 'Disk Warning', description: 'An error was detected on device during paging operation. Often precedes disk failure.', severity: 'Warning' },
      { id: 157, name: 'Disk Surprise Removed', description: 'A disk was surprise removed. Drive was unplugged without safe ejection.', severity: 'Warning' },
    ],
  },
];
