export const eventsByCategory: {
  category: string
  log: string
  events: {
    id: number
    name: string
    description: string
    severity: 'Info' | 'Warning' | 'Error' | 'Critical'
  }[]
}[] = [
  {
    category: 'Logon & Authentication',
    log: 'Security',
    events: [
      { id: 4624, name: 'Successful Logon', description: 'An account was successfully logged on. Check logon type: 2=Interactive, 3=Network, 4=Batch, 5=Service, 7=Unlock, 10=RemoteInteractive (RDP), 11=CachedInteractive.', severity: 'Info' },
      { id: 4625, name: 'Failed Logon', description: 'An account failed to log on. Sub-status 0xC000006A=bad password, 0xC0000064=bad username, 0xC0000234=account locked, 0xC000006F=outside logon hours.', severity: 'Warning' },
      { id: 4634, name: 'Logoff', description: 'An account was logged off. Logon ID correlates with the initial 4624 event.', severity: 'Info' },
      { id: 4647, name: 'User Initiated Logoff', description: 'User initiated logoff for the listed account. Precedes 4634 for interactive sessions.', severity: 'Info' },
      { id: 4648, name: 'Explicit Credential Logon', description: 'A logon was attempted using explicit credentials (e.g. runas). Common in pass-the-hash and over-pass-the-hash attacks. Check target server name.', severity: 'Warning' },
      { id: 4649, name: 'Replay Attack Detected', description: 'A Kerberos replay attack was detected. A request was received twice with identical information. Potential replay or network issue.', severity: 'Critical' },
      { id: 4672, name: 'Special Privileges Assigned', description: 'Special privileges (admin-equivalent) assigned to new logon session. Track SeDebugPrivilege, SeTcbPrivilege, SeImpersonatePrivilege assignments.', severity: 'Info' },
      { id: 4627, name: 'Group Membership Information', description: 'Group membership information logged at logon. Requires "Audit Group Membership" advanced policy. Correlate with 4624 via Logon ID.', severity: 'Info' },
      { id: 4740, name: 'Account Locked Out', description: 'A user account was locked out. Check caller computer name to find the originating machine. Correlate with 4625 events on that machine.', severity: 'Warning' },
      { id: 4767, name: 'Account Unlocked', description: 'A user account was unlocked by an administrator.', severity: 'Info' },
      { id: 4768, name: 'Kerberos TGT Requested', description: 'A Kerberos TGT was requested. Failure result codes: 0x6=bad username, 0x12=account disabled/expired, 0x17=password expired, 0x18=bad password. Monitor for 0x18 for spray attacks.', severity: 'Info' },
      { id: 4769, name: 'Kerberos Service Ticket Requested', description: 'A Kerberos service ticket was requested. Encryption type 0x17 (RC4) requests against service accounts may indicate Kerberoasting. Monitor for unusual target services.', severity: 'Info' },
      { id: 4770, name: 'Kerberos Service Ticket Renewed', description: 'A Kerberos service ticket was renewed.', severity: 'Info' },
      { id: 4771, name: 'Kerberos Pre-Auth Failed', description: 'Kerberos pre-authentication failed. Failure code 0x18=bad password is most common. High volume from a single source indicates a spray or brute force attack.', severity: 'Warning' },
      { id: 4773, name: 'Kerberos Service Ticket Request Failed', description: 'A Kerberos service ticket request failed. Check failure code for root cause.', severity: 'Warning' },
      { id: 4776, name: 'NTLM Credential Validation', description: 'The domain controller attempted to validate credentials via NTLM. Error code 0xC000006A=bad password, 0xC000006D=generic failure. Monitor for NTLM in environments moving to Kerberos-only.', severity: 'Info' },
      { id: 4778, name: 'RDP Session Reconnected', description: 'A session was reconnected to a Window Station. Check Client Name and Client Address.', severity: 'Info' },
      { id: 4779, name: 'RDP Session Disconnected', description: 'A session was disconnected from a Window Station.', severity: 'Info' },
      { id: 4800, name: 'Workstation Locked', description: 'The workstation was locked by a user.', severity: 'Info' },
      { id: 4801, name: 'Workstation Unlocked', description: 'The workstation was unlocked.', severity: 'Info' },
      { id: 4802, name: 'Screensaver Invoked', description: 'The screen saver was invoked.', severity: 'Info' },
      { id: 4803, name: 'Screensaver Dismissed', description: 'The screen saver was dismissed.', severity: 'Info' },
      { id: 4964, name: 'Special Groups Logon', description: 'Special groups have been assigned to a new logon. Fires when a member of a monitored group logs on. Requires Special Groups registry configuration.', severity: 'Warning' },
    ],
  },
  {
    category: 'Account Management',
    log: 'Security',
    events: [
      { id: 4720, name: 'User Account Created', description: 'A user account was created. Check who created it and in which OU.', severity: 'Info' },
      { id: 4722, name: 'User Account Enabled', description: 'A user account was enabled.', severity: 'Info' },
      { id: 4723, name: 'Password Change Attempt', description: 'An attempt was made to change an account\'s password by the user themselves.', severity: 'Info' },
      { id: 4724, name: 'Password Reset Attempt', description: 'An attempt was made to reset an account\'s password by an administrator.', severity: 'Warning' },
      { id: 4725, name: 'User Account Disabled', description: 'A user account was disabled.', severity: 'Warning' },
      { id: 4726, name: 'User Account Deleted', description: 'A user account was deleted.', severity: 'Warning' },
      { id: 4727, name: 'Global Group Created', description: 'A security-enabled global group was created.', severity: 'Info' },
      { id: 4728, name: 'Member Added to Global Group', description: 'A member was added to a security-enabled global group. Monitor for additions to Domain Admins, Enterprise Admins, Schema Admins.', severity: 'Info' },
      { id: 4729, name: 'Member Removed from Global Group', description: 'A member was removed from a security-enabled global group.', severity: 'Warning' },
      { id: 4730, name: 'Global Group Deleted', description: 'A security-enabled global group was deleted.', severity: 'Warning' },
      { id: 4731, name: 'Local Group Created', description: 'A security-enabled local group was created.', severity: 'Info' },
      { id: 4732, name: 'Member Added to Local Group', description: 'A member was added to a security-enabled local group. Monitor for additions to local Administrators group.', severity: 'Info' },
      { id: 4733, name: 'Member Removed from Local Group', description: 'A member was removed from a security-enabled local group.', severity: 'Warning' },
      { id: 4734, name: 'Local Group Deleted', description: 'A security-enabled local group was deleted.', severity: 'Warning' },
      { id: 4738, name: 'User Account Changed', description: 'A user account was changed. Includes password, flag, and attribute changes. Check "User Account Control" field for flag changes like enabling delegation.', severity: 'Info' },
      { id: 4741, name: 'Computer Account Created', description: 'A computer account was created in AD. Monitor for unexpected machine account creation (MachineAccountQuota abuse).', severity: 'Info' },
      { id: 4742, name: 'Computer Account Changed', description: 'A computer account was changed. Changes to msDS-SupportedEncryptionTypes may indicate downgrade attacks.', severity: 'Info' },
      { id: 4743, name: 'Computer Account Deleted', description: 'A computer account was deleted from AD.', severity: 'Warning' },
      { id: 4756, name: 'Member Added to Universal Group', description: 'A member was added to a security-enabled universal group.', severity: 'Info' },
      { id: 4757, name: 'Member Removed from Universal Group', description: 'A member was removed from a security-enabled universal group.', severity: 'Warning' },
      { id: 4758, name: 'Universal Group Created', description: 'A security-enabled universal group was created.', severity: 'Info' },
      { id: 4759, name: 'Distribution Group Created', description: 'A security-disabled universal (distribution) group was created.', severity: 'Info' },
      { id: 4760, name: 'Distribution Group Changed', description: 'A security-disabled universal group was changed.', severity: 'Info' },
      { id: 4761, name: 'Member Added to Distribution Group', description: 'A member was added to a security-disabled universal group.', severity: 'Info' },
      { id: 4762, name: 'Universal Group Changed', description: 'A security-enabled universal group was changed.', severity: 'Info' },
      { id: 4781, name: 'Account Name Changed', description: 'The name of an account was changed. Renaming built-in accounts (Administrator, Guest) generates this event.', severity: 'Warning' },
      { id: 4782, name: 'Password Hash Accessed', description: 'The password hash of an account was accessed. Seen during DCSync attacks (Mimikatz lsadump::dcsync). Critical indicator of compromise.', severity: 'Critical' },
      { id: 4793, name: 'Password Policy Checking API Called', description: 'The Password Policy Checking API was called. Can indicate password auditing tools or pre-attack enumeration.', severity: 'Info' },
      { id: 4794, name: 'DSRM Password Set Attempt', description: 'An attempt was made to set the Directory Services Restore Mode administrator password. Attackers set this to maintain persistence on DCs.', severity: 'Critical' },
      { id: 4798, name: 'User\'s Local Group Membership Enumerated', description: 'A user\'s local group membership was enumerated. Common during post-exploitation reconnaissance. Check calling process.', severity: 'Warning' },
      { id: 4799, name: 'Security-Enabled Local Group Membership Enumerated', description: 'A security-enabled local group membership was enumerated. Often part of lateral movement reconnaissance.', severity: 'Warning' },
    ],
  },
  {
    category: 'Privilege Use & Sensitive Operations',
    log: 'Security',
    events: [
      { id: 4673, name: 'Privileged Service Called', description: 'A privileged service was called. Tracks use of sensitive privileges like SeDebugPrivilege, SeTcbPrivilege. High volume; filter for sensitive privileges only.', severity: 'Warning' },
      { id: 4674, name: 'Privileged Object Operation', description: 'An operation was attempted on a privileged object. Tracks privilege use on specific objects.', severity: 'Warning' },
      { id: 4703, name: 'Token Right Adjusted', description: 'A user\'s token privilege was enabled or disabled. Can indicate privilege escalation attempts or tools adjusting their own privileges.', severity: 'Warning' },
      { id: 4704, name: 'User Right Assigned', description: 'A user right was assigned to an account. Changes to SeDebugPrivilege, SeImpersonatePrivilege, or SeTcbPrivilege are high priority.', severity: 'Warning' },
      { id: 4705, name: 'User Right Removed', description: 'A user right was removed from an account.', severity: 'Info' },
      { id: 4985, name: 'Transaction State Changed', description: 'The state of a transaction has changed. Part of the Kernel Transaction Manager; relevant to transacted file operations.', severity: 'Info' },
    ],
  },
  {
    category: 'Process & Task Activity',
    log: 'Security',
    events: [
      { id: 4688, name: 'New Process Created', description: 'A new process has been created. Enable command line auditing (GPO) to capture full arguments. Watch for: cmd.exe, powershell.exe, wscript.exe, cscript.exe, mshta.exe, regsvr32.exe, rundll32.exe spawned by Office apps.', severity: 'Info' },
      { id: 4689, name: 'Process Exited', description: 'A process has exited. Correlate with 4688 via Process ID for process lifetime analysis.', severity: 'Info' },
      { id: 4696, name: 'Primary Token Assigned to Process', description: 'A primary token was assigned to a process. Tracks token assignment for service processes.', severity: 'Info' },
      { id: 4698, name: 'Scheduled Task Created', description: 'A scheduled task was created. Common persistence mechanism. Check task name, action, and trigger. Watch for tasks running from temp directories or with encoded commands.', severity: 'Warning' },
      { id: 4699, name: 'Scheduled Task Deleted', description: 'A scheduled task was deleted. Attackers may delete tasks after execution to cover tracks.', severity: 'Warning' },
      { id: 4700, name: 'Scheduled Task Enabled', description: 'A scheduled task was enabled.', severity: 'Warning' },
      { id: 4701, name: 'Scheduled Task Disabled', description: 'A scheduled task was disabled.', severity: 'Info' },
      { id: 4702, name: 'Scheduled Task Updated', description: 'A scheduled task was updated. Check for changes to task actions or triggers that may indicate backdooring.', severity: 'Warning' },
    ],
  },
  {
    category: 'Task Scheduler Operational',
    log: 'Microsoft-Windows-TaskScheduler/Operational',
    events: [
      { id: 100, name: 'Task Started', description: 'Task Scheduler started a task. Includes task name, instance ID, and user context.', severity: 'Info' },
      { id: 102, name: 'Task Completed', description: 'Task Scheduler successfully finished a task instance.', severity: 'Info' },
      { id: 103, name: 'Task Failed', description: 'Task Scheduler failed to start a task. Check result code for cause.', severity: 'Warning' },
      { id: 106, name: 'Task Registered', description: 'A task was registered (created or updated). Useful for tracking task creation without enabling Security auditing.', severity: 'Warning' },
      { id: 107, name: 'Task Triggered', description: 'Task Scheduler launched a task due to a trigger. Includes trigger type (time, event, logon, etc.).', severity: 'Info' },
      { id: 108, name: 'Task Engine Started', description: 'Task Scheduler service started a task engine process.', severity: 'Info' },
      { id: 110, name: 'Task Engine Stopped', description: 'Task Scheduler stopped a task engine process.', severity: 'Info' },
      { id: 111, name: 'Task Engine Crashed', description: 'Task Scheduler stopped an instance due to an unexpected error.', severity: 'Error' },
      { id: 119, name: 'Task Queued', description: 'Task Scheduler queued an instance of a task.', severity: 'Info' },
      { id: 129, name: 'Task Process Created', description: 'Task Scheduler created a process for a task. Includes PID — correlate with 4688 for full command line.', severity: 'Info' },
      { id: 140, name: 'Task Updated', description: 'A user updated task settings.', severity: 'Warning' },
      { id: 141, name: 'Task Deleted', description: 'A user deleted a task.', severity: 'Warning' },
      { id: 142, name: 'Task Disabled', description: 'A user disabled a task.', severity: 'Info' },
      { id: 200, name: 'Action Started', description: 'Task Scheduler launched the action of a task. Includes action path.', severity: 'Info' },
      { id: 201, name: 'Action Completed', description: 'Task Scheduler successfully completed the task action.', severity: 'Info' },
      { id: 203, name: 'Action Failed', description: 'Task Scheduler failed to execute the task action. Check return code.', severity: 'Warning' },
    ],
  },
  {
    category: 'PowerShell & Script Activity',
    log: 'PowerShell / Operational',
    events: [
      { id: 4103, name: 'Pipeline Execution Details', description: 'PowerShell pipeline execution details captured. Requires Module Logging to be enabled. High volume but critical for detecting malicious modules.', severity: 'Info' },
      { id: 4104, name: 'Script Block Logging', description: 'PowerShell script block was executed. Captures full script content including deobfuscated code. Enable for security visibility. Severity elevated automatically for suspicious content.', severity: 'Warning' },
      { id: 4105, name: 'Script Block Start', description: 'PowerShell started executing a script block.', severity: 'Info' },
      { id: 4106, name: 'Script Block End', description: 'PowerShell finished executing a script block.', severity: 'Info' },
      { id: 400, name: 'PowerShell Session Started', description: 'A new PowerShell session started (engine state changed to Available). Check HostApplication field — wsmprovhost.exe indicates WinRM remoting.', severity: 'Info' },
      { id: 403, name: 'PowerShell Session Ended', description: 'PowerShell engine state changed to Stopped. Session ended.', severity: 'Info' },
      { id: 600, name: 'PowerShell Provider Loaded', description: 'A PowerShell provider was loaded. WSMan provider load indicates remoting activity. Registry provider load may indicate registry manipulation.', severity: 'Info' },
      { id: 800, name: 'Pipeline Execution Details (V2)', description: 'PowerShell pipeline execution — older V2 engine variant. May indicate attackers downgrading to PowerShell v2 to bypass AMSI and logging.', severity: 'Warning' },
    ],
  },
  {
    category: 'Object & File Access',
    log: 'Security',
    events: [
      { id: 4656, name: 'Object Handle Requested', description: 'A handle to an object was requested. Requires SACL auditing on the object. Generates before 4663 — indicates access attempt.', severity: 'Info' },
      { id: 4657, name: 'Registry Value Modified', description: 'A registry value was modified. Requires SACL on the registry key. Use to monitor sensitive keys like Run, Services, LSA, Winlogon.', severity: 'Warning' },
      { id: 4658, name: 'Object Handle Closed', description: 'The handle to an object was closed. Correlate with 4656 to track access duration.', severity: 'Info' },
      { id: 4660, name: 'Object Deleted', description: 'An object was deleted. Requires SACL auditing on the object.', severity: 'Warning' },
      { id: 4661, name: 'SAM Object Handle Requested', description: 'A handle was requested for a SAM object. High volume of these against user/group objects may indicate enumeration (BloodHound, ADFind).', severity: 'Warning' },
      { id: 4663, name: 'Object Access Attempt', description: 'An attempt was made to access an object. Requires SACL auditing on the object. Check accesses field: ReadData=file read, WriteData=file write, DELETE=delete.', severity: 'Info' },
      { id: 4670, name: 'Object Permissions Changed', description: 'Permissions on an object were changed. Check old and new DACL values for suspicious permission additions.', severity: 'Warning' },
    ],
  },
  {
    category: 'Active Directory & LDAP',
    log: 'Security',
    events: [
      { id: 4662, name: 'AD Object Operation', description: 'An operation was performed on an AD object. Requires DS Access auditing. GUID 1131f6aa/1131f6ab in properties field indicates DCSync replication rights — critical IOC.', severity: 'Critical' },
      { id: 4928, name: 'AD Replica Source Naming Context Established', description: 'An AD replica source naming context was established. Legitimate DC replication or possible DCSync attack — verify source DC.', severity: 'Warning' },
      { id: 4929, name: 'AD Replica Source Naming Context Removed', description: 'An AD replica source naming context was removed.', severity: 'Info' },
      { id: 5136, name: 'AD Object Modified', description: 'A directory service object was modified. Requires DS Changes auditing. Check attribute name and value for unauthorized changes (e.g., adminCount, msDS-AllowedToActOnBehalfOfOtherIdentity for RBCD attacks).', severity: 'Warning' },
      { id: 5137, name: 'AD Object Created', description: 'A directory service object was created. Unexpected OU/computer/user object creation may indicate attack activity.', severity: 'Warning' },
      { id: 5138, name: 'AD Object Undeleted', description: 'A directory service object was undeleted (AD Recycle Bin).', severity: 'Info' },
      { id: 5139, name: 'AD Object Moved', description: 'A directory service object was moved to a different container.', severity: 'Warning' },
      { id: 5141, name: 'AD Object Deleted', description: 'A directory service object was deleted. Monitor for deletion of domain controllers, key OUs, or GPO objects.', severity: 'Warning' },
    ],
  },
  {
    category: 'Policy & Audit Changes',
    log: 'Security',
    events: [
      { id: 4706, name: 'Domain Trust Created', description: 'A new domain trust was created. Unauthorized trust creation could allow cross-domain attacks.', severity: 'Critical' },
      { id: 4707, name: 'Domain Trust Removed', description: 'A domain trust was removed.', severity: 'Warning' },
      { id: 4713, name: 'Kerberos Policy Changed', description: 'Kerberos policy was changed. Changes to ticket lifetime or clock tolerance may indicate tampering.', severity: 'Warning' },
      { id: 4716, name: 'Trusted Domain Information Changed', description: 'Trusted domain information was changed. Check for SID filtering changes which can weaken trust security.', severity: 'Warning' },
      { id: 4719, name: 'Audit Policy Changed', description: 'System audit policy was changed. Could indicate an attacker disabling logging to evade detection.', severity: 'Warning' },
      { id: 4739, name: 'Domain Policy Changed', description: 'Domain policy was changed including password policy or lockout settings.', severity: 'Warning' },
      { id: 4902, name: 'Audit Policy Table Created', description: 'The per-user audit policy table was created during system startup.', severity: 'Info' },
      { id: 4904, name: 'Security Event Source Registered', description: 'An attempt was made to register a security event source.', severity: 'Info' },
      { id: 4905, name: 'Security Event Source Unregistered', description: 'An attempt was made to unregister a security event source.', severity: 'Warning' },
      { id: 4906, name: 'CrashOnAuditFail Value Changed', description: 'The CrashOnAuditFail value was changed. If set to 1 the system will crash if the security log is full.', severity: 'Warning' },
      { id: 4907, name: 'Auditing Settings Changed on Object', description: 'Auditing settings on an object were changed. Could indicate disabling audit trail on a specific resource.', severity: 'Warning' },
      { id: 4912, name: 'Per-User Audit Policy Changed', description: 'Per-user audit policy was changed.', severity: 'Warning' },
    ],
  },
  {
    category: 'Event Log Integrity',
    log: 'Security / System',
    events: [
      { id: 1100, name: 'Event Log Service Shutting Down', description: 'The event logging service was shut down. If unexpected, may indicate tampering or the system is being shut down.', severity: 'Warning' },
      { id: 1101, name: 'Audit Events Dropped', description: 'Audit events were dropped due to the audit queue being full. Increase log size or reduce audit volume.', severity: 'Error' },
      { id: 1102, name: 'Security Audit Log Cleared', description: 'The Security audit log was cleared. This is a high-priority indicator — attackers clear logs to cover tracks. Check who cleared it.', severity: 'Critical' },
      { id: 104, name: 'Event Log Cleared (System/Application)', description: 'A System or Application log was cleared. Log: System (wevtutil). Check SubjectUserName — clearing logs is a common anti-forensics technique.', severity: 'Critical' },
    ],
  },
  {
    category: 'Network & Firewall',
    log: 'Security',
    events: [
      { id: 5140, name: 'Network Share Accessed', description: 'A network share object was accessed. Check share name (C$, ADMIN$, IPC$) and source IP for lateral movement indicators.', severity: 'Info' },
      { id: 5142, name: 'Network Share Added', description: 'A network share object was added. Unexpected share creation may indicate data staging.', severity: 'Warning' },
      { id: 5144, name: 'Network Share Deleted', description: 'A network share object was deleted.', severity: 'Warning' },
      { id: 5145, name: 'Network Share File Access Check', description: 'A network share object was checked to see whether the client can be granted desired access. Generates for every file access — very high volume on file servers. Filter for denied access.', severity: 'Info' },
      { id: 5152, name: 'WFP Blocked Packet', description: 'Windows Filtering Platform blocked a network packet.', severity: 'Info' },
      { id: 5154, name: 'WFP Permitted Listen', description: 'Windows Filtering Platform permitted an application to listen on a port.', severity: 'Info' },
      { id: 5155, name: 'WFP Blocked Listen', description: 'Windows Filtering Platform blocked an application from listening on a port.', severity: 'Warning' },
      { id: 5156, name: 'Firewall Allowed Connection', description: 'Windows Filtering Platform permitted a network connection. Very high volume — use only for specific IP/port monitoring.', severity: 'Info' },
      { id: 5157, name: 'Firewall Blocked Connection', description: 'Windows Filtering Platform blocked a network connection. Useful for detecting C2 callback attempts and lateral movement.', severity: 'Warning' },
      { id: 5158, name: 'WFP Permitted Bind', description: 'Windows Filtering Platform permitted a bind to a local port.', severity: 'Info' },
      { id: 5159, name: 'WFP Blocked Bind', description: 'Windows Filtering Platform blocked a bind to a local port.', severity: 'Warning' },
      { id: 5447, name: 'WFP Filter Changed', description: 'A Windows Filtering Platform filter was changed. May indicate firewall rule tampering.', severity: 'Warning' },
    ],
  },
  {
    category: 'Windows Firewall Rule Changes',
    log: 'Microsoft-Windows-Windows Firewall With Advanced Security/Firewall',
    events: [
      { id: 2004, name: 'Firewall Rule Added', description: 'A firewall rule was added to the Windows Firewall exception list. Malware often adds rules to allow inbound connections. Check rule name, direction, protocol, and application path.', severity: 'Warning' },
      { id: 2005, name: 'Firewall Rule Modified', description: 'A firewall rule was modified. Check what changed and whether it opens a new attack surface.', severity: 'Warning' },
      { id: 2006, name: 'Firewall Rule Deleted', description: 'A firewall rule was deleted.', severity: 'Warning' },
      { id: 2033, name: 'Firewall Rule List Cleared', description: 'All firewall rules in a profile were deleted. This is a critical event — may indicate an attacker disabling host-based firewall controls.', severity: 'Critical' },
      { id: 2009, name: 'Firewall Failed to Load Group Policy', description: 'Windows Firewall failed to load Group Policy. Firewall may not be in the expected state.', severity: 'Error' },
      { id: 2010, name: 'Firewall Failed to Load Local Policy', description: 'Windows Firewall could not load local policy. Check for policy corruption.', severity: 'Error' },
    ],
  },
  {
    category: 'Windows Defender & Antivirus',
    log: 'Microsoft-Windows-Windows Defender/Operational',
    events: [
      { id: 1006, name: 'Malware Detected (Engine)', description: 'Windows Defender antimalware engine found malware or potentially unwanted software. Note threat name, severity, and detection path.', severity: 'Critical' },
      { id: 1007, name: 'Action Taken on Malware', description: 'Windows Defender antimalware platform performed an action to protect your machine from malware or potentially unwanted software.', severity: 'Warning' },
      { id: 1008, name: 'Malware Action Failed', description: 'Windows Defender failed to take action on malware. The threat may still be active.', severity: 'Critical' },
      { id: 1009, name: 'Quarantine Restore', description: 'A quarantined item was restored from quarantine by a user. Verify this was authorized.', severity: 'Warning' },
      { id: 1010, name: 'Quarantine Restore Failed', description: 'Windows Defender failed to restore a quarantined item.', severity: 'Error' },
      { id: 1011, name: 'Quarantine Delete', description: 'A quarantined item was deleted by a user.', severity: 'Info' },
      { id: 1012, name: 'Quarantine Delete Failed', description: 'Windows Defender failed to delete a quarantined item.', severity: 'Error' },
      { id: 1013, name: 'History Delete', description: 'Malware detection history was deleted by a user. Verify this was authorized — attackers may clear history to hide activity.', severity: 'Warning' },
      { id: 1015, name: 'Suspicious Behavior Detected', description: 'Windows Defender detected suspicious behavior that may indicate a threat even if no known signature matched.', severity: 'Critical' },
      { id: 1116, name: 'Malware Detected (Platform)', description: 'Windows Defender antimalware platform detected malware or potentially unwanted software.', severity: 'Critical' },
      { id: 1117, name: 'Malware Action Taken (Platform)', description: 'Windows Defender antimalware platform performed action to protect against malware or potentially unwanted software.', severity: 'Warning' },
      { id: 1118, name: 'Malware Action Failed (Platform)', description: 'Windows Defender antimalware platform attempted but failed to perform an action. The threat may remain active.', severity: 'Critical' },
      { id: 1119, name: 'Malware Critical Action Failed', description: 'A critical error occurred when taking action on malware. Investigate immediately.', severity: 'Critical' },
      { id: 3002, name: 'Real-Time Protection Failed', description: 'Windows Defender real-time protection encountered an error and failed. System may be unprotected.', severity: 'Critical' },
      { id: 5001, name: 'Real-Time Protection Disabled', description: 'Windows Defender real-time protection was disabled. Verify this was authorized and investigate if unexpected.', severity: 'Critical' },
      { id: 5004, name: 'Real-Time Protection Configuration Changed', description: 'Windows Defender real-time protection configuration changed. Check what setting changed.', severity: 'Warning' },
      { id: 5007, name: 'Antimalware Platform Configuration Changed', description: 'Windows Defender antimalware platform configuration changed. Monitor for exclusion additions which attackers use to bypass scanning.', severity: 'Warning' },
      { id: 5010, name: 'Antimalware Scanning for Malware Disabled', description: 'Scanning for malware and other potentially unwanted software was disabled.', severity: 'Critical' },
      { id: 5012, name: 'Scanning for Viruses Disabled', description: 'Scanning for viruses was disabled. System may be unprotected.', severity: 'Critical' },
    ],
  },
  {
    category: 'AppLocker & Application Control',
    log: 'Microsoft-Windows-AppLocker/EXE and DLL',
    events: [
      { id: 8002, name: 'AppLocker: Allowed Executable', description: 'AppLocker allowed an executable file to run. Log only; file was allowed by policy.', severity: 'Info' },
      { id: 8003, name: 'AppLocker: Audited Executable', description: 'AppLocker would have blocked this executable but the policy is in audit mode. Use these events to build your allowlist before switching to enforce.', severity: 'Warning' },
      { id: 8004, name: 'AppLocker: Blocked Executable', description: 'AppLocker blocked an executable from running. Check file path and publisher. Frequent blocks from the same user may indicate policy bypass attempts.', severity: 'Warning' },
      { id: 8006, name: 'AppLocker: Audited Script', description: 'AppLocker would have blocked this script but policy is in audit mode.', severity: 'Warning' },
      { id: 8007, name: 'AppLocker: Blocked Script', description: 'AppLocker blocked a script from running. Check script path and calling process.', severity: 'Warning' },
      { id: 8020, name: 'AppLocker: Audited Packaged App', description: 'AppLocker would have blocked this packaged app installation in audit mode.', severity: 'Info' },
      { id: 8021, name: 'AppLocker: Blocked Packaged App', description: 'AppLocker blocked a Windows Store app from running.', severity: 'Warning' },
      { id: 8023, name: 'AppLocker: Allowed MSI/Script', description: 'AppLocker allowed a Windows Installer package or script to run.', severity: 'Info' },
      { id: 8025, name: 'AppLocker: Blocked MSI/Script', description: 'AppLocker blocked a Windows Installer package from running.', severity: 'Warning' },
    ],
  },
  {
    category: 'WMI Activity',
    log: 'Microsoft-Windows-WMI-Activity/Operational',
    events: [
      { id: 5857, name: 'WMI Provider Loaded', description: 'A WMI provider was loaded. Unexpected providers may indicate malicious WMI registrations.', severity: 'Info' },
      { id: 5858, name: 'WMI Query Error', description: 'A WMI query returned an error. May indicate malformed queries from attack tools.', severity: 'Info' },
      { id: 5859, name: 'WMI Filter-to-Consumer Binding', description: 'A WMI event filter was bound to a consumer. This is the core mechanism for WMI-based persistence (fileless malware). Investigate any unexpected bindings.', severity: 'Critical' },
      { id: 5860, name: 'WMI Temporary Event Registration', description: 'A temporary WMI event consumer was registered. Check for suspicious event filter queries.', severity: 'Warning' },
      { id: 5861, name: 'WMI Permanent Event Registration', description: 'A permanent WMI event consumer was registered. Permanent subscriptions survive reboots and are a common persistence mechanism. Investigate all new registrations.', severity: 'Critical' },
    ],
  },
  {
    category: 'Certificate Services & Cryptography',
    log: 'Security / Application',
    events: [
      { id: 4886, name: 'Certificate Requested', description: 'Certificate Services received a certificate request. Monitor for requests using vulnerable templates (ESC1: no manager approval + client auth EKU + requestor supplies SAN).', severity: 'Info' },
      { id: 4887, name: 'Certificate Issued', description: 'Certificate Services approved and issued a certificate. Check template name and requester — unexpected high-privilege certificates are a critical IOC.', severity: 'Warning' },
      { id: 4888, name: 'Certificate Request Denied', description: 'Certificate Services denied a certificate request. Repeated denials may indicate enumeration of CA templates.', severity: 'Info' },
      { id: 4890, name: 'Certificate Manager Settings Changed', description: 'The certificate manager settings for Certificate Services changed. Unauthorized changes could weaken CA security posture.', severity: 'Warning' },
      { id: 4891, name: 'Certificate Services Configuration Entry Changed', description: 'A configuration entry changed in Certificate Services.', severity: 'Warning' },
      { id: 4892, name: 'Certificate Services Property Changed', description: 'A property of Certificate Services changed.', severity: 'Warning' },
      { id: 4896, name: 'Certificate Services Database Row Deleted', description: 'One or more rows have been deleted from the certificate database.', severity: 'Warning' },
      { id: 4897, name: 'Role Separation Enabled', description: 'Role separation was enabled in Certificate Services.', severity: 'Info' },
    ],
  },
  {
    category: 'Credential Manager',
    log: 'Security',
    events: [
      { id: 5376, name: 'Credential Manager Credentials Backed Up', description: 'Credential Manager credentials were backed up. Check if this was user-initiated or automated.', severity: 'Warning' },
      { id: 5377, name: 'Credential Manager Credentials Restored', description: 'Credential Manager credentials were restored from backup.', severity: 'Warning' },
      { id: 5378, name: 'Credential Delegation Not Allowed', description: 'The requested credentials delegation was not allowed by policy. May indicate CredSSP misconfiguration or attack attempt.', severity: 'Warning' },
      { id: 5379, name: 'Credential Manager Read', description: 'A user credential was read from Credential Manager. Repeated reads by unexpected processes may indicate credential harvesting.', severity: 'Warning' },
      { id: 5380, name: 'Vault Credentials Searched', description: 'A user searched credentials in Credential Manager Vault.', severity: 'Info' },
      { id: 5381, name: 'Vault Credentials Listed', description: 'A user enumerated credentials in Credential Manager Vault.', severity: 'Warning' },
      { id: 5382, name: 'Vault Credentials Read', description: 'A user read a credential from Credential Manager Vault.', severity: 'Warning' },
    ],
  },
  {
    category: 'Driver & Device Installation',
    log: 'System / Microsoft-Windows-DriverFrameworks-UserMode/Operational',
    events: [
      { id: 20001, name: 'Device Driver Installed', description: 'A device driver was installed. Unexpected kernel-mode driver installations are a critical indicator of rootkit activity or persistence.', severity: 'Warning' },
      { id: 20003, name: 'Device Driver Service Added', description: 'A device driver service was added to the system. Check driver name and file path.', severity: 'Warning' },
      { id: 10000, name: 'USB Device Connected (UMDFv2)', description: 'A USB device was connected. Log: UserMode DriverFrameworks Operational. Includes device path and hardware ID.', severity: 'Info' },
      { id: 10001, name: 'USB Device Disconnected', description: 'A USB device was disconnected.', severity: 'Info' },
      { id: 6416, name: 'New External Device Recognized', description: 'A new external device was recognized by the system. Security log variant — requires Device Installation auditing.', severity: 'Info' },
      { id: 6419, name: 'Device Disabled', description: 'A request was made to disable a device.', severity: 'Warning' },
      { id: 6420, name: 'Device Enabled', description: 'A request was made to enable a device.', severity: 'Info' },
      { id: 6421, name: 'Device Access Request', description: 'A request was made to access a removable device. Requires removable device auditing.', severity: 'Info' },
      { id: 6422, name: 'Removable Device Allowed', description: 'Removable storage was allowed by policy.', severity: 'Info' },
      { id: 6423, name: 'Removable Device Blocked', description: 'Installation of a removable device was blocked by policy.', severity: 'Warning' },
      { id: 6424, name: 'Removable Device Installation Allowed After Block', description: 'Installation of a removable device that was previously blocked was allowed by an administrator.', severity: 'Warning' },
    ],
  },
  {
    category: 'System Startup & Shutdown',
    log: 'System',
    events: [
      { id: 41, name: 'Kernel-Power: Unexpected Shutdown', description: 'The system rebooted without cleanly shutting down. Often indicates a crash (BSOD), hard power loss, or hardware failure. Check BugcheckCode field.', severity: 'Critical' },
      { id: 1074, name: 'System Shutdown / Restart', description: 'A process or user initiated a system shutdown or restart. Includes who initiated it and the reason code.', severity: 'Info' },
      { id: 1076, name: 'Shutdown Reason Set', description: 'The user set the reason for an unexpected shutdown via Shutdown Event Tracker.', severity: 'Info' },
      { id: 6005, name: 'Event Log Service Started', description: 'The event log service was started. Indicates system boot. Note timestamp gap from last 6006 to detect unexpected downtime.', severity: 'Info' },
      { id: 6006, name: 'Event Log Service Stopped', description: 'The event log service was stopped. Indicates a clean shutdown.', severity: 'Info' },
      { id: 6008, name: 'Unexpected Shutdown', description: 'The previous system shutdown was unexpected. Typically precedes event 41. Check for pattern of unexpected shutdowns.', severity: 'Error' },
      { id: 6013, name: 'System Uptime', description: 'Logged daily — shows system uptime in seconds. Useful for detecting hidden reboots between logs.', severity: 'Info' },
    ],
  },
  {
    category: 'Services',
    log: 'System',
    events: [
      { id: 7000, name: 'Service Failed to Start', description: 'A service failed to start. Check the error code — 2=file not found, 5=access denied, 1053=timeout.', severity: 'Error' },
      { id: 7001, name: 'Service Dependency Failed', description: 'A service failed to start because a dependent service failed to start.', severity: 'Error' },
      { id: 7009, name: 'Service Connect Timeout', description: 'A timeout was reached while waiting for a service to connect during startup.', severity: 'Error' },
      { id: 7011, name: 'Service Transaction Timeout', description: 'A timeout was reached waiting for a transaction response from a service.', severity: 'Warning' },
      { id: 7022, name: 'Service Hung on Start', description: 'A service hung on starting and did not respond in time.', severity: 'Warning' },
      { id: 7023, name: 'Service Terminated with Error', description: 'A service terminated with the listed error code. Look up error code in Windows error reference.', severity: 'Error' },
      { id: 7024, name: 'Service Terminated with Specific Error', description: 'A service terminated with a service-specific error. Check service logs for detailed error.', severity: 'Error' },
      { id: 7026, name: 'Boot-Start Driver Failed to Load', description: 'A boot-start or system-start driver failed to load. May indicate driver corruption or AV/security software conflict.', severity: 'Error' },
      { id: 7031, name: 'Service Crashed', description: 'A service terminated unexpectedly and recovery actions were taken. Check recovery count and action taken.', severity: 'Error' },
      { id: 7034, name: 'Service Crashed (No Recovery)', description: 'A service terminated unexpectedly with no recovery action configured.', severity: 'Error' },
      { id: 7036, name: 'Service State Change', description: 'A service entered a running or stopped state. Monitor for security-related services (Defender, EventLog, Firewall) stopping unexpectedly.', severity: 'Info' },
      { id: 7040, name: 'Service Start Type Changed', description: 'The start type of a service was changed. Watch for security services being set to Disabled — common malware defense evasion technique.', severity: 'Warning' },
      { id: 7045, name: 'New Service Installed', description: 'A new service was installed on the system. Common malware persistence vector. Check service binary path for temp directories or encoded commands.', severity: 'Warning' },
    ],
  },
  {
    category: 'Application Errors',
    log: 'Application',
    events: [
      { id: 1000, name: 'Application Error', description: 'An application faulted and was terminated. Check faulting module and exception code. Exception 0xC0000005=access violation, 0xC0000374=heap corruption.', severity: 'Error' },
      { id: 1001, name: 'Application Fault (WER)', description: 'Windows Error Reporting logged a fault. Correlates with event 1000. Contains bucket ID for Microsoft crash lookup.', severity: 'Error' },
      { id: 1002, name: 'Application Hang', description: 'An application stopped responding for more than 5 seconds and was terminated.', severity: 'Warning' },
      { id: 1026, name: '.NET Runtime Error', description: 'A .NET application encountered an unhandled exception. Check description for exception type and stack trace.', severity: 'Error' },
    ],
  },
  {
    category: 'Windows Update',
    log: 'System',
    events: [
      { id: 19, name: 'Update Installed Successfully', description: 'A Windows update was successfully installed. Note KB number for patch tracking.', severity: 'Info' },
      { id: 20, name: 'Update Installation Failed', description: 'A Windows update failed to install. Check error code — 0x80070005=access denied, 0x80070002=file not found. Repeated failures may indicate a corrupted update store.', severity: 'Error' },
      { id: 43, name: 'Update Installation Started', description: 'Windows Update began installing an update.', severity: 'Info' },
      { id: 44, name: 'Update Download Started', description: 'Windows Update began downloading an update.', severity: 'Info' },
    ],
  },
  {
    category: 'BitLocker',
    log: 'System',
    events: [
      { id: 24577, name: 'Volume Encryption Started', description: 'Encryption of a volume has begun.', severity: 'Info' },
      { id: 24578, name: 'Volume Encryption Stopped', description: 'Encryption of a volume was stopped before completion. Investigate if unexpected.', severity: 'Warning' },
      { id: 24579, name: 'Volume Encryption Complete', description: 'Encryption of a volume has completed successfully.', severity: 'Info' },
      { id: 24580, name: 'Volume Decryption Started', description: 'Decryption of a BitLocker-protected volume has begun. Verify this was authorized.', severity: 'Warning' },
      { id: 24581, name: 'Volume Decryption Complete', description: 'Decryption of a BitLocker-protected volume has completed.', severity: 'Warning' },
      { id: 24582, name: 'Volume Decryption Stopped', description: 'Decryption of a volume was stopped before completion.', severity: 'Warning' },
      { id: 24583, name: 'Volume Conversion Worker Thread Started', description: 'The conversion worker thread for a volume has started processing.', severity: 'Info' },
      { id: 24588, name: 'Volume Validation Failed', description: 'The validation of a BitLocker volume has failed. Volume may be corrupt or tampered with.', severity: 'Error' },
      { id: 24621, name: 'Initial Volume State Check', description: 'BitLocker performed an initial state check on the volume at startup.', severity: 'Info' },
    ],
  },
  {
    category: 'Group Policy',
    log: 'System',
    events: [
      { id: 1500, name: 'Group Policy Applied (Computer)', description: 'Computer Group Policy was applied successfully. Check Applied GPOs list in event details.', severity: 'Info' },
      { id: 1501, name: 'Group Policy Applied (User)', description: 'User Group Policy was applied successfully.', severity: 'Info' },
      { id: 1502, name: 'Group Policy Applied (Local)', description: 'Local Group Policy was applied successfully.', severity: 'Info' },
      { id: 1503, name: 'Group Policy Applied (Local User)', description: 'Local user Group Policy was applied successfully.', severity: 'Info' },
      { id: 1006, name: 'GP Processing Failed (Computer)', description: 'Windows failed to apply Group Policy for the computer. Check for network connectivity, DC reachability, or DNS issues.', severity: 'Error' },
      { id: 1007, name: 'GP Processing Failed (User)', description: 'Windows failed to apply Group Policy for the user account.', severity: 'Error' },
      { id: 1125, name: 'GP Processing Slow Link', description: 'Windows is applying Group Policy over a slow network link. Certain CSEs (scripts, folder redirection) may be skipped.', severity: 'Warning' },
      { id: 1126, name: 'GP Processing Slow Link (Fast)', description: 'Windows detected a fast network link during Group Policy processing.', severity: 'Info' },
      { id: 1129, name: 'GP Processing Skipped (Connectivity)', description: 'Group Policy processing was skipped because of connectivity issues. Check network and DC availability.', severity: 'Warning' },
    ],
  },
  {
    category: 'RDP & Remote Access',
    log: 'Security / TerminalServices',
    events: [
      { id: 1149, name: 'RDP Auth Succeeded (No Credentials)', description: 'User authenticated to Remote Desktop without a credentials prompt. Check for pass-the-hash or saved RDP credentials abuse.', severity: 'Warning' },
      { id: 21, name: 'RDP Logon Successful', description: 'Remote Desktop Services: Session logon succeeded. Log: Microsoft-Windows-TerminalServices-LocalSessionManager/Operational.', severity: 'Info' },
      { id: 22, name: 'RDP Shell Started', description: 'Remote Desktop Services: Shell start notification received. Desktop is now available.', severity: 'Info' },
      { id: 23, name: 'RDP Session Logoff', description: 'Remote Desktop Services: Session logoff succeeded.', severity: 'Info' },
      { id: 24, name: 'RDP Session Disconnected', description: 'Remote Desktop Services: Session has been disconnected. Includes client IP address.', severity: 'Info' },
      { id: 25, name: 'RDP Session Reconnection Succeeded', description: 'Remote Desktop Services: Session reconnection succeeded.', severity: 'Info' },
      { id: 39, name: 'RDP Session Disconnect (User)', description: 'Session was disconnected by a local or remote user.', severity: 'Info' },
      { id: 40, name: 'RDP Session Disconnect (Reason)', description: 'Session was disconnected — includes reason code for the disconnect.', severity: 'Info' },
      { id: 4778, name: 'RDP Session Reconnected (Security)', description: 'A session was reconnected to a Window Station. Security log variant — includes client name and address.', severity: 'Info' },
      { id: 4779, name: 'RDP Session Disconnected (Security)', description: 'A session was disconnected from a Window Station. Security log variant.', severity: 'Info' },
    ],
  },
  {
    category: 'Print Activity',
    log: 'Microsoft-Windows-PrintService/Operational',
    events: [
      { id: 307, name: 'Document Printed', description: 'A document was printed. Includes printer name, document name, user, and page count. Useful for DLP and tracking sensitive document printing. Must enable PrintService/Operational log.', severity: 'Info' },
      { id: 805, name: 'Print Job Deleted', description: 'A print job was deleted before completion. May indicate a user canceling a sensitive print job.', severity: 'Info' },
      { id: 800, name: 'Printer Created', description: 'A printer was added to the system.', severity: 'Info' },
      { id: 801, name: 'Printer Deleted', description: 'A printer was removed from the system.', severity: 'Info' },
      { id: 802, name: 'Printer Configuration Changed', description: 'A printer configuration was changed. Watch for driver changes which may indicate Print Spooler exploitation.', severity: 'Warning' },
    ],
  },
  {
    category: 'DNS & DHCP',
    log: 'DNS Server / Microsoft-Windows-Dhcp-Client/Operational',
    events: [
      { id: 150, name: 'DNS Query Logged', description: 'A DNS query was logged by the DNS Server debug log. Requires enabling DNS Analytical logging. Critical for detecting DNS tunneling and C2 over DNS.', severity: 'Info' },
      { id: 770, name: 'DNS Resolution Failure', description: 'DNS client failed to resolve a name. Check the queried name — excessive NXDOMAIN responses may indicate DNS-based C2 or DGA malware.', severity: 'Warning' },
      { id: 771, name: 'DNS Query Response', description: 'DNS client received a query response. Analytical log variant.', severity: 'Info' },
      { id: 1014, name: 'DNS Name Resolution Timeout', description: 'Name resolution for the specified host timed out. Check for DNS server connectivity issues.', severity: 'Warning' },
      { id: 50000, name: 'DHCP Server Authorized', description: 'The DHCP server was authorized in Active Directory.', severity: 'Info' },
      { id: 50001, name: 'DHCP Server Unauthorized', description: 'The DHCP server is not authorized in Active Directory. May cause network disruption.', severity: 'Critical' },
      { id: 50004, name: 'DHCP Server Rogue Detected', description: 'A rogue DHCP server was detected on the network. Rogue DHCP servers can redirect traffic for man-in-the-middle attacks.', severity: 'Critical' },
    ],
  },
  {
    category: 'Disk & Hardware',
    log: 'System',
    events: [
      { id: 7, name: 'Disk Error (Bad Block)', description: 'The device has a bad block. Indicates a failing disk — back up immediately and plan replacement. Source: Disk.', severity: 'Critical' },
      { id: 11, name: 'Driver: Controller Error', description: 'The driver detected a controller error. May indicate failing disk or cable. Source: Disk or specific driver.', severity: 'Error' },
      { id: 15, name: 'Device Not Ready', description: 'The device is not ready. Disk or device may be failing or disconnected.', severity: 'Warning' },
      { id: 51, name: 'Disk Warning (Paging)', description: 'An error was detected on device during paging operation. Often precedes disk failure. Source: Disk.', severity: 'Warning' },
      { id: 55, name: 'File System Corruption', description: 'The file system structure on disk is corrupt and unusable. Run CHKDSK immediately. Source: NTFS.', severity: 'Critical' },
      { id: 98, name: 'NTFS Volume Dirty', description: 'The volume is dirty and requires CHKDSK to be run. May indicate improper shutdown or disk errors.', severity: 'Warning' },
      { id: 157, name: 'Disk Surprise Removed', description: 'A disk was surprise removed without safe ejection. Potential data loss.', severity: 'Warning' },
      { id: 129, name: 'Hard Reset Issued to Disk', description: 'A reset to the device was issued. Often indicates the disk stopped responding — early failure warning.', severity: 'Error' },
    ],
  },
  {
    category: 'LAPS',
    log: 'Microsoft-Windows-LAPS/Operational',
    events: [
      { id: 10018, name: 'LAPS Password Updated Successfully', description: 'Windows LAPS successfully updated the managed account password. Includes account name and expiration time.', severity: 'Info' },
      { id: 10019, name: 'LAPS Password Update Failed', description: 'Windows LAPS failed to update the managed account password. Investigate — local admin password may be stale.', severity: 'Error' },
      { id: 10020, name: 'LAPS Password Read', description: 'The LAPS-managed password was read from Active Directory. Check who read it and from where — should only be authorized admins.', severity: 'Warning' },
      { id: 10021, name: 'LAPS Policy Processing Started', description: 'Windows LAPS started processing policy.', severity: 'Info' },
      { id: 10022, name: 'LAPS Policy Processing Completed', description: 'Windows LAPS completed processing policy.', severity: 'Info' },
      { id: 10023, name: 'LAPS Configuration Not Found', description: 'Windows LAPS could not find its configuration in Active Directory. LAPS policy may not be applied to this OU.', severity: 'Warning' },
      { id: 10024, name: 'LAPS Legacy Mode Detected', description: 'Windows LAPS detected legacy (non-Windows LAPS) configuration. Consider migrating to Windows LAPS.', severity: 'Info' },
    ],
  },
  {
    category: 'Wireless & Network Location',
    log: 'Microsoft-Windows-WLAN-AutoConfig/Operational',
    events: [
      { id: 8001, name: 'Wireless Connection Successful', description: 'WLAN AutoConfig service connected to a wireless network. Includes SSID and authentication type.', severity: 'Info' },
      { id: 8002, name: 'Wireless Connection Failed', description: 'WLAN AutoConfig service failed to connect to a wireless network. Check failure reason.', severity: 'Warning' },
      { id: 8003, name: 'Wireless Disconnected', description: 'WLAN AutoConfig service disconnected from a wireless network. Includes reason code.', severity: 'Info' },
      { id: 11000, name: 'Wireless Security Started', description: 'Wireless LAN adapter security started. Includes SSID and BSS type.', severity: 'Info' },
      { id: 11001, name: 'Wireless Security Succeeded', description: 'Wireless LAN adapter security succeeded (authentication complete).', severity: 'Info' },
      { id: 11002, name: 'Wireless Security Failed', description: 'Wireless LAN adapter security failed. May indicate wrong credentials, rogue AP, or 802.1X issues.', severity: 'Warning' },
      { id: 11004, name: 'Wireless Roaming Started', description: 'Wireless LAN adapter started roaming to a new access point.', severity: 'Info' },
      { id: 11005, name: 'Wireless Roaming Succeeded', description: 'Wireless LAN adapter successfully roamed to a new access point.', severity: 'Info' },
      { id: 11006, name: 'Wireless Roaming Failed', description: 'Wireless LAN adapter failed to roam. Connection may drop.', severity: 'Warning' },
    ],
  },
];
