export const portCategories: {
  category: string
  ports: {
    port: number | string
    protocol: 'TCP' | 'UDP' | 'TCP/UDP'
    service: string
    description: string
    dangerous: boolean
    notes?: string
  }[]
}[] = [
  {
    category: 'Web & HTTP',
    ports: [
      { port: 80, protocol: 'TCP', service: 'HTTP', description: 'Unencrypted web traffic. Should be redirected to HTTPS in all modern deployments.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'HTTPS', description: 'Encrypted web traffic over TLS/SSL. Standard for all web services.', dangerous: false },
      { port: 8080, protocol: 'TCP', service: 'HTTP Alternate', description: 'Common alternate HTTP port used by web proxies, dev servers, and some admin interfaces.', dangerous: false },
      { port: 8443, protocol: 'TCP', service: 'HTTPS Alternate', description: 'Alternate HTTPS port commonly used by Tomcat, Proxmox, pfSense, and other web UIs.', dangerous: false },
      { port: 8888, protocol: 'TCP', service: 'HTTP Alt / Jupyter', description: 'Common alternate web port used by Jupyter notebooks and various applications.', dangerous: false },
      { port: 3000, protocol: 'TCP', service: 'Dev HTTP / Grafana', description: 'Common development server port used by Node.js, React, and Grafana.', dangerous: false },
      { port: 9090, protocol: 'TCP', service: 'HTTP Alt / Prometheus', description: 'Used by Prometheus, Cockpit, and various web admin interfaces.', dangerous: false },
      { port: 8008, protocol: 'TCP', service: 'HTTP Alternate', description: 'Alternate HTTP port used by Google Chromecast, Home Assistant, and some IoT devices.', dangerous: false },
      { port: 8081, protocol: 'TCP', service: 'HTTP Alternate', description: 'Alternate HTTP port used by many management interfaces, Nexus Repository, and proxies.', dangerous: false },
      { port: 8123, protocol: 'TCP', service: 'Home Assistant', description: 'Home Assistant web interface default port.', dangerous: false },
      { port: 9443, protocol: 'TCP', service: 'HTTPS Alternate', description: 'Alternate HTTPS port used by some management interfaces.', dangerous: false },
      { port: 4443, protocol: 'TCP', service: 'HTTPS Alternate', description: 'Alternate HTTPS port used by Cisco AnyConnect, some reverse proxies, and admin consoles.', dangerous: false },
      { port: 5000, protocol: 'TCP', service: 'Flask / Dev HTTP', description: 'Default Flask development server port. Also used by Docker Registry and some admin UIs.', dangerous: false },
      { port: 7000, protocol: 'TCP', service: 'HTTP Alt / Cassandra', description: 'Used by some web services and Cassandra inter-node communication.', dangerous: false },
      { port: 7001, protocol: 'TCP', service: 'Oracle WebLogic', description: 'Oracle WebLogic Server HTTP port. Has had multiple critical RCE CVEs.', dangerous: true, notes: 'Restrict to application servers. WebLogic has a history of critical deserialization vulnerabilities.' },
      { port: 7002, protocol: 'TCP', service: 'Oracle WebLogic HTTPS', description: 'Oracle WebLogic Server HTTPS port.', dangerous: true, notes: 'Restrict to application servers. Patch aggressively.' },
      { port: 4848, protocol: 'TCP', service: 'GlassFish Admin', description: 'Oracle GlassFish application server admin console.', dangerous: true, notes: 'Restrict to management networks. Known default credential issues.' },
      { port: 9000, protocol: 'TCP', service: 'SonarQube / PHP-FPM', description: 'SonarQube web interface and PHP-FPM FastCGI port.', dangerous: false },
      { port: 2368, protocol: 'TCP', service: 'Ghost CMS', description: 'Ghost blogging platform default port.', dangerous: false },
      { port: 8069, protocol: 'TCP', service: 'Odoo', description: 'Odoo ERP/CRM web interface default port.', dangerous: false },
      { port: 3001, protocol: 'TCP', service: 'Dev HTTP Alt', description: 'Common alternate development server port.', dangerous: false },
      { port: 8161, protocol: 'TCP', service: 'ActiveMQ Console', description: 'Apache ActiveMQ web admin console.', dangerous: true, notes: 'Default credentials admin/admin. Restrict to management networks. Multiple critical RCE CVEs.' },
      { port: 8880, protocol: 'TCP', service: 'HTTP Alt / IBM', description: 'IBM HTTP Server alternate port and various web applications.', dangerous: false },
    ],
  },
  {
    category: 'Email',
    ports: [
      { port: 25, protocol: 'TCP', service: 'SMTP', description: 'Simple Mail Transfer Protocol. Server-to-server email relay. Often blocked outbound by ISPs to prevent spam.', dangerous: true, notes: 'Commonly exploited for open relay and spam. Block outbound on end-user networks.' },
      { port: 465, protocol: 'TCP', service: 'SMTPS', description: 'SMTP over SSL. Legacy implicit TLS port for email submission. Deprecated in favor of 587 but still widely used.', dangerous: false },
      { port: 587, protocol: 'TCP', service: 'SMTP Submission', description: 'Modern email submission port. Requires authentication and STARTTLS. Use this for outbound email from clients and applications.', dangerous: false },
      { port: 2525, protocol: 'TCP', service: 'SMTP Alternate', description: 'Alternate SMTP port used by cloud email services (SendGrid, Mailgun, Postmark) when 587 is blocked.', dangerous: false },
      { port: 110, protocol: 'TCP', service: 'POP3', description: 'Post Office Protocol v3. Downloads email from server. Unencrypted — use 995 instead.', dangerous: true, notes: 'Transmits credentials in plaintext. Disable in favor of IMAPS.' },
      { port: 995, protocol: 'TCP', service: 'POP3S', description: 'POP3 over SSL/TLS. Encrypted email retrieval.', dangerous: false },
      { port: 143, protocol: 'TCP', service: 'IMAP', description: 'Internet Message Access Protocol. Syncs email from server. Unencrypted — use 993 instead.', dangerous: true, notes: 'Transmits credentials in plaintext. Disable in favor of IMAPS.' },
      { port: 993, protocol: 'TCP', service: 'IMAPS', description: 'IMAP over SSL/TLS. Encrypted email sync. Standard for modern email clients.', dangerous: false },
      { port: 366, protocol: 'TCP', service: 'ODMR', description: 'On-Demand Mail Relay. Allows a client to trigger mail delivery.', dangerous: false },
      { port: 24, protocol: 'TCP', service: 'SMTP Alternate (legacy)', description: 'Legacy SMTP alternate port used by some mail servers.', dangerous: false },
    ],
  },
  {
    category: 'File Transfer & Storage',
    ports: [
      { port: 20, protocol: 'TCP', service: 'FTP Data', description: 'FTP data transfer channel (active mode). Unencrypted.', dangerous: true, notes: 'Transmits data and credentials in plaintext. Replace with SFTP (22) or FTPS (990).' },
      { port: 21, protocol: 'TCP', service: 'FTP Control', description: 'FTP command channel. Unencrypted.', dangerous: true, notes: 'Transmits credentials in plaintext. Replace with SFTP (22) or FTPS (990).' },
      { port: 22, protocol: 'TCP', service: 'SSH / SFTP / SCP', description: 'Secure Shell, Secure File Transfer Protocol, and Secure Copy. Encrypted remote access and file transfer.', dangerous: false, notes: 'Change to non-standard port and restrict to known IPs if internet-facing.' },
      { port: 69, protocol: 'UDP', service: 'TFTP', description: 'Trivial File Transfer Protocol. No authentication. Used for PXE boot and network device firmware updates.', dangerous: true, notes: 'No authentication or encryption. Restrict to management VLANs only.' },
      { port: 990, protocol: 'TCP', service: 'FTPS', description: 'FTP over implicit TLS. Encrypted FTP.', dangerous: false },
      { port: 989, protocol: 'TCP', service: 'FTPS Data', description: 'FTPS data channel over implicit TLS.', dangerous: false },
      { port: 2049, protocol: 'TCP/UDP', service: 'NFS', description: 'Network File System. Unix/Linux file sharing.', dangerous: true, notes: 'Restrict to trusted hosts. Use NFSv4 with Kerberos for authentication.' },
      { port: 445, protocol: 'TCP', service: 'SMB / CIFS', description: 'Server Message Block. Windows file sharing, AD replication, and remote management.', dangerous: true, notes: 'Never expose to internet. Enable SMB signing. Block SMBv1.' },
      { port: 139, protocol: 'TCP', service: 'NetBIOS Session / SMB', description: 'Legacy SMB over NetBIOS. Replaced by port 445.', dangerous: true, notes: 'Block externally. Disable NetBIOS over TCP/IP.' },
      { port: 873, protocol: 'TCP', service: 'rsync', description: 'rsync file synchronization daemon. Unencrypted when used directly (not over SSH).', dangerous: true, notes: 'Run over SSH tunnel or restrict to trusted hosts. Anonymous rsync exposes all synced data.' },
      { port: 548, protocol: 'TCP', service: 'AFP', description: 'Apple Filing Protocol. Apple network file sharing. Legacy — replaced by SMB in modern macOS.', dangerous: false, notes: 'Disable if not using Apple-specific file sharing.' },
      { port: 3260, protocol: 'TCP', service: 'iSCSI', description: 'iSCSI storage protocol. Block-level storage over TCP/IP.', dangerous: true, notes: 'Restrict to dedicated storage VLAN. Use CHAP authentication. No encryption by default.' },
      { port: 10000, protocol: 'TCP', service: 'Webmin', description: 'Webmin web-based system administration interface.', dangerous: true, notes: 'Restrict to management network. Has had multiple critical CVEs.' },
    ],
  },
  {
    category: 'Remote Access & Desktop',
    ports: [
      { port: 22, protocol: 'TCP', service: 'SSH', description: 'Secure Shell. Encrypted remote terminal access. Standard for Linux/Unix administration.', dangerous: false, notes: 'Restrict to known IPs. Disable password auth and use key-based auth.' },
      { port: 23, protocol: 'TCP', service: 'Telnet', description: 'Unencrypted remote terminal. Transmits everything including credentials in plaintext.', dangerous: true, notes: 'Never use. Replace with SSH (22) in all environments.' },
      { port: 3389, protocol: 'TCP', service: 'RDP', description: 'Remote Desktop Protocol. Windows remote desktop access. High-value target for attackers.', dangerous: true, notes: 'Never expose directly to internet. Use VPN or RD Gateway. Enable NLA and restrict by IP.' },
      { port: 5900, protocol: 'TCP', service: 'VNC', description: 'Virtual Network Computing. Remote desktop for non-Windows systems. Unencrypted by default.', dangerous: true, notes: 'Tunnel through SSH or VPN. Never expose directly to internet.' },
      { port: 5901, protocol: 'TCP', service: 'VNC Display 1', description: 'VNC second display session (display :1). Each subsequent display increments by 1.', dangerous: true, notes: 'Same risks as VNC port 5900.' },
      { port: 5985, protocol: 'TCP', service: 'WinRM HTTP', description: 'Windows Remote Management over HTTP. Used by PowerShell Remoting.', dangerous: true, notes: 'Unencrypted. Use WinRM HTTPS (5986) or restrict to management networks only.' },
      { port: 5986, protocol: 'TCP', service: 'WinRM HTTPS', description: 'Windows Remote Management over HTTPS. Encrypted PowerShell remoting.', dangerous: false },
      { port: 2222, protocol: 'TCP', service: 'SSH Alternate', description: 'Common alternate SSH port used to reduce automated scanning noise.', dangerous: false },
      { port: 4899, protocol: 'TCP', service: 'Radmin', description: 'Remote Administrator (Radmin) remote control software.', dangerous: true, notes: 'Restrict to management networks. Has been exploited in ransomware attacks.' },
      { port: 5938, protocol: 'TCP', service: 'TeamViewer', description: 'TeamViewer remote access and support software primary port.', dangerous: false, notes: 'Monitor usage. Commonly abused by threat actors after initial access. Consider allowing only from approved endpoints.' },
      { port: 7070, protocol: 'TCP', service: 'AnyDesk', description: 'AnyDesk remote access software primary communication port.', dangerous: false, notes: 'Monitor usage. Like TeamViewer, commonly abused post-compromise for persistence.' },
      { port: 443, protocol: 'TCP', service: 'TeamViewer / AnyDesk Fallback', description: 'Both TeamViewer and AnyDesk fall back to HTTPS/443 if primary ports are blocked.', dangerous: false, notes: 'Difficult to block without disrupting normal HTTPS traffic.' },
      { port: 8200, protocol: 'TCP', service: 'GoToMyPC / Vault', description: 'GoToMyPC remote access and HashiCorp Vault API port.', dangerous: false },
      { port: 4001, protocol: 'TCP', service: 'NinjaRMM / LogMeIn Alt', description: 'LogMeIn alternate communication port.', dangerous: false },
      { port: 8900, protocol: 'TCP', service: 'Splashtop', description: 'Splashtop remote access software relay port.', dangerous: false },
      { port: 631, protocol: 'TCP', service: 'IPP / CUPS', description: 'Internet Printing Protocol. Used by CUPS on Linux/Mac and Windows print services.', dangerous: false },
    ],
  },
  {
    category: 'DNS & Network Services',
    ports: [
      { port: 53, protocol: 'TCP/UDP', service: 'DNS', description: 'Domain Name System. UDP for queries, TCP for zone transfers and large responses.', dangerous: false, notes: 'Restrict zone transfers (TCP 53) to authorized secondary DNS servers only.' },
      { port: 67, protocol: 'UDP', service: 'DHCP Server', description: 'Dynamic Host Configuration Protocol server. Assigns IP addresses to clients.', dangerous: false },
      { port: 68, protocol: 'UDP', service: 'DHCP Client', description: 'DHCP client port. Receives IP configuration from DHCP server.', dangerous: false },
      { port: 123, protocol: 'UDP', service: 'NTP', description: 'Network Time Protocol. Time synchronization. Critical for Kerberos and certificate validity.', dangerous: false, notes: 'Clock skew over 5 minutes breaks Kerberos authentication. Used in amplification DDoS.' },
      { port: 161, protocol: 'UDP', service: 'SNMP', description: 'Simple Network Management Protocol. Network device monitoring and management.', dangerous: true, notes: 'Use SNMPv3 with authentication and encryption. SNMPv1/v2c use community strings (plaintext passwords).' },
      { port: 162, protocol: 'UDP', service: 'SNMP Trap', description: 'SNMP trap receiver. Devices send unsolicited notifications to management systems.', dangerous: false },
      { port: 5353, protocol: 'UDP', service: 'mDNS / Bonjour', description: 'Multicast DNS. Zero-configuration name resolution on local networks.', dangerous: true, notes: 'Can leak hostnames and service information. Disable on corporate networks or restrict to specific VLANs.' },
      { port: 5355, protocol: 'UDP', service: 'LLMNR', description: 'Link-Local Multicast Name Resolution. Windows name resolution fallback when DNS fails.', dangerous: true, notes: 'Disable via GPO. Commonly exploited by Responder for credential capture on internal networks.' },
      { port: 137, protocol: 'UDP', service: 'NetBIOS Name Service', description: 'NetBIOS name service. Legacy Windows name resolution.', dangerous: true, notes: 'Disable NetBIOS over TCP/IP. Exploited by Responder and other MITM tools.' },
      { port: 138, protocol: 'UDP', service: 'NetBIOS Datagram', description: 'NetBIOS datagram service. Used for Windows browsing and legacy SMB.', dangerous: true, notes: 'Disable with NetBIOS. Not needed in modern networks.' },
      { port: 853, protocol: 'TCP', service: 'DNS over TLS (DoT)', description: 'DNS over TLS. Encrypted DNS queries to prevent eavesdropping and tampering.', dangerous: false },
      { port: 784, protocol: 'UDP', service: 'DNS over QUIC', description: 'DNS over QUIC protocol. Encrypted DNS transport.', dangerous: false },
      { port: 42, protocol: 'TCP/UDP', service: 'WINS', description: 'Windows Internet Name Service. Legacy NetBIOS name resolution for Windows.', dangerous: false, notes: 'Legacy. Disable if no legacy Windows XP/2003 systems remain.' },
      { port: 546, protocol: 'UDP', service: 'DHCPv6 Client', description: 'DHCPv6 client port for IPv6 address assignment.', dangerous: false },
      { port: 547, protocol: 'UDP', service: 'DHCPv6 Server', description: 'DHCPv6 server port for IPv6 address assignment.', dangerous: false },
      { port: 8853, protocol: 'TCP', service: 'DNS over HTTPS Alt', description: 'Alternate DoH port used by some resolver implementations.', dangerous: false },
    ],
  },
  {
    category: 'Windows & Active Directory',
    ports: [
      { port: 88, protocol: 'TCP/UDP', service: 'Kerberos', description: 'Kerberos authentication. Core of Active Directory authentication.', dangerous: false },
      { port: 135, protocol: 'TCP', service: 'RPC Endpoint Mapper', description: 'Microsoft RPC endpoint mapper. Required for AD replication, WMI, and DCOM.', dangerous: true, notes: 'Restrict to management networks. Block from internet.' },
      { port: 389, protocol: 'TCP/UDP', service: 'LDAP', description: 'Lightweight Directory Access Protocol. Unencrypted AD queries and authentication.', dangerous: true, notes: 'Use LDAPS (636) for encrypted LDAP. Plain LDAP transmits credentials in cleartext.' },
      { port: 636, protocol: 'TCP', service: 'LDAPS', description: 'LDAP over SSL/TLS. Encrypted Active Directory queries.', dangerous: false },
      { port: 3268, protocol: 'TCP', service: 'Global Catalog LDAP', description: 'Active Directory Global Catalog LDAP. Used to query all objects across all domains in a forest.', dangerous: false },
      { port: 3269, protocol: 'TCP', service: 'Global Catalog LDAPS', description: 'Global Catalog LDAP over SSL. Encrypted cross-domain AD queries.', dangerous: false },
      { port: 464, protocol: 'TCP/UDP', service: 'Kerberos Password Change', description: 'Kerberos password change protocol (kpasswd). Used for AD password changes.', dangerous: false },
      { port: 593, protocol: 'TCP', service: 'RPC over HTTP', description: 'RPC over HTTP. Used by Outlook Anywhere and some Exchange services.', dangerous: false },
      { port: 9389, protocol: 'TCP', service: 'AD Web Services', description: 'Active Directory Web Services. Used by Active Directory Administrative Center and PowerShell AD module.', dangerous: false },
      { port: 5722, protocol: 'TCP', service: 'DFSR', description: 'Distributed File System Replication. Used for SYSVOL replication between domain controllers in 2008+.', dangerous: false },
      { port: 445, protocol: 'TCP', service: 'SMB / AD Replication', description: 'SMB also carries AD replication traffic, SYSVOL, NETLOGON access, and GPO application.', dangerous: true, notes: 'Must be open between DCs and from DCs to clients. Block SMBv1.' },
      { port: 49152, protocol: 'TCP', service: 'RPC Dynamic Ports', description: 'Start of Windows RPC dynamic port range (49152–65535). AD replication, WMI, and DCOM negotiate ports here.', dangerous: false, notes: 'Can be restricted to a smaller range via registry for firewall management.' },
      { port: 3702, protocol: 'UDP', service: 'WS-Discovery', description: 'Web Services Dynamic Discovery used by Active Directory and various Windows services.', dangerous: false },
      { port: 2535, protocol: 'UDP', service: 'MADCAP', description: 'Multicast Address Dynamic Client Allocation Protocol. Used for multicast address management.', dangerous: false },
    ],
  },
  {
    category: 'Database',
    ports: [
      { port: 1433, protocol: 'TCP', service: 'MS SQL Server', description: 'Microsoft SQL Server. Never expose directly to internet.', dangerous: true, notes: 'Restrict to application servers only. Use Windows auth over SQL auth where possible.' },
      { port: 1434, protocol: 'UDP', service: 'MS SQL Browser', description: 'SQL Server Browser service. Returns SQL instance information to clients.', dangerous: true, notes: 'Disable if using fixed port. Leaks SQL instance names and versions.' },
      { port: 3306, protocol: 'TCP', service: 'MySQL / MariaDB', description: 'MySQL and MariaDB database server.', dangerous: true, notes: 'Restrict to localhost or application server. Never expose to internet.' },
      { port: 5432, protocol: 'TCP', service: 'PostgreSQL', description: 'PostgreSQL database server.', dangerous: true, notes: 'Restrict to localhost or application server. Never expose to internet.' },
      { port: 1521, protocol: 'TCP', service: 'Oracle DB', description: 'Oracle Database listener.', dangerous: true, notes: 'Restrict to application servers only.' },
      { port: 1630, protocol: 'TCP', service: 'Oracle DB Alt', description: 'Oracle Database alternate listener port.', dangerous: true, notes: 'Restrict to application servers only.' },
      { port: 27017, protocol: 'TCP', service: 'MongoDB', description: 'MongoDB database server. No authentication by default in older versions.', dangerous: true, notes: 'Bind to localhost only. Enable authentication. Many breaches from internet-exposed MongoDB.' },
      { port: 27018, protocol: 'TCP', service: 'MongoDB Shard', description: 'MongoDB shardsvr port for sharded cluster configuration.', dangerous: true, notes: 'Restrict to MongoDB cluster nodes only.' },
      { port: 27019, protocol: 'TCP', service: 'MongoDB Config', description: 'MongoDB configsvr port for config server replication.', dangerous: true, notes: 'Restrict to MongoDB cluster nodes only.' },
      { port: 6379, protocol: 'TCP', service: 'Redis', description: 'Redis in-memory data store. No authentication by default.', dangerous: true, notes: 'Bind to localhost or use requirepass. Internet-exposed Redis is a common breach vector.' },
      { port: 16379, protocol: 'TCP', service: 'Redis Cluster Bus', description: 'Redis Cluster inter-node communication bus. Port is always +10000 from client port.', dangerous: true, notes: 'Restrict to Redis cluster nodes only.' },
      { port: 5984, protocol: 'TCP', service: 'CouchDB', description: 'Apache CouchDB HTTP API.', dangerous: true, notes: 'Restrict to localhost. Default admin party mode (no auth) in older versions.' },
      { port: 9042, protocol: 'TCP', service: 'Cassandra CQL', description: 'Apache Cassandra CQL native transport port.', dangerous: true, notes: 'Restrict to cluster nodes and application servers.' },
      { port: 9160, protocol: 'TCP', service: 'Cassandra Thrift', description: 'Apache Cassandra legacy Thrift API port.', dangerous: true, notes: 'Disable Thrift API. Restrict to application servers.' },
      { port: 7474, protocol: 'TCP', service: 'Neo4j HTTP', description: 'Neo4j graph database HTTP API.', dangerous: true, notes: 'Restrict access. Default credentials have been commonly left unchanged.' },
      { port: 7473, protocol: 'TCP', service: 'Neo4j HTTPS', description: 'Neo4j graph database HTTPS API.', dangerous: false },
      { port: 7687, protocol: 'TCP', service: 'Neo4j Bolt', description: 'Neo4j Bolt protocol for driver connections.', dangerous: true, notes: 'Restrict to application servers.' },
      { port: 11211, protocol: 'TCP/UDP', service: 'Memcached', description: 'Memcached distributed memory caching. No authentication.', dangerous: true, notes: 'Bind to localhost only. No encryption or authentication. Used in massive UDP amplification DDoS attacks.' },
      { port: 8529, protocol: 'TCP', service: 'ArangoDB', description: 'ArangoDB multi-model database HTTP API.', dangerous: true, notes: 'Restrict to application servers. Disable web interface in production.' },
      { port: 9200, protocol: 'TCP', service: 'Elasticsearch HTTP', description: 'Elasticsearch REST API. No authentication in older versions.', dangerous: true, notes: 'Restrict to localhost or monitoring network. Many breaches from internet-exposed Elasticsearch.' },
      { port: 9300, protocol: 'TCP', service: 'Elasticsearch Transport', description: 'Elasticsearch node-to-node transport protocol.', dangerous: true, notes: 'Restrict to Elasticsearch cluster nodes only.' },
      { port: 26257, protocol: 'TCP', service: 'CockroachDB', description: 'CockroachDB distributed SQL database port.', dangerous: true, notes: 'Restrict to cluster nodes and application servers.' },
      { port: 8123, protocol: 'TCP', service: 'ClickHouse HTTP', description: 'ClickHouse OLAP database HTTP interface.', dangerous: true, notes: 'Restrict to application servers.' },
      { port: 9000, protocol: 'TCP', service: 'ClickHouse Native', description: 'ClickHouse native protocol port.', dangerous: true, notes: 'Restrict to application servers.' },
      { port: 28015, protocol: 'TCP', service: 'RethinkDB', description: 'RethinkDB client driver port.', dangerous: true, notes: 'Restrict to application servers.' },
      { port: 29015, protocol: 'TCP', service: 'RethinkDB Cluster', description: 'RethinkDB cluster communication port.', dangerous: true, notes: 'Restrict to cluster nodes only.' },
    ],
  },
  {
    category: 'VPN & Tunneling',
    ports: [
      { port: 1194, protocol: 'UDP', service: 'OpenVPN', description: 'OpenVPN default port. SSL/TLS-based VPN.', dangerous: false },
      { port: 1723, protocol: 'TCP', service: 'PPTP', description: 'Point-to-Point Tunneling Protocol. Legacy VPN protocol with known cryptographic weaknesses.', dangerous: true, notes: 'Deprecated. MS-CHAPv2 is broken. Use IKEv2, OpenVPN, or WireGuard instead.' },
      { port: 500, protocol: 'UDP', service: 'IKE / IPSec', description: 'Internet Key Exchange. Used for IPSec VPN tunnel establishment.', dangerous: false },
      { port: 4500, protocol: 'UDP', service: 'IPSec NAT-T', description: 'IPSec NAT Traversal. Allows IPSec through NAT devices.', dangerous: false },
      { port: 1701, protocol: 'UDP', service: 'L2TP', description: 'Layer 2 Tunneling Protocol. Used with IPSec for L2TP/IPSec VPN.', dangerous: false },
      { port: 51820, protocol: 'UDP', service: 'WireGuard', description: 'WireGuard VPN. Modern, fast, and cryptographically sound VPN protocol.', dangerous: false },
      { port: 1080, protocol: 'TCP', service: 'SOCKS Proxy', description: 'SOCKS proxy protocol. Used by many applications for proxied connections.', dangerous: true, notes: 'Open SOCKS proxies are commonly abused for anonymization and traffic routing.' },
      { port: 8388, protocol: 'TCP', service: 'Shadowsocks', description: 'Shadowsocks proxy protocol. Encrypted proxy designed to bypass censorship.', dangerous: false, notes: 'Also commonly used to obfuscate C2 traffic.' },
      { port: 4433, protocol: 'TCP', service: 'Ivanti / Pulse Secure VPN', description: 'Ivanti (formerly Pulse Secure) SSL VPN port. Multiple critical CVEs in recent years.', dangerous: true, notes: 'Patch immediately. CVE-2019-11510 and others allowed unauthenticated RCE.' },
      { port: 10443, protocol: 'TCP', service: 'FortiGate SSL VPN Alt', description: 'FortiGate SSL VPN alternate HTTPS port.', dangerous: false, notes: 'Keep patched. FortiGate SSL VPN has had multiple critical CVEs.' },
      { port: 41641, protocol: 'UDP', service: 'Tailscale', description: 'Tailscale WireGuard-based VPN mesh network. Uses UDP with DERP relay fallback.', dangerous: false },
      { port: 9993, protocol: 'UDP', service: 'ZeroTier', description: 'ZeroTier virtual network overlay. Peer-to-peer encrypted networking.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Cisco AnyConnect / SSL VPN', description: 'Cisco AnyConnect and most SSL VPN products use HTTPS/443 for client connections.', dangerous: false },
      { port: 4501, protocol: 'UDP', service: 'GlobalProtect / Palo Alto', description: 'Palo Alto GlobalProtect VPN IPSec port.', dangerous: false },
      { port: 3128, protocol: 'TCP', service: 'Squid HTTP Proxy', description: 'Common HTTP proxy port used by Squid and other proxies.', dangerous: false, notes: 'Open proxies can be abused for anonymization. Restrict to internal use.' },
    ],
  },
  {
    category: 'VoIP & Unified Communications',
    ports: [
      { port: 5060, protocol: 'TCP/UDP', service: 'SIP', description: 'Session Initiation Protocol. VoIP call signaling. Unencrypted.', dangerous: true, notes: 'Commonly scanned and attacked. Use SIPS (5061) or restrict to SBC/carrier IP ranges.' },
      { port: 5061, protocol: 'TCP', service: 'SIPS', description: 'SIP over TLS. Encrypted VoIP signaling.', dangerous: false },
      { port: '10000-20000', protocol: 'UDP', service: 'RTP Media', description: 'Real-time Transport Protocol. Carries actual audio/video streams for VoIP.', dangerous: false },
      { port: '16384-32767', protocol: 'UDP', service: 'RTP Media (Cisco)', description: 'Cisco RTP media port range for VoIP audio streams.', dangerous: false },
      { port: 1720, protocol: 'TCP', service: 'H.323', description: 'H.323 VoIP call signaling. Legacy video conferencing and VoIP standard.', dangerous: false },
      { port: 3478, protocol: 'TCP/UDP', service: 'STUN / Teams Media', description: 'STUN protocol for NAT traversal. Used by Microsoft Teams, WebRTC, and VoIP.', dangerous: false },
      { port: 3479, protocol: 'TCP/UDP', service: 'Teams Media', description: 'Microsoft Teams media transport port.', dangerous: false },
      { port: 3480, protocol: 'TCP/UDP', service: 'Teams Media', description: 'Microsoft Teams media transport port.', dangerous: false },
      { port: 3481, protocol: 'TCP/UDP', service: 'Teams Media', description: 'Microsoft Teams media transport port.', dangerous: false },
      { port: 19302, protocol: 'UDP', service: 'Google STUN', description: 'Google STUN server for WebRTC NAT traversal (stun.l.google.com).', dangerous: false },
      { port: 5349, protocol: 'TCP', service: 'STUN/TURN over TLS', description: 'STUN and TURN over TLS for WebRTC and VoIP NAT traversal.', dangerous: false },
      { port: 8801, protocol: 'TCP/UDP', service: 'Zoom', description: 'Zoom video conferencing primary port.', dangerous: false },
      { port: 8802, protocol: 'TCP/UDP', service: 'Zoom Alternate', description: 'Zoom video conferencing alternate port.', dangerous: false },
      { port: '8801-8802', protocol: 'UDP', service: 'Zoom Media', description: 'Zoom UDP media transport range.', dangerous: false },
      { port: 9000, protocol: 'TCP', service: 'Cisco Unified CM / Webex', description: 'Cisco Unified Communications Manager and Webex calling port.', dangerous: false },
      { port: 2000, protocol: 'TCP', service: 'Cisco SCCP', description: 'Cisco Skinny Client Control Protocol (SCCP). Used by Cisco IP phones.', dangerous: false },
      { port: 2443, protocol: 'TCP', service: 'Webex', description: 'Cisco Webex HTTPS alternate port for meeting connectivity.', dangerous: false },
      { port: 5004, protocol: 'UDP', service: 'SRTP', description: 'Secure Real-time Transport Protocol. Encrypted media transport for VoIP.', dangerous: false },
    ],
  },
  {
    category: 'RMM & MSP Tools',
    ports: [
      { port: 5721, protocol: 'TCP', service: 'Kaseya VSA Agent', description: 'Kaseya VSA agent communication port. Used by Kaseya RMM agents to communicate with VSA server.', dangerous: false, notes: 'Restrict to Kaseya VSA server IP. Exploited in 2021 ransomware attack (CVE-2021-30116).' },
      { port: 443, protocol: 'TCP', service: 'Kaseya / ConnectWise HTTPS', description: 'Most modern RMM tools communicate over HTTPS/443 to cloud endpoints.', dangerous: false },
      { port: 8041, protocol: 'TCP', service: 'ConnectWise Automate', description: 'ConnectWise Automate (LabTech) agent communication port.', dangerous: false },
      { port: 65000, protocol: 'TCP', service: 'Datto RMM', description: 'Datto RMM agent communication port.', dangerous: false },
      { port: 8200, protocol: 'TCP', service: 'Datto RMM Alt', description: 'Datto RMM alternate agent port.', dangerous: false },
      { port: 4343, protocol: 'TCP', service: 'N-able N-central', description: 'N-able N-central agent communication port.', dangerous: false },
      { port: 10001, protocol: 'TCP', service: 'NinjaRMM', description: 'NinjaRMM agent communication port.', dangerous: false },
      { port: 6543, protocol: 'TCP', service: 'Atera', description: 'Atera RMM agent communication port.', dangerous: false },
      { port: 5000, protocol: 'TCP', service: 'Syncro RMM', description: 'Syncro RMM platform communication port.', dangerous: false },
      { port: 8040, protocol: 'TCP', service: 'ConnectWise Control', description: 'ConnectWise Control (ScreenConnect) relay port.', dangerous: false, notes: 'Restrict relay to authorized CW Control server. Has been abused in attacks.' },
      { port: 8041, protocol: 'TCP', service: 'ConnectWise Control Alt', description: 'ConnectWise Control alternate relay port.', dangerous: false },
      { port: 4422, protocol: 'TCP', service: 'N-able Take Control', description: 'N-able Take Control remote access agent port.', dangerous: false },
      { port: 80, protocol: 'TCP', service: 'Huntress / EDR Agent Fallback', description: 'Many endpoint agents fall back to HTTP/80 for initial communication if 443 fails.', dangerous: false },
    ],
  },
  {
    category: 'Backup & Recovery',
    ports: [
      { port: 9392, protocol: 'TCP', service: 'Veeam Backup', description: 'Veeam Backup & Replication server default management port.', dangerous: false },
      { port: 9401, protocol: 'TCP', service: 'Veeam Catalog', description: 'Veeam catalog service port.', dangerous: false },
      { port: '2500-5000', protocol: 'TCP', service: 'Veeam Data Transfer', description: 'Veeam data transfer port range between backup infrastructure components.', dangerous: false },
      { port: 10002, protocol: 'TCP', service: 'Veeam Mount Service', description: 'Veeam mount service for instant VM recovery.', dangerous: false },
      { port: 6160, protocol: 'TCP', service: 'Veeam Installer', description: 'Veeam automated deployment and installer service.', dangerous: false },
      { port: 6162, protocol: 'TCP', service: 'Veeam Data Mover', description: 'Veeam data mover service on backup repositories.', dangerous: false },
      { port: 9876, protocol: 'TCP', service: 'Acronis Agent', description: 'Acronis Cyber Protect / Backup agent communication port.', dangerous: false },
      { port: 44445, protocol: 'TCP', service: 'Acronis Management', description: 'Acronis management server communication port.', dangerous: false },
      { port: 55000, protocol: 'TCP', service: 'Datto BCDR', description: 'Datto BCDR (backup/continuity) device communication port.', dangerous: false },
      { port: 8882, protocol: 'TCP', service: 'Datto Agent', description: 'Datto backup agent port.', dangerous: false },
      { port: 6783, protocol: 'TCP', service: 'Zerto', description: 'Zerto replication engine port.', dangerous: false },
      { port: 4009, protocol: 'TCP', service: 'Commvault', description: 'Commvault data protection communication port.', dangerous: false },
      { port: 8400, protocol: 'TCP', service: 'Commvault Services', description: 'Commvault CommServe and MediaAgent communication.', dangerous: false },
      { port: 8403, protocol: 'TCP', service: 'Commvault Client', description: 'Commvault client communication port.', dangerous: false },
      { port: 10000, protocol: 'TCP', service: 'Barracuda Backup', description: 'Barracuda Backup appliance communication port.', dangerous: false },
      { port: 5120, protocol: 'TCP', service: 'Backup Exec Agent', description: 'Veritas Backup Exec agent communication port.', dangerous: false },
      { port: 6106, protocol: 'TCP', service: 'Backup Exec Server', description: 'Veritas Backup Exec server communication.', dangerous: false },
    ],
  },
  {
    category: 'Security, AV & EDR',
    ports: [
      { port: 443, protocol: 'TCP', service: 'CrowdStrike Falcon', description: 'CrowdStrike Falcon EDR agent communicates exclusively over HTTPS/443 to ts01-b.cloudsink.net and lfodown01-b.cloudsink.net.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'SentinelOne', description: 'SentinelOne EDR agent communicates over HTTPS/443 to management console.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Carbon Black / VMware EDR', description: 'VMware Carbon Black endpoint agent communicates over HTTPS/443.', dangerous: false },
      { port: 54443, protocol: 'TCP', service: 'Carbon Black Alt', description: 'Carbon Black alternate agent communication port.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Defender for Endpoint', description: 'Microsoft Defender for Endpoint communicates over HTTPS/443 to Microsoft cloud endpoints.', dangerous: false },
      { port: 8191, protocol: 'TCP', service: 'Sophos Management', description: 'Sophos Central / Sophos Enterprise Console management communication.', dangerous: false },
      { port: 8192, protocol: 'TCP', service: 'Sophos Client', description: 'Sophos endpoint client communication port.', dangerous: false },
      { port: 2967, protocol: 'TCP', service: 'Symantec SEP Manager', description: 'Symantec Endpoint Protection Manager (SEPM) agent heartbeat port.', dangerous: false },
      { port: 8014, protocol: 'TCP', service: 'Symantec SEP Alt', description: 'Symantec Endpoint Protection alternate communication port.', dangerous: false },
      { port: 4343, protocol: 'TCP', service: 'Trend Micro / N-able', description: 'Trend Micro OfficeScan/Apex One server port. Also used by N-able N-central.', dangerous: false },
      { port: 8834, protocol: 'TCP', service: 'Nessus / Tenable.sc', description: 'Nessus vulnerability scanner web interface and Tenable.sc communication.', dangerous: false },
      { port: 9390, protocol: 'TCP', service: 'OpenVAS / GVM', description: 'OpenVAS/Greenbone Vulnerability Manager service port.', dangerous: false },
      { port: 1514, protocol: 'TCP/UDP', service: 'Wazuh Agent', description: 'Wazuh/OSSEC SIEM agent to manager communication.', dangerous: false },
      { port: 1515, protocol: 'TCP', service: 'Wazuh Agent Registration', description: 'Wazuh agent registration port.', dangerous: false },
      { port: 55000, protocol: 'TCP', service: 'Wazuh API', description: 'Wazuh REST API for management and integrations.', dangerous: false },
      { port: 8200, protocol: 'TCP', service: 'HashiCorp Vault', description: 'HashiCorp Vault secrets management API port.', dangerous: false, notes: 'Restrict to management systems and applications requiring secret access.' },
      { port: 8201, protocol: 'TCP', service: 'HashiCorp Vault Cluster', description: 'HashiCorp Vault cluster communication port.', dangerous: false },
      { port: 4444, protocol: 'TCP', service: 'Metasploit Default', description: 'Default Metasploit reverse shell listener. Used by many exploits and malware for C2.', dangerous: true, notes: 'Block inbound/outbound. Traffic on this port is almost always malicious in production environments.' },
      { port: 31337, protocol: 'TCP', service: 'Back Orifice / Elite', description: 'Back Orifice legacy RAT port. Used by old-school malware.', dangerous: true, notes: 'Block. Any traffic on this port is suspicious.' },
      { port: 9001, protocol: 'TCP', service: 'Qualys Scanner', description: 'Qualys vulnerability scanner communication. Also used by Tor.', dangerous: false, notes: 'Verify legitimate Qualys traffic. Also used by Tor relays.' },
    ],
  },
  {
    category: 'Authentication & Identity',
    ports: [
      { port: 1812, protocol: 'UDP', service: 'RADIUS Auth', description: 'RADIUS authentication. Used for 802.1X, VPN, and Wi-Fi authentication.', dangerous: false },
      { port: 1813, protocol: 'UDP', service: 'RADIUS Accounting', description: 'RADIUS accounting. Logs authentication events.', dangerous: false },
      { port: 1645, protocol: 'UDP', service: 'RADIUS Auth (legacy)', description: 'Legacy RADIUS authentication port. Deprecated in favor of 1812.', dangerous: false },
      { port: 1646, protocol: 'UDP', service: 'RADIUS Accounting (legacy)', description: 'Legacy RADIUS accounting port. Deprecated in favor of 1813.', dangerous: false },
      { port: 49, protocol: 'TCP', service: 'TACACS+', description: 'Terminal Access Controller Access-Control System Plus. Network device AAA authentication.', dangerous: false, notes: 'Encrypts only the password by default. Use TACACS+ with full encryption enabled.' },
      { port: 443, protocol: 'TCP', service: 'SAML / OAuth / OIDC / Okta / Azure AD', description: 'Modern identity protocols and cloud IdP services (Okta, Azure AD, Google Workspace) all use HTTPS/443.', dangerous: false },
      { port: 389, protocol: 'TCP/UDP', service: 'LDAP Authentication', description: 'LDAP used for authentication by many applications. Transmits credentials in cleartext.', dangerous: true, notes: 'Always use LDAPS (636) for authentication. Many applications still default to plain LDAP.' },
      { port: 88, protocol: 'TCP/UDP', service: 'Kerberos', description: 'Kerberos v5 authentication. Required for AD SSO and service ticket issuance.', dangerous: false },
      { port: 636, protocol: 'TCP', service: 'LDAPS Authentication', description: 'Encrypted LDAP for authentication. Use this instead of 389 for all auth flows.', dangerous: false },
      { port: 7070, protocol: 'TCP', service: 'Duo Security', description: 'Duo Security MFA proxy communication port.', dangerous: false },
      { port: 8080, protocol: 'TCP', service: 'Duo Auth Proxy', description: 'Duo Authentication Proxy RADIUS/LDAP interface for on-premises MFA integration.', dangerous: false },
      { port: 4568, protocol: 'TCP', service: 'Duo Proxy Alt', description: 'Duo Authentication Proxy alternate port.', dangerous: false },
    ],
  },
  {
    category: 'Monitoring & Observability',
    ports: [
      { port: 514, protocol: 'UDP', service: 'Syslog', description: 'Syslog protocol. Unencrypted log forwarding to SIEM or syslog server.', dangerous: false, notes: 'Use syslog over TLS (6514) for sensitive log data.' },
      { port: 6514, protocol: 'TCP', service: 'Syslog TLS', description: 'Syslog over TLS. Encrypted log forwarding.', dangerous: false },
      { port: 9100, protocol: 'TCP', service: 'Prometheus Node Exporter', description: 'Prometheus Node Exporter metrics endpoint. Exposes system metrics.', dangerous: false },
      { port: 5601, protocol: 'TCP', service: 'Kibana', description: 'Kibana web UI for Elasticsearch. Restrict to management network.', dangerous: false },
      { port: 8086, protocol: 'TCP', service: 'InfluxDB HTTP', description: 'InfluxDB time series database HTTP API.', dangerous: false },
      { port: 8088, protocol: 'TCP', service: 'InfluxDB RPC', description: 'InfluxDB RPC service for backup and restore operations.', dangerous: false },
      { port: 8291, protocol: 'TCP', service: 'Winbox (MikroTik)', description: 'MikroTik Winbox management protocol.', dangerous: true, notes: 'Restrict to management VLAN. CVE-2018-14847 exploited this port.' },
      { port: 8728, protocol: 'TCP', service: 'MikroTik API', description: 'MikroTik RouterOS API. Unencrypted.', dangerous: true, notes: 'Use API-SSL (8729) instead. Restrict to management VLAN.' },
      { port: 8729, protocol: 'TCP', service: 'MikroTik API-SSL', description: 'MikroTik RouterOS API over SSL.', dangerous: false },
      { port: 8443, protocol: 'TCP', service: 'UniFi Controller HTTPS', description: 'Ubiquiti UniFi Network Controller HTTPS management port.', dangerous: false },
      { port: 3478, protocol: 'UDP', service: 'UniFi STUN', description: 'UniFi STUN port for device communication.', dangerous: false },
      { port: 10001, protocol: 'UDP', service: 'UniFi Device Discovery', description: 'UniFi device discovery protocol (AP discovery).', dangerous: false },
      { port: 8880, protocol: 'TCP', service: 'UniFi HTTP Portal', description: 'UniFi guest portal HTTP port.', dangerous: false },
      { port: 8843, protocol: 'TCP', service: 'UniFi HTTPS Portal', description: 'UniFi guest portal HTTPS port.', dangerous: false },
      { port: 6789, protocol: 'TCP', service: 'UniFi Throughput Test', description: 'UniFi mobile speed test port.', dangerous: false },
      { port: 5666, protocol: 'TCP', service: 'NRPE (Nagios)', description: 'Nagios Remote Plugin Executor. Allows Nagios to run checks on remote hosts.', dangerous: false, notes: 'Restrict to Nagios server IP. NRPE can execute arbitrary commands if misconfigured.' },
      { port: 12489, protocol: 'TCP', service: 'NSClient++ (Nagios)', description: 'NSClient++ Windows monitoring agent for Nagios/Check_MK.', dangerous: false },
      { port: 10050, protocol: 'TCP', service: 'Zabbix Agent', description: 'Zabbix monitoring agent. Zabbix server connects to this port on monitored hosts.', dangerous: false },
      { port: 10051, protocol: 'TCP', service: 'Zabbix Server', description: 'Zabbix server/trapper port. Agents and proxies connect to Zabbix server on this port.', dangerous: false },
      { port: 8080, protocol: 'TCP', service: 'PRTG HTTP', description: 'PRTG Network Monitor web interface HTTP port.', dangerous: false },
      { port: 8443, protocol: 'TCP', service: 'PRTG HTTPS', description: 'PRTG Network Monitor web interface HTTPS port.', dangerous: false },
      { port: 9997, protocol: 'TCP', service: 'Splunk Forwarder', description: 'Splunk Universal Forwarder to indexer communication.', dangerous: false },
      { port: 8089, protocol: 'TCP', service: 'Splunk Management', description: 'Splunk management/REST API port.', dangerous: false },
      { port: 8000, protocol: 'TCP', service: 'Splunk Web', description: 'Splunk web interface port.', dangerous: false },
      { port: 12201, protocol: 'TCP/UDP', service: 'Graylog GELF', description: 'Graylog Extended Log Format (GELF) input port.', dangerous: false },
      { port: 9000, protocol: 'TCP', service: 'Graylog Web', description: 'Graylog web interface port.', dangerous: false },
      { port: 6556, protocol: 'TCP', service: 'Check_MK Agent', description: 'Check_MK monitoring agent port.', dangerous: false },
      { port: 4317, protocol: 'TCP', service: 'OpenTelemetry gRPC', description: 'OpenTelemetry Collector gRPC receiver for traces, metrics, and logs.', dangerous: false },
      { port: 4318, protocol: 'TCP', service: 'OpenTelemetry HTTP', description: 'OpenTelemetry Collector HTTP receiver.', dangerous: false },
      { port: 2003, protocol: 'TCP', service: 'Graphite / Carbon', description: 'Graphite/Carbon metrics ingestion (plaintext protocol).', dangerous: false },
      { port: 2004, protocol: 'TCP', service: 'Graphite Pickle', description: 'Graphite Carbon pickle protocol for batched metrics.', dangerous: false },
      { port: 8125, protocol: 'UDP', service: 'StatsD', description: 'StatsD metrics aggregation service (Datadog, etc.).', dangerous: false },
    ],
  },
  {
    category: 'Infrastructure & Virtualization',
    ports: [
      { port: 443, protocol: 'TCP', service: 'vCenter / ESXi HTTPS', description: 'VMware vCenter and ESXi web management interface.', dangerous: false },
      { port: 902, protocol: 'TCP', service: 'VMware Remote Console', description: 'VMware remote console and VM heartbeat between ESXi and vCenter.', dangerous: false },
      { port: 903, protocol: 'TCP', service: 'VMware Remote Console Alt', description: 'VMware Remote Console alternate port.', dangerous: false },
      { port: 9084, protocol: 'TCP', service: 'vCenter Update Manager', description: 'VMware vCenter Update Manager (VUM) download port.', dangerous: false },
      { port: 7331, protocol: 'TCP', service: 'vSphere Replication', description: 'VMware vSphere Replication traffic port.', dangerous: false },
      { port: 8006, protocol: 'TCP', service: 'Proxmox Web UI', description: 'Proxmox VE web management interface over HTTPS.', dangerous: false },
      { port: 8007, protocol: 'TCP', service: 'Proxmox SPICE', description: 'Proxmox SPICE proxy for VM console access.', dangerous: false },
      { port: 111, protocol: 'TCP/UDP', service: 'RPC Portmapper', description: 'RPC portmapper/rpcbind. Required for NFS and other RPC services.', dangerous: true, notes: 'Restrict to hosts requiring NFS. Block from internet.' },
      { port: 2375, protocol: 'TCP', service: 'Docker HTTP API', description: 'Docker daemon unencrypted API. Exposed Docker API gives root access to the host.', dangerous: true, notes: 'Never expose. Use Docker socket or TLS-secured API (2376) instead.' },
      { port: 2376, protocol: 'TCP', service: 'Docker TLS API', description: 'Docker daemon TLS-secured API.', dangerous: false },
      { port: 2377, protocol: 'TCP', service: 'Docker Swarm', description: 'Docker Swarm cluster management port.', dangerous: false },
      { port: 4789, protocol: 'UDP', service: 'VXLAN / Docker Overlay', description: 'VXLAN and Docker Overlay network encapsulation port.', dangerous: false },
      { port: 7946, protocol: 'TCP/UDP', service: 'Docker Swarm Gossip', description: 'Docker Swarm container network discovery and gossip.', dangerous: false },
      { port: 5000, protocol: 'TCP', service: 'Docker Registry', description: 'Docker private registry default HTTP port. Use HTTPS in production.', dangerous: true, notes: 'Use HTTPS and authentication. Unauthenticated registries expose all container images.' },
      { port: 6443, protocol: 'TCP', service: 'Kubernetes API', description: 'Kubernetes API server. Restrict to management systems and CI/CD.', dangerous: false },
      { port: 10250, protocol: 'TCP', service: 'Kubernetes Kubelet', description: 'Kubernetes Kubelet API. Restrict to control plane nodes only.', dangerous: true, notes: 'Exposed Kubelet allows exec into containers. Restrict tightly.' },
      { port: 10255, protocol: 'TCP', service: 'Kubernetes Read-Only Kubelet', description: 'Kubernetes read-only Kubelet port. Disabled by default in newer versions.', dangerous: true, notes: 'Disable. Exposes pod and node information without authentication.' },
      { port: 10256, protocol: 'TCP', service: 'kube-proxy', description: 'Kubernetes kube-proxy health check port.', dangerous: false },
      { port: 2379, protocol: 'TCP', service: 'etcd Client', description: 'etcd distributed key-value store client port. Used by Kubernetes.', dangerous: true, notes: 'Restrict to control plane nodes. etcd contains all Kubernetes secrets.' },
      { port: 2380, protocol: 'TCP', service: 'etcd Peer', description: 'etcd peer communication port between cluster members.', dangerous: true, notes: 'Restrict to etcd cluster members only.' },
      { port: '30000-32767', protocol: 'TCP', service: 'Kubernetes NodePort', description: 'Kubernetes NodePort service range. External traffic enters the cluster through these ports.', dangerous: false },
      { port: 9099, protocol: 'TCP', service: 'Calico / CNI Health', description: 'Calico Kubernetes CNI health check port.', dangerous: false },
      { port: 4240, protocol: 'TCP', service: 'Cilium Health', description: 'Cilium Kubernetes CNI health check port.', dangerous: false },
    ],
  },
  {
    category: 'DevOps & Development',
    ports: [
      { port: 9418, protocol: 'TCP', service: 'Git', description: 'Git protocol for unauthenticated repository access. Unencrypted.', dangerous: true, notes: 'Use Git over SSH (22) or HTTPS (443). Plain Git protocol has no authentication.' },
      { port: 8080, protocol: 'TCP', service: 'Jenkins', description: 'Jenkins CI/CD server web interface default port.', dangerous: false, notes: 'Restrict to management network. Exposed Jenkins with script console = RCE.' },
      { port: 50000, protocol: 'TCP', service: 'Jenkins Agent', description: 'Jenkins build agent (JNLP) communication port.', dangerous: false },
      { port: 8090, protocol: 'TCP', service: 'Atlassian Confluence', description: 'Confluence wiki server default HTTP port.', dangerous: false, notes: 'Multiple critical CVEs. Patch aggressively and restrict to internal networks.' },
      { port: 8091, protocol: 'TCP', service: 'Couchbase / Confluence Alt', description: 'Couchbase Server management port and Confluence alternate port.', dangerous: false },
      { port: 8085, protocol: 'TCP', service: 'Atlassian Jira Alt', description: 'Atlassian Jira alternate HTTP port.', dangerous: false },
      { port: 7990, protocol: 'TCP', service: 'Atlassian Bitbucket', description: 'Atlassian Bitbucket Server default web port.', dangerous: false },
      { port: 7999, protocol: 'TCP', service: 'Atlassian Bitbucket SSH', description: 'Atlassian Bitbucket Server SSH Git port.', dangerous: false },
      { port: 8181, protocol: 'TCP', service: 'SonarQube / Nexus Alt', description: 'SonarQube and Nexus Repository Manager alternate ports.', dangerous: false },
      { port: 8082, protocol: 'TCP', service: 'Nexus / Artifactory Docker', description: 'Nexus Repository and JFrog Artifactory Docker registry port.', dangerous: false },
      { port: 8083, protocol: 'TCP', service: 'Mosquitto / MQTT Alt', description: 'Mosquitto MQTT broker alternate port and various build tool ports.', dangerous: false },
      { port: 8300, protocol: 'TCP', service: 'Consul RPC', description: 'HashiCorp Consul server RPC port.', dangerous: false },
      { port: 8301, protocol: 'TCP/UDP', service: 'Consul Serf LAN', description: 'HashiCorp Consul LAN gossip protocol.', dangerous: false },
      { port: 8302, protocol: 'TCP/UDP', service: 'Consul Serf WAN', description: 'HashiCorp Consul WAN gossip protocol.', dangerous: false },
      { port: 8500, protocol: 'TCP', service: 'Consul HTTP API', description: 'HashiCorp Consul HTTP API and web UI.', dangerous: false, notes: 'Restrict to management systems. Consul stores service mesh config and may contain sensitive data.' },
      { port: 8600, protocol: 'TCP/UDP', service: 'Consul DNS', description: 'HashiCorp Consul DNS interface for service discovery.', dangerous: false },
      { port: 4646, protocol: 'TCP', service: 'HashiCorp Nomad HTTP', description: 'HashiCorp Nomad orchestrator HTTP API.', dangerous: false },
      { port: 4647, protocol: 'TCP', service: 'HashiCorp Nomad RPC', description: 'HashiCorp Nomad RPC port.', dangerous: false },
      { port: 4648, protocol: 'TCP/UDP', service: 'HashiCorp Nomad Serf', description: 'HashiCorp Nomad cluster gossip protocol.', dangerous: false },
      { port: 61613, protocol: 'TCP', service: 'ActiveMQ STOMP', description: 'Apache ActiveMQ STOMP protocol port.', dangerous: true, notes: 'Restrict to application servers. ActiveMQ has had critical deserialization CVEs.' },
      { port: 61616, protocol: 'TCP', service: 'ActiveMQ OpenWire', description: 'Apache ActiveMQ OpenWire protocol (default broker port).', dangerous: true, notes: 'Restrict to application servers. CVE-2023-46604 — critical RCE exploited actively.' },
      { port: 5672, protocol: 'TCP', service: 'RabbitMQ AMQP', description: 'RabbitMQ AMQP protocol port for message broker connections.', dangerous: false },
      { port: 5671, protocol: 'TCP', service: 'RabbitMQ AMQPS', description: 'RabbitMQ AMQP over TLS.', dangerous: false },
      { port: 15672, protocol: 'TCP', service: 'RabbitMQ Management', description: 'RabbitMQ web management console.', dangerous: false, notes: 'Default credentials guest/guest. Restrict to management network.' },
      { port: 9092, protocol: 'TCP', service: 'Apache Kafka', description: 'Apache Kafka broker client communication port.', dangerous: true, notes: 'No authentication or encryption by default. Restrict to trusted clients.' },
      { port: 2181, protocol: 'TCP', service: 'Apache ZooKeeper', description: 'ZooKeeper coordination service client port. Used by Kafka, Hadoop, and others.', dangerous: true, notes: 'No authentication in default config. Restrict to cluster nodes.' },
      { port: 2888, protocol: 'TCP', service: 'ZooKeeper Peer', description: 'ZooKeeper follower-to-leader communication.', dangerous: false },
      { port: 3888, protocol: 'TCP', service: 'ZooKeeper Leader Election', description: 'ZooKeeper leader election port.', dangerous: false },
      { port: 4200, protocol: 'TCP', service: 'Angular Dev Server', description: 'Angular CLI development server default port.', dangerous: false },
      { port: 3001, protocol: 'TCP', service: 'Vite / React Dev', description: 'Vite and various React framework development server ports.', dangerous: false },
    ],
  },
  {
    category: 'Storage & NAS',
    ports: [
      { port: 5000, protocol: 'TCP', service: 'Synology DSM HTTP', description: 'Synology DiskStation Manager web interface HTTP port.', dangerous: false },
      { port: 5001, protocol: 'TCP', service: 'Synology DSM HTTPS', description: 'Synology DiskStation Manager web interface HTTPS port.', dangerous: false },
      { port: 6690, protocol: 'TCP', service: 'Synology Drive', description: 'Synology Drive client sync port.', dangerous: false },
      { port: 1723, protocol: 'TCP', service: 'Synology VPN (PPTP)', description: 'Synology VPN Server PPTP port (deprecated).', dangerous: true, notes: 'Use OpenVPN or L2TP/IPSec instead of PPTP.' },
      { port: 80, protocol: 'TCP', service: 'TrueNAS HTTP', description: 'TrueNAS/FreeNAS web interface HTTP port.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'TrueNAS HTTPS', description: 'TrueNAS/FreeNAS web interface HTTPS port.', dangerous: false },
      { port: 6789, protocol: 'TCP', service: 'Ceph Monitor', description: 'Ceph monitor daemon client communication port.', dangerous: false },
      { port: '6800-7300', protocol: 'TCP', service: 'Ceph OSD', description: 'Ceph Object Storage Daemon communication port range.', dangerous: false },
      { port: 6817, protocol: 'TCP', service: 'Ceph Manager', description: 'Ceph Manager daemon port.', dangerous: false },
      { port: 9001, protocol: 'TCP', service: 'MinIO Console', description: 'MinIO S3-compatible object storage web console.', dangerous: false },
      { port: 9000, protocol: 'TCP', service: 'MinIO API', description: 'MinIO S3-compatible object storage API port.', dangerous: false, notes: 'Restrict to trusted clients. Use TLS and access keys.' },
      { port: 24007, protocol: 'TCP', service: 'GlusterFS Daemon', description: 'GlusterFS management daemon port.', dangerous: false },
      { port: 24008, protocol: 'TCP', service: 'GlusterFS Management', description: 'GlusterFS management communication port.', dangerous: false },
      { port: 111, protocol: 'TCP/UDP', service: 'Portmapper (NFS/Gluster)', description: 'RPC portmapper required for NFS and GlusterFS.', dangerous: true, notes: 'Restrict to storage network. Block from internet.' },
    ],
  },
  {
    category: 'Collaboration & Messaging',
    ports: [
      { port: 443, protocol: 'TCP', service: 'Slack', description: 'Slack communicates entirely over HTTPS/443. No additional ports required.', dangerous: false },
      { port: 80, protocol: 'TCP', service: 'Slack Fallback', description: 'Slack falls back to HTTP/80 if HTTPS is unavailable.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Microsoft Teams', description: 'Microsoft Teams uses HTTPS/443 for signaling, chat, and file transfer.', dangerous: false },
      { port: '3478-3481', protocol: 'TCP/UDP', service: 'Microsoft Teams Media', description: 'Microsoft Teams media (audio/video) transport ports. Recommended for quality.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Zoom HTTPS', description: 'Zoom uses HTTPS/443 for signaling. Falls back to 80 if blocked.', dangerous: false },
      { port: '8801-8802', protocol: 'UDP', service: 'Zoom UDP Media', description: 'Zoom UDP ports for audio/video streams. Use these for best call quality.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Webex Meetings', description: 'Cisco Webex uses HTTPS/443 for meeting connectivity.', dangerous: false },
      { port: 9000, protocol: 'UDP', service: 'Webex Media', description: 'Cisco Webex UDP media port.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Google Meet / Google Chat', description: 'Google Meet and Google Chat operate over HTTPS/443.', dangerous: false },
      { port: 19302, protocol: 'UDP', service: 'Google WebRTC STUN', description: 'Google STUN servers for WebRTC NAT traversal used by Meet.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Discord', description: 'Discord text and signaling over HTTPS/443.', dangerous: false },
      { port: '50000-65535', protocol: 'UDP', service: 'Discord Voice', description: 'Discord voice and video media UDP range.', dangerous: false },
      { port: 7000, protocol: 'TCP', service: 'AirPlay', description: 'Apple AirPlay streaming protocol. Used for screen mirroring and audio.', dangerous: false },
      { port: 7001, protocol: 'TCP', service: 'AirPlay Alt', description: 'Apple AirPlay alternate port.', dangerous: false },
    ],
  },
  {
    category: 'Printing & Discovery',
    ports: [
      { port: 9100, protocol: 'TCP', service: 'RAW Printing / JetDirect', description: 'Direct IP printing (RAW/JetDirect). Common for network printers.', dangerous: false },
      { port: 515, protocol: 'TCP', service: 'LPD / LPR', description: 'Line Printer Daemon. Legacy Unix printing protocol.', dangerous: false },
      { port: 631, protocol: 'TCP', service: 'IPP / CUPS', description: 'Internet Printing Protocol. Used by CUPS on Linux/Mac and Windows print services.', dangerous: false },
      { port: 1900, protocol: 'UDP', service: 'UPnP SSDP', description: 'Universal Plug and Play Simple Service Discovery Protocol.', dangerous: true, notes: 'Disable UPnP on routers and firewalls. Widely exploited for amplification attacks and internal network exposure.' },
      { port: 5357, protocol: 'TCP', service: 'WSDAPI / WSD', description: 'Web Services for Devices. Windows network discovery and printer detection.', dangerous: false },
      { port: 3702, protocol: 'UDP', service: 'WS-Discovery', description: 'Web Services Dynamic Discovery. Used by network printers and cameras.', dangerous: false },
      { port: 9220, protocol: 'TCP', service: 'HP JetDirect XML', description: 'HP JetDirect XML-based printer management.', dangerous: false },
      { port: 9500, protocol: 'TCP', service: 'HP JetDirect Alt', description: 'HP JetDirect alternate management port.', dangerous: false },
    ],
  },
  {
    category: 'Network Routing & Switching',
    ports: [
      { port: 179, protocol: 'TCP', service: 'BGP', description: 'Border Gateway Protocol. Internet routing protocol between autonomous systems.', dangerous: false, notes: 'Restrict BGP peering to authorized peer IPs. BGP hijacking is a real threat.' },
      { port: 520, protocol: 'UDP', service: 'RIP', description: 'Routing Information Protocol v1/v2. Legacy distance-vector routing protocol.', dangerous: false },
      { port: 521, protocol: 'UDP', service: 'RIPng', description: 'RIP next generation for IPv6.', dangerous: false },
      { port: 646, protocol: 'TCP/UDP', service: 'LDP', description: 'Label Distribution Protocol. Used in MPLS networks.', dangerous: false },
      { port: 1985, protocol: 'UDP', service: 'HSRP', description: 'Cisco Hot Standby Router Protocol. First-hop redundancy.', dangerous: false },
      { port: 4789, protocol: 'UDP', service: 'VXLAN', description: 'Virtual Extensible LAN. Network virtualization overlay protocol.', dangerous: false },
      { port: 8472, protocol: 'UDP', service: 'VXLAN (Linux / Flannel)', description: 'VXLAN port used by Linux kernel and Flannel CNI for container overlay networking.', dangerous: false },
      { port: 4500, protocol: 'UDP', service: 'IPSec NAT Traversal', description: 'IPSec NAT-T port also used by ISAKMP for NAT traversal in routing environments.', dangerous: false },
      { port: 8285, protocol: 'UDP', service: 'Flannel VXLAN', description: 'Flannel Kubernetes CNI VXLAN UDP backend port.', dangerous: false },
      { port: 6081, protocol: 'UDP', service: 'GENEVE', description: 'Generic Network Virtualization Encapsulation. Used by OVN and OpenShift.', dangerous: false },
      { port: 2152, protocol: 'UDP', service: 'GTP-U', description: 'GPRS Tunneling Protocol User Plane. Used in mobile networks and some SD-WAN.', dangerous: false },
      { port: 4784, protocol: 'UDP', service: 'BFD', description: 'Bidirectional Forwarding Detection. Fast link failure detection for routing protocols.', dangerous: false },
    ],
  },
  {
    category: 'Microsoft 365 & Exchange',
    ports: [
      { port: 443, protocol: 'TCP', service: 'M365 / Exchange Online', description: 'All M365 services including Exchange Online, SharePoint, OneDrive, Teams, and Azure AD use HTTPS/443.', dangerous: false },
      { port: 25, protocol: 'TCP', service: 'Exchange SMTP Relay', description: 'SMTP for server-to-server mail relay. Used for on-premises Exchange to M365 hybrid and third-party connectors.', dangerous: false },
      { port: 587, protocol: 'TCP', service: 'SMTP Submission', description: 'Authenticated SMTP for applications and hybrid mail flow.', dangerous: false },
      { port: 993, protocol: 'TCP', service: 'IMAPS (Exchange)', description: 'Encrypted IMAP for Exchange Online and on-premises Exchange.', dangerous: false },
      { port: 995, protocol: 'TCP', service: 'POP3S (Exchange)', description: 'Encrypted POP3 for Exchange Online.', dangerous: false },
      { port: 80, protocol: 'TCP', service: 'Exchange AutoDiscover HTTP', description: 'Exchange AutoDiscover HTTP redirect. Redirects to HTTPS. Also used for Exchange certificate validation.', dangerous: false },
      { port: 443, protocol: 'TCP', service: 'Exchange EWS / AutoDiscover', description: 'Exchange Web Services (EWS), AutoDiscover, and ActiveSync all use HTTPS/443.', dangerous: false },
      { port: 3268, protocol: 'TCP', service: 'Exchange Global Catalog', description: 'Exchange uses LDAP Global Catalog for address book lookups.', dangerous: false },
      { port: 691, protocol: 'TCP', service: 'Exchange Routing (legacy)', description: 'Legacy Exchange routing engine port. Not used in Exchange 2013+.', dangerous: false },
      { port: 6001, protocol: 'TCP', service: 'Exchange Information Store', description: 'Exchange Information Store RPC port (on-premises).', dangerous: false },
      { port: 6002, protocol: 'TCP', service: 'Exchange Directory Referral', description: 'Exchange Directory Referral service port (on-premises).', dangerous: false },
      { port: 6004, protocol: 'TCP', service: 'Exchange DSAccess', description: 'Exchange DSAccess service for AD communication (on-premises).', dangerous: false },
    ],
  },
  {
    category: 'Industrial & IoT',
    ports: [
      { port: 502, protocol: 'TCP', service: 'Modbus TCP', description: 'Modbus TCP industrial control system protocol. No authentication or encryption.', dangerous: true, notes: 'Restrict to industrial network segment. Never expose to internet. No auth or encryption.' },
      { port: 47808, protocol: 'UDP', service: 'BACnet', description: 'Building Automation and Control network protocol. HVAC and building management systems.', dangerous: true, notes: 'Restrict to building management VLAN. No authentication in base protocol.' },
      { port: 4840, protocol: 'TCP', service: 'OPC-UA', description: 'OPC Unified Architecture. Modern industrial automation protocol with optional security.', dangerous: false },
      { port: 102, protocol: 'TCP', service: 'Siemens S7 / ISO-TSAP', description: 'Siemens S7 PLC communication protocol. Used by Siemens SCADA and TIA Portal.', dangerous: true, notes: 'Never expose. Target of Stuxnet and ongoing ICS attacks.' },
      { port: 1883, protocol: 'TCP', service: 'MQTT', description: 'Message Queuing Telemetry Transport. IoT messaging protocol. Unencrypted.', dangerous: true, notes: 'Use MQTTS (8883) for encrypted MQTT. Unauthenticated brokers are common.' },
      { port: 8883, protocol: 'TCP', service: 'MQTTS', description: 'MQTT over SSL/TLS. Encrypted IoT messaging.', dangerous: false },
      { port: 5683, protocol: 'UDP', service: 'CoAP', description: 'Constrained Application Protocol. Lightweight IoT protocol similar to HTTP.', dangerous: false },
      { port: 5684, protocol: 'UDP', service: 'CoAP DTLS', description: 'CoAP over DTLS. Encrypted constrained IoT protocol.', dangerous: false },
      { port: 554, protocol: 'TCP', service: 'RTSP', description: 'Real Time Streaming Protocol. IP camera and media streaming default port.', dangerous: true, notes: 'Restrict to security management systems. Never expose to internet.' },
      { port: 8554, protocol: 'TCP', service: 'RTSP Alternate', description: 'RTSP alternate port for IP cameras and streaming.', dangerous: true, notes: 'Same risks as port 554. Restrict access.' },
      { port: 2404, protocol: 'TCP', service: 'IEC 60870-5-104', description: 'IEC 60870-5-104 SCADA protocol for telecontrol. Used in power grid systems.', dangerous: true, notes: 'Air-gap or strictly isolate. Critical infrastructure protocol.' },
      { port: 20000, protocol: 'TCP', service: 'DNP3', description: 'Distributed Network Protocol 3. SCADA and utility automation protocol.', dangerous: true, notes: 'Restrict to control system network. No authentication in base protocol.' },
      { port: 44818, protocol: 'TCP/UDP', service: 'EtherNet/IP', description: 'EtherNet/IP industrial Ethernet protocol. Used by Allen-Bradley and other PLCs.', dangerous: true, notes: 'Restrict to industrial VLAN. No encryption.' },
      { port: 9600, protocol: 'TCP', service: 'OMRON FINS', description: 'OMRON FINS protocol for PLC communication.', dangerous: true, notes: 'Restrict to industrial network. No authentication.' },
    ],
  },
  {
    category: 'Commonly Attacked / Malware Ports',
    ports: [
      { port: 4444, protocol: 'TCP', service: 'Metasploit Default', description: 'Default Metasploit reverse shell listener. Used by many exploits and malware for C2.', dangerous: true, notes: 'Block inbound/outbound. Traffic on this port is almost always malicious in production environments.' },
      { port: 6666, protocol: 'TCP', service: 'IRC / Malware C2', description: 'IRC port. Legacy chat protocol commonly used by botnets for C2 communication.', dangerous: true, notes: 'Block outbound. IRC-based botnets are still active.' },
      { port: 6667, protocol: 'TCP', service: 'IRC / Malware C2', description: 'Standard IRC port. Commonly used by botnets for C2.', dangerous: true, notes: 'Block outbound. Unexpected IRC traffic indicates likely malware.' },
      { port: 6668, protocol: 'TCP', service: 'IRC Alt / Malware', description: 'IRC alternate port used by botnets.', dangerous: true, notes: 'Block outbound. Same risk profile as 6666/6667.' },
      { port: 6881, protocol: 'TCP/UDP', service: 'BitTorrent', description: 'BitTorrent P2P file sharing default port.', dangerous: true, notes: 'Block on corporate networks. Bandwidth consumption and potential copyright/malware risk.' },
      { port: '6881-6999', protocol: 'TCP/UDP', service: 'BitTorrent Range', description: 'BitTorrent DHT and peer communication port range.', dangerous: true, notes: 'Block on corporate networks.' },
      { port: 31337, protocol: 'TCP', service: 'Back Orifice', description: 'Back Orifice legacy Remote Access Trojan port.', dangerous: true, notes: 'Block. Any traffic here is suspicious.' },
      { port: 1337, protocol: 'TCP', service: 'Common Malware / Alt Services', description: 'Commonly used by malware and hackers as an alternate service port.', dangerous: true, notes: 'Unexpected traffic on this port warrants investigation.' },
      { port: 12345, protocol: 'TCP', service: 'NetBus RAT', description: 'NetBus Remote Access Trojan legacy port.', dangerous: true, notes: 'Block. Legacy RAT but still used in some malware.' },
      { port: 9001, protocol: 'TCP', service: 'Tor Relay', description: 'Tor network relay port. Outbound connections may indicate Tor usage.', dangerous: true, notes: 'Investigate outbound connections. May indicate Tor usage for data exfiltration.' },
      { port: 9030, protocol: 'TCP', service: 'Tor Directory', description: 'Tor directory service port.', dangerous: true, notes: 'Block outbound on corporate networks.' },
      { port: 9050, protocol: 'TCP', service: 'Tor SOCKS', description: 'Tor browser local SOCKS proxy port.', dangerous: true, notes: 'Block outbound. Indicates local Tor client usage.' },
      { port: 9051, protocol: 'TCP', service: 'Tor Control', description: 'Tor control port for local Tor process management.', dangerous: true, notes: 'Block. Should not appear on corporate endpoints.' },
      { port: 4782, protocol: 'TCP', service: 'Quasar RAT', description: 'Quasar open-source RAT default port. Commonly used in targeted attacks.', dangerous: true, notes: 'Block. Associated with multiple APT groups.' },
      { port: 1604, protocol: 'TCP', service: 'DarkComet RAT', description: 'DarkComet RAT default port.', dangerous: true, notes: 'Block. DarkComet has been used extensively by threat actors.' },
      { port: 8888, protocol: 'TCP', service: 'Various Malware / Jupyter', description: 'Used by some malware for C2 due to similarity with legitimate traffic. Also Jupyter notebooks.', dangerous: true, notes: 'Investigate unexpected outbound traffic on this port.' },
      { port: 65535, protocol: 'TCP', service: 'Common Backdoor Port', description: 'Highest possible TCP port. Commonly used by backdoors attempting to blend in at the top of the port range.', dangerous: true, notes: 'Block. Legitimate services rarely use this port.' },
      { port: 5554, protocol: 'TCP', service: 'Sasser Worm', description: 'Port used by the Sasser worm (legacy) and some modern malware.', dangerous: true, notes: 'Block. Any traffic warrants investigation.' },
      { port: 3127, protocol: 'TCP', service: 'MyDoom Backdoor', description: 'MyDoom malware backdoor port (legacy but still flagged in threat intel).', dangerous: true, notes: 'Block inbound/outbound.' },
      { port: 6000, protocol: 'TCP', service: 'X11 / Malware', description: 'X Window System display port. Also used by some malware for tunneling.', dangerous: true, notes: 'Never expose X11 to internet. Block outbound if X11 forwarding is not used.' },
    ],
  },
];
